-- Monitor de incidentes (alertas ops por WhatsApp):
--   * aox_incident agrupa por huella los errores inesperados de aox_api_log
--     (HTTP 5xx o ERROR sin status_code); aox_incident_event guarda que filas
--     del log ya se procesaron y a que incidente pertenecen.
--   * pkg_aox_incident_monitor avisa a OPS_ALERT_PHONE con la plantilla
--     META_WA_TEMPLATE_OPS_ALERT (o texto libre si no esta configurada).
--   * Job HASEL_INCIDENT_MONITOR cada 5 min via pkg_aox_job_wrapper.
--   * OPS_ALERT_PHONE (param_value NOT NULL) se inserta a mano por entorno; no versionar el valor.
-- Como AOXDEV. Idempotente.
--
-- PROD (WKSP_AOX, aplicado 2026-09-25): NO correr este script tal cual. Prod no tiene
-- pkg_aox_job_wrapper/pkg_aox_session y su pkg_aox_meta_api es anterior a la de este repo
-- (los @@ la pisarian). En prod se aplico:
--   * Las tablas y pkg_aox_incident_monitor igual que aca.
--   * En pkg_aox_meta_api solo se agregaron pr_send_template_wa y pr_send_whatsapp_text
--     al final de la spec y del body (el resto del paquete quedo como estaba).
--   * Job con job_action 'BEGIN pkg_aox_incident_monitor.pr_run; END;' (sin wrapper).
--   * OPS_ALERT_ENABLED = 1.

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT === 20260924_ops_incident_monitor ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE aox_incident (
            id_incident               NUMBER GENERATED BY DEFAULT AS IDENTITY,
            fingerprint               VARCHAR2(64)   NOT NULL,
            api_name                  VARCHAR2(200),
            process_name              VARCHAR2(200),
            error_code                NUMBER,
            error_sample              VARCHAR2(1000),
            status                    VARCHAR2(20)   DEFAULT 'OPEN' NOT NULL,
            first_seen_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            last_seen_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            occurrences               NUMBER         DEFAULT 0 NOT NULL,
            occurrences_at_last_alert NUMBER         DEFAULT 0 NOT NULL,
            alerts_sent               NUMBER         DEFAULT 0 NOT NULL,
            last_attempt_at           TIMESTAMP(6) WITH TIME ZONE,
            last_alert_at             TIMESTAMP(6) WITH TIME ZONE,
            resolved_at               TIMESTAMP(6) WITH TIME ZONE,
            resolved_note             VARCHAR2(1000),
            created_at                TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_aox_incident PRIMARY KEY (id_incident),
            CONSTRAINT uq_aox_incident_fingerprint UNIQUE (fingerprint),
            CONSTRAINT ck_aox_incident_status CHECK (status IN ('OPEN', 'RESOLVED', 'IGNORED'))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE aox_incident_event (
            id_log      NUMBER NOT NULL,
            id_incident NUMBER NOT NULL,
            org_id      NUMBER,
            occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_aox_incident_event PRIMARY KEY (id_log),
            CONSTRAINT fk_aox_incident_event_inc FOREIGN KEY (id_incident)
                REFERENCES aox_incident (id_incident)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX idx_aox_incident_event_inc ON aox_incident_event (id_incident, org_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN
            RAISE;
        END IF;
END;
/

@@../packages/PKG_AOX_META_API.pls
@@../packages/PKG_AOX_INCIDENT_MONITOR.pls
@@../packages/PKG_AOX_JOB_WRAPPER.pls

PROMPT --- Parametros (solo si faltan)
MERGE INTO app_parameter p
USING (
    SELECT 'OPS_ALERT_ENABLED' param_key, '0' param_value,
           'Monitor de incidentes: 1 envia avisos por WhatsApp, 0 solo registra.' description
      FROM dual
    UNION ALL
    SELECT 'OPS_ALERT_COOLDOWN_MIN', '60',
           'Minutos minimos entre avisos del mismo incidente abierto.'
      FROM dual
    UNION ALL
    SELECT 'META_WA_TEMPLATE_OPS_ALERT', 'alerta_incidente_hasel',
           'Plantilla Meta de avisos ops (6 variables). Sin el parametro se envia texto libre (ventana 24 h).'
      FROM dual
) s
ON (p.param_key = s.param_key)
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);
COMMIT;

PROMPT --- Job HASEL_INCIDENT_MONITOR
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'HASEL_INCIDENT_MONITOR',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN pkg_aox_job_wrapper.pr_process_incident_monitor; END;',
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=5',
        enabled         => TRUE,
        comments        => 'Agrupa errores 5xx de aox_api_log y avisa por WhatsApp (OPS_ALERT_PHONE).'
    );
    DBMS_OUTPUT.PUT_LINE('CREATE JOB HASEL_INCIDENT_MONITOR');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN
            RAISE;
        END IF;
        DBMS_OUTPUT.PUT_LINE('SKIP job existente HASEL_INCIDENT_MONITOR');
END;
/

PROMPT === Migracion 20260924_ops_incident_monitor completada ===
