-- Saldo a favor + downgrade agendado al fin de ciclo.
-- - org_subscription.account_balance / pending_plan*
-- - org_subscription_invoice.gross_amount / credit_applied
-- - org_billing_credit_ledger

PROMPT === org_subscription: account_balance + pending_plan ===

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION' AND column_name = 'ACCOUNT_BALANCE';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_subscription ADD (account_balance NUMBER DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION' AND column_name = 'PENDING_PLN_ID_PLAN';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_subscription ADD (pending_pln_id_plan NUMBER NULL)';
    END IF;

    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION' AND column_name = 'PENDING_PLAN_CHANGE_AT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_subscription ADD (pending_plan_change_at TIMESTAMP(6) WITH TIME ZONE NULL)';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE org_subscription ADD CONSTRAINT fk_orgsub_pending_plan
         FOREIGN KEY (pending_pln_id_plan) REFERENCES ref_plan (id_plan)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2260) THEN RAISE; END IF;
END;
/

COMMENT ON COLUMN org_subscription.account_balance IS
  'Saldo a favor en Gs (entero). Se aplica automaticamente en el proximo cargo.';
COMMENT ON COLUMN org_subscription.pending_pln_id_plan IS
  'Plan agendado (downgrade) que se aplica en pending_plan_change_at / fin de ciclo.';
COMMENT ON COLUMN org_subscription.pending_plan_change_at IS
  'Momento en que se aplica el plan pendiente (normalmente current_period_end).';

PROMPT === org_subscription_invoice: gross_amount + credit_applied ===

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION_INVOICE' AND column_name = 'GROSS_AMOUNT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_subscription_invoice ADD (gross_amount NUMBER NULL)';
        EXECUTE IMMEDIATE
            'UPDATE /*+ no_parallel */ org_subscription_invoice SET gross_amount = amount WHERE gross_amount IS NULL';
        COMMIT;
    END IF;

    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION_INVOICE' AND column_name = 'CREDIT_APPLIED';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_subscription_invoice ADD (credit_applied NUMBER DEFAULT 0 NOT NULL)';
    END IF;
END;
/

COMMENT ON COLUMN org_subscription_invoice.gross_amount IS
  'Monto antes de descontar saldo a favor. amount = neto cobrado (o 0 si cubierto por credito).';
COMMENT ON COLUMN org_subscription_invoice.credit_applied IS
  'Gs de saldo a favor aplicados a esta factura (se consumen al pasar a PAID).';

PROMPT === org_billing_credit_ledger ===

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'ORG_BILLING_CREDIT_LEDGER';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE org_billing_credit_ledger (
              id_credit_ledger    NUMBER GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization NUMBER NOT NULL,
              delta_amount        NUMBER NOT NULL,
              balance_after       NUMBER NOT NULL,
              reason              VARCHAR2(30) NOT NULL,
              invoice_id          NUMBER NULL,
              ref_code            VARCHAR2(40) NULL,
              created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT pk_org_billing_credit_ledger PRIMARY KEY (id_credit_ledger),
              CONSTRAINT chk_orgbcl_reason CHECK (reason IN ('CANCEL_ADDON', 'APPLY_INVOICE', 'MANUAL_ADJ')),
              CONSTRAINT fk_orgbcl_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization) ON DELETE CASCADE,
              CONSTRAINT fk_orgbcl_invoice FOREIGN KEY (invoice_id)
                REFERENCES org_subscription_invoice (id_invoice) ON DELETE SET NULL
            )
        ]';
        EXECUTE IMMEDIATE
            'CREATE INDEX idx_orgbcl_org_created ON org_billing_credit_ledger (org_id_organization, created_at)';
    END IF;
END;
/

COMMIT;
PROMPT OK: billing credit + pending plan
