-- Complemento Cuerpo (BODY_MAP): tablas, catálogo clínico y seed de tienda.
-- Sin ORDS ni ADDONS_BILLING_LIVE (preview org_addon como odontograma).

PROMPT === ref_body_region ===
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ref_body_region (
      region_code   VARCHAR2(40)  NOT NULL,
      view_code     VARCHAR2(10)  NOT NULL,
      label         VARCHAR2(100) NOT NULL,
      sort_order    NUMBER        DEFAULT 0 NOT NULL,
      is_active     NUMBER(1,0)   DEFAULT 1 NOT NULL,
      CONSTRAINT pk_ref_body_region PRIMARY KEY (region_code),
      CONSTRAINT chk_ref_body_region_view CHECK (view_code IN ('FRONT', 'BACK', 'SIDE')),
      CONSTRAINT chk_ref_body_region_active CHECK (is_active IN (0, 1))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === ref_body_joint_test ===
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ref_body_joint_test (
      joint_code    VARCHAR2(20)  NOT NULL,
      test_code     VARCHAR2(30)  NOT NULL,
      label         VARCHAR2(100) NOT NULL,
      sort_order    NUMBER        DEFAULT 0 NOT NULL,
      is_active     NUMBER(1,0)   DEFAULT 1 NOT NULL,
      CONSTRAINT pk_ref_body_joint_test PRIMARY KEY (joint_code, test_code),
      CONSTRAINT chk_ref_body_joint CHECK (joint_code IN ('SHOULDER', 'HIP', 'KNEE', 'ANKLE')),
      CONSTRAINT chk_ref_body_joint_test_active CHECK (is_active IN (0, 1))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === customer_body_snapshot ===
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE customer_body_snapshot (
      id_body_snapshot    NUMBER GENERATED BY DEFAULT AS IDENTITY,
      org_id_organization NUMBER NOT NULL,
      cus_id_customer     NUMBER NOT NULL,
      app_id_appointment  NUMBER NOT NULL,
      silhouette          VARCHAR2(10) DEFAULT 'NEUTRAL' NOT NULL,
      snapshot_json       CLOB NOT NULL,
      captured_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_by_user     NUMBER NULL,
      created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE customer_body_snapshot ADD CONSTRAINT pk_customer_body_snapshot PRIMARY KEY (id_body_snapshot)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE customer_body_snapshot ADD CONSTRAINT chk_body_snap_silhouette CHECK (silhouette IN ('NEUTRAL', 'FEMALE', 'MALE'))]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE UNIQUE INDEX uq_body_snap_org_appt
      ON customer_body_snapshot (org_id_organization, app_id_appointment)
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE INDEX idx_body_snap_org_cus
      ON customer_body_snapshot (org_id_organization, cus_id_customer, captured_at)
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- Catálogo de regiones (allowlist; sin SPINE_/FACE_/NAIL_)
MERGE INTO ref_body_region t
USING (
  SELECT 'FRONT_GENERIC' AS region_code, 'FRONT' AS view_code, 'Frente (general)' AS label, 1 AS sort_order FROM dual UNION ALL
  SELECT 'BACK_GENERIC', 'BACK', 'Espalda (general)', 1 FROM dual UNION ALL
  SELECT 'SIDE_GENERIC', 'SIDE', 'Lado (general)', 1 FROM dual UNION ALL
  SELECT 'FRONT_SHOULDER_L', 'FRONT', 'Hombro izquierdo', 10 FROM dual UNION ALL
  SELECT 'FRONT_SHOULDER_R', 'FRONT', 'Hombro derecho', 11 FROM dual UNION ALL
  SELECT 'FRONT_KNEE_L', 'FRONT', 'Rodilla izquierda', 20 FROM dual UNION ALL
  SELECT 'FRONT_KNEE_R', 'FRONT', 'Rodilla derecha', 21 FROM dual UNION ALL
  SELECT 'BACK_HIP_L', 'BACK', 'Cadera izquierda', 30 FROM dual UNION ALL
  SELECT 'BACK_HIP_R', 'BACK', 'Cadera derecha', 31 FROM dual UNION ALL
  SELECT 'SIDE_ANKLE_L', 'SIDE', 'Tobillo izquierdo', 40 FROM dual UNION ALL
  SELECT 'SIDE_ANKLE_R', 'SIDE', 'Tobillo derecho', 41 FROM dual
) s
ON (t.region_code = s.region_code)
WHEN NOT MATCHED THEN
  INSERT (region_code, view_code, label, sort_order, is_active)
  VALUES (s.region_code, s.view_code, s.label, s.sort_order, 1);
COMMIT;

MERGE INTO ref_body_joint_test t
USING (
  SELECT 'SHOULDER' AS joint_code, 'NEER' AS test_code, 'Neer' AS label, 1 AS sort_order FROM dual UNION ALL
  SELECT 'SHOULDER', 'HAWKINS', 'Hawkins', 2 FROM dual UNION ALL
  SELECT 'SHOULDER', 'JOBES', 'Jobe', 3 FROM dual UNION ALL
  SELECT 'HIP', 'FABER', 'FABER', 1 FROM dual UNION ALL
  SELECT 'HIP', 'FADIR', 'FADIR', 2 FROM dual UNION ALL
  SELECT 'HIP', 'THOMAS', 'Thomas', 3 FROM dual UNION ALL
  SELECT 'KNEE', 'LACHMAN', 'Lachman', 1 FROM dual UNION ALL
  SELECT 'KNEE', 'DRAWER_ANT', 'Cajón ant.', 2 FROM dual UNION ALL
  SELECT 'KNEE', 'MCMURRAY', 'McMurray', 3 FROM dual UNION ALL
  SELECT 'ANKLE', 'ANTERIOR_DRAWER', 'Cajón ant.', 1 FROM dual UNION ALL
  SELECT 'ANKLE', 'TALAR_TILT', 'Inclinación talar', 2 FROM dual UNION ALL
  SELECT 'ANKLE', 'THOMPSON', 'Thompson', 3 FROM dual
) s
ON (t.joint_code = s.joint_code AND t.test_code = s.test_code)
WHEN NOT MATCHED THEN
  INSERT (joint_code, test_code, label, sort_order, is_active)
  VALUES (s.joint_code, s.test_code, s.label, s.sort_order, 1);
COMMIT;

-- Puentes addon ↔ rubros existentes (ids 4 Salud, 6 Fisioterapia).
-- Sin ensure_specialty: una sola taxonomía de 13 filas en org_specialty.

-- Addon BODY_MAP (MERGE por code)
MERGE INTO ref_addon t
USING (
  SELECT 'BODY_MAP' AS code,
         'Cuerpo' AS name,
         'Mapa corporal, zoom de articulación y evolución por sesión.' AS short_description,
         'BODY_MAP' AS feature_code,
         59000 AS price_amount,
         'PYG' AS currency,
         'MONTHLY' AS billing_period,
         1 AS is_active,
         2 AS sort_order,
         1 AS requires_specialty_bridge
    FROM dual
) s
ON (t.code = s.code)
WHEN MATCHED THEN UPDATE SET
  t.name = s.name,
  t.short_description = s.short_description,
  t.feature_code = s.feature_code,
  t.price_amount = s.price_amount,
  t.currency = s.currency,
  t.billing_period = s.billing_period,
  t.is_active = s.is_active,
  t.sort_order = s.sort_order,
  t.requires_specialty_bridge = s.requires_specialty_bridge
WHEN NOT MATCHED THEN
  INSERT (id_addon, code, name, short_description, feature_code, price_amount, currency, billing_period, is_active, sort_order, requires_specialty_bridge)
  VALUES (
    (SELECT NVL(MAX(id_addon), 0) + 1 FROM ref_addon),
    s.code, s.name, s.short_description, s.feature_code, s.price_amount, s.currency, s.billing_period, s.is_active, s.sort_order, s.requires_specialty_bridge
  );
COMMIT;

MERGE INTO ref_addon_specialty t
USING (
  SELECT ra.id_addon AS rad_id_addon, os.id_org_specialty AS osp_id_org_specialty
    FROM ref_addon ra
    JOIN org_specialty os ON os.id_org_specialty IN (4, 6)
   WHERE ra.code = 'BODY_MAP'
) s
ON (t.rad_id_addon = s.rad_id_addon AND t.osp_id_org_specialty = s.osp_id_org_specialty)
WHEN NOT MATCHED THEN
  INSERT (rad_id_addon, osp_id_org_specialty)
  VALUES (s.rad_id_addon, s.osp_id_org_specialty);
COMMIT;

PROMPT OK: cuerpo body_map migration
