-- Migracion: perfil publico — banner, facebook/instagram, galeria (max 30)
--
--   ALTER workspace_setting
--   CREATE org_gallery_image
--   Redeploy packages + ORDS gallery endpoints

PROMPT === 1. Columnas banner / redes en workspace_setting ===
BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE workspace_setting ADD banner_url VARCHAR2(500) NULL]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE workspace_setting ADD banner_filename VARCHAR2(255) NULL]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE workspace_setting ADD banner_mime_type VARCHAR2(100) NULL]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE workspace_setting ADD facebook_url VARCHAR2(500) NULL]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE workspace_setting ADD instagram_url VARCHAR2(500) NULL]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT === 2. Tabla org_gallery_image ===
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_gallery_image (
          id_gallery_image    NUMBER GENERATED BY DEFAULT AS IDENTITY,
          org_id_organization NUMBER NOT NULL,
          image_url           VARCHAR2(1000) NOT NULL,
          filename            VARCHAR2(255) NULL,
          mime_type           VARCHAR2(150) NULL,
          sort_order          NUMBER DEFAULT 1 NOT NULL,
          created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT pk_org_gallery_image PRIMARY KEY (id_gallery_image),
          CONSTRAINT chk_orggal_sort CHECK (sort_order BETWEEN 1 AND 30),
          CONSTRAINT fk_orggal_organization FOREIGN KEY (org_id_organization)
            REFERENCES organization (id_organization) ON DELETE CASCADE
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE INDEX idx_orggal_org_sort ON org_gallery_image (org_id_organization, sort_order)
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT === 3. Packages ===
@@../packages/PKG_AOX_BUCKET.pls
@@../packages/PKG_AOX_WORKSPACE_API.pls
@@../packages/PKG_AOX_PUBLIC_BOOKING_API.pls

PROMPT === 4. ORDS gallery endpoints ===
BEGIN
    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'workspace/gallery'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'workspace/gallery',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_workspace_api.pr_add_gallery_image(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_body          => :body_text,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'workspace/gallery',
        p_method      => 'PUT',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_workspace_api.pr_reorder_gallery(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_body          => :body_text,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'workspace/gallery/:id'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'workspace/gallery/:id',
        p_method      => 'DELETE',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_workspace_api.pr_delete_gallery_image(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_gallery_id    => :id,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    COMMIT;
END;
/

PROMPT === 5. Recompilacion ===
BEGIN
    DBMS_UTILITY.compile_schema(schema => USER, compile_all => FALSE);
END;
/

PROMPT === 20260718_public_profile_media finalizada ===
