-- Migracion: Suscripcion Hasel con pago recurrente Pagopar (uPay)
-- Plan: pagopar_recurrente_suscripcion
--
-- Contenido:
--   * Tabla ORG_PAYMENT_CARD (tarjetas catastradas, pago-recurrente/3.0).
--   * Columnas nuevas en org_subscription (auto_renew, last_charge_at, charge_retry_count).
--   * Parametros de plataforma para la API de pago recurrente / iframe uPay.
--   * Recompila PKG_AOX_PAGOPAR_API y PKG_AOX_SUBSCRIPTION_BILLING_API.
--
-- El job DBMS_SCHEDULER va en un archivo aparte (20260711_subscription_recurring_job.sql),
-- NO se ejecuta en DEV. Los handlers ORDS van en 20260711_subscription_recurring_ords.sql.
--
-- Dependencias: organization, ref_plan, org_subscription, org_subscription_invoice,
--               PKG_AOX_UTIL, PKG_AOX_SUBSCRIPTION_API, FN_GET_PARAMETER.
-- NOTA ADB: DML con no_parallel y commit por statement (ver reglas del proyecto).

PROMPT === 1. Tabla ORG_PAYMENT_CARD (idempotente) ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'ORG_PAYMENT_CARD';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE org_payment_card (
              id_payment_card       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization   NUMBER                      NOT NULL,
              provider              VARCHAR2(20)                DEFAULT 'uPay' NOT NULL,
              pagopar_identificador VARCHAR2(64)                NOT NULL,
              pagopar_card_id       VARCHAR2(64)                NULL,
              brand                 VARCHAR2(40)                NULL,
              masked_number         VARCHAR2(40)                NULL,
              card_type             VARCHAR2(20)                NULL,
              issuer                VARCHAR2(120)               NULL,
              status                VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
              is_default            NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              confirmed_at          TIMESTAMP(6) WITH TIME ZONE NULL,
              updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
            )]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_orgcard_org_status ON org_payment_card (org_id_organization, status)';
        EXECUTE IMMEDIATE 'ALTER TABLE org_payment_card ADD CONSTRAINT pk_org_payment_card PRIMARY KEY (id_payment_card)';
        EXECUTE IMMEDIATE 'ALTER TABLE org_payment_card ADD CONSTRAINT chk_orgcard_status CHECK (status IN (''PENDING'',''ACTIVE'',''DELETED''))';
        EXECUTE IMMEDIATE 'ALTER TABLE org_payment_card ADD CONSTRAINT chk_orgcard_default CHECK (is_default IN (0,1))';
        EXECUTE IMMEDIATE 'ALTER TABLE org_payment_card ADD CONSTRAINT fk_orgcard_org FOREIGN KEY (org_id_organization) REFERENCES organization (id_organization) ON DELETE CASCADE';
    END IF;
END;
/

PROMPT === 2. Columnas nuevas en org_subscription (idempotente) ===
DECLARE
    PROCEDURE add_col(pi_ddl IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE pi_ddl;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE NOT IN (-1430) THEN  -- ORA-01430: la columna ya existe
                RAISE;
            END IF;
    END;
BEGIN
    add_col('ALTER TABLE org_subscription ADD (auto_renew NUMBER(1,0) DEFAULT 1 NOT NULL)');
    add_col('ALTER TABLE org_subscription ADD (last_charge_at TIMESTAMP(6) WITH TIME ZONE NULL)');
    add_col('ALTER TABLE org_subscription ADD (charge_retry_count NUMBER DEFAULT 0 NOT NULL)');
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE org_subscription ADD CONSTRAINT chk_orgsub_autorenew CHECK (auto_renew IN (0,1))';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE NOT IN (-2264, -2260) THEN  -- constraint ya existe
                RAISE;
            END IF;
    END;
END;
/

PROMPT === 3. Parametros de plataforma (pago recurrente / iframe uPay) ===
MERGE INTO app_parameter t
USING (
  SELECT 'PAGOPAR_RECURRENTE_BASE_URL'      AS param_key, 'Base URL de la API Pagopar pago-recurrente/3.0.'                         AS description, 'https://api.pagopar.com/api/pago-recurrente/3.0/' AS param_value FROM dual UNION ALL
  SELECT 'PAGOPAR_UPAY_IFRAME_URL'          AS param_key, 'URL base del iframe uPay de catastro (se le concatena el id-form).'      AS description, 'https://www.pagopar.com/upay-iframe/?id-form='  AS param_value FROM dual UNION ALL
  SELECT 'PAGOPAR_UPAY_RETURN_URL'          AS param_key, 'URL HTTPS donde se incrusta el iframe y a la que Pagopar redirige.'      AS description, 'https://hasel.app/panel/plan'                    AS param_value FROM dual UNION ALL
  SELECT 'SUBSCRIPTION_CARD_PROVIDER'       AS param_key, 'Proveedor de catastro de tarjeta (uPay o Bancard).'                      AS description, 'uPay'                                            AS param_value FROM dual UNION ALL
  SELECT 'SUBSCRIPTION_MAX_CHARGE_RETRIES'  AS param_key, 'Intentos maximos de cobro por ciclo antes de dejar de reintentar.'       AS description, '4'                                               AS param_value FROM dual
) s
ON (t.param_key = s.param_key)
WHEN NOT MATCHED THEN
  INSERT (param_key, param_value, description)
  VALUES (s.param_key, s.param_value, s.description);

COMMIT;

PROMPT === 4. Recompilar paquetes ===
@@../packages/PKG_AOX_PAGOPAR_API.pls
@@../packages/PKG_AOX_SUBSCRIPTION_BILLING_API.pls

PROMPT === 5. Recompilacion de objetos invalidos ===
BEGIN
    DBMS_UTILITY.compile_schema(schema => USER, compile_all => FALSE);
END;
/

PROMPT === Migracion pago recurrente OK ===
PROMPT Recorda: registrar handlers ORDS (20260711_subscription_recurring_ords.sql)
PROMPT y crear el job en PRODUCCION (20260711_subscription_recurring_job.sql).
