-- Campanas push admin (Hasel_admn): catalogo + campana + vars + delivery + package.
-- No modifica PKG_AOX_FCM_API ni notificaciones fijas.

PROMPT === push_var_catalog ===
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE push_var_catalog (
          id_var_catalog NUMBER         GENERATED BY DEFAULT AS IDENTITY,
          var_key        VARCHAR2(50)   NOT NULL,
          label_es       VARCHAR2(120)  NOT NULL,
          sample_value   VARCHAR2(200)  NULL,
          is_active      NUMBER(1,0)    DEFAULT 1 NOT NULL,
          sort_order     NUMBER(4,0)    DEFAULT 0 NOT NULL,
          CONSTRAINT pk_push_var_catalog PRIMARY KEY (id_var_catalog),
          CONSTRAINT uq_push_var_catalog_key UNIQUE (var_key),
          CONSTRAINT chk_push_var_cat_active CHECK (is_active IN (0, 1))
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('push_var_catalog creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('push_var_catalog ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

MERGE INTO push_var_catalog t
USING (
  SELECT 'NOMBRE'   AS var_key, 'Nombre'   AS label_es, 'Ana'             AS sample_value, 10 AS sort_order FROM dual UNION ALL
  SELECT 'APELLIDO' AS var_key, 'Apellido' AS label_es, 'Giménez'         AS sample_value, 20 AS sort_order FROM dual UNION ALL
  SELECT 'EMAIL'    AS var_key, 'Email'    AS label_es, 'ana@ejemplo.com' AS sample_value, 30 AS sort_order FROM dual
) s
ON (t.var_key = s.var_key)
WHEN MATCHED THEN UPDATE SET
  t.label_es = s.label_es, t.sample_value = s.sample_value, t.sort_order = s.sort_order, t.is_active = 1
WHEN NOT MATCHED THEN INSERT (var_key, label_es, sample_value, is_active, sort_order)
VALUES (s.var_key, s.label_es, s.sample_value, 1, s.sort_order);

COMMIT;

PROMPT === push_campaign ===
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE push_campaign (
          id_campaign         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
          name                VARCHAR2(200)               NOT NULL,
          title_template      VARCHAR2(500)               NOT NULL,
          body_template       VARCHAR2(4000)              NOT NULL,
          url_template        VARCHAR2(1000)              NULL,
          audience_type       VARCHAR2(20)                NOT NULL,
          role_id             NUMBER                      NULL,
          send_at             TIMESTAMP(6) WITH TIME ZONE NULL,
          status              VARCHAR2(20)                DEFAULT ''DRAFT'' NOT NULL,
          scheduler_job_name  VARCHAR2(128)               NULL,
          is_enabled          NUMBER(1,0)                 DEFAULT 1 NOT NULL,
          sent_at             TIMESTAMP(6) WITH TIME ZONE NULL,
          error_message       VARCHAR2(4000)              NULL,
          created_by          VARCHAR2(100)               NULL,
          created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT pk_push_campaign PRIMARY KEY (id_campaign),
          CONSTRAINT uq_push_camp_job_name UNIQUE (scheduler_job_name),
          CONSTRAINT chk_push_camp_audience CHECK (audience_type IN (''ALL_ACTIVE'', ''ROLE'')),
          CONSTRAINT chk_push_camp_status CHECK (
            status IN (''DRAFT'', ''SCHEDULED'', ''SENDING'', ''SENT'', ''CANCELLED'', ''DISABLED'', ''ERROR'')
          ),
          CONSTRAINT chk_push_camp_enabled CHECK (is_enabled IN (0, 1)),
          CONSTRAINT chk_push_camp_role_req CHECK (
            (audience_type = ''ALL_ACTIVE'' AND role_id IS NULL)
            OR (audience_type = ''ROLE'' AND role_id IS NOT NULL)
          ),
          CONSTRAINT fk_push_camp_role FOREIGN KEY (role_id) REFERENCES role (id_role)
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('push_campaign creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('push_campaign ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_push_camp_status ON push_campaign (status, send_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === push_campaign_var ===
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE push_campaign_var (
          id_campaign_var NUMBER         GENERATED BY DEFAULT AS IDENTITY,
          id_campaign     NUMBER         NOT NULL,
          var_key         VARCHAR2(50)   NOT NULL,
          var_value       VARCHAR2(4000) NOT NULL,
          CONSTRAINT pk_push_campaign_var PRIMARY KEY (id_campaign_var),
          CONSTRAINT uq_push_camp_var_key UNIQUE (id_campaign, var_key),
          CONSTRAINT fk_push_camp_var_camp FOREIGN KEY (id_campaign)
            REFERENCES push_campaign (id_campaign) ON DELETE CASCADE
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('push_campaign_var creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('push_campaign_var ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_push_camp_var_camp ON push_campaign_var (id_campaign)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === push_campaign_delivery ===
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE push_campaign_delivery (
          id_delivery      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
          id_campaign      NUMBER                      NOT NULL,
          platform_user_id NUMBER                      NOT NULL,
          fcm_token        VARCHAR2(1000)              NULL,
          resolved_title   VARCHAR2(500)               NULL,
          resolved_body    VARCHAR2(4000)              NULL,
          status           VARCHAR2(20)                DEFAULT ''PENDING'' NOT NULL,
          error_message    VARCHAR2(4000)              NULL,
          sent_at          TIMESTAMP(6) WITH TIME ZONE NULL,
          created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT pk_push_campaign_delivery PRIMARY KEY (id_delivery),
          CONSTRAINT chk_push_deliv_status CHECK (status IN (''PENDING'', ''SENT'', ''FAILED'')),
          CONSTRAINT fk_push_deliv_camp FOREIGN KEY (id_campaign)
            REFERENCES push_campaign (id_campaign) ON DELETE CASCADE,
          CONSTRAINT fk_push_deliv_pu FOREIGN KEY (platform_user_id)
            REFERENCES platform_user (id_platform_user)
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('push_campaign_delivery creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('push_campaign_delivery ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_push_deliv_camp ON push_campaign_delivery (id_campaign, status)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_push_deliv_pu ON push_campaign_delivery (platform_user_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === Package pkg_aox_push_campaign ===
-- Compilar package desde archivo (SQL*Plus / SQLcl):
-- @@packages/PKG_AOX_PUSH_CAMPAIGN.pls
-- Si se aplica solo esta migracion via ORDS/MCP, ejecutar el .pls por separado.

PROMPT === Migracion push_campaign tablas lista. Compilar package: @@packages/PKG_AOX_PUSH_CAMPAIGN.pls ===
