-- Webhook WABA (POST attendance-reply):
--   * Tabla aox_log_webhook_meta + pkg_aox_meta_api.pr_log_webhook_meta (autonomous).
--   * Body desde :body (BLOB -> CLOB); :body_text llega vacio si tambien se bindea :body.
--   * Firma X-Hub-Signature-256 como parametro HEADER ORDS (:x_hub_signature_256).
--   * META_APP_SECRET se carga en app_parameter por entorno; no versionar el valor.

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE aox_log_webhook_meta (
            id_log     NUMBER GENERATED BY DEFAULT AS IDENTITY,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            payload    CLOB
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE aox_log_webhook_meta ADD created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    ORDS.define_handler(
        p_module_name    => 'whatsapp',
        p_pattern        => 'attendance-reply',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_body_blob BLOB := :body;
    v_body      CLOB;
    v_sig       VARCHAR2(4000);
    v_payload   VARCHAR2(200);
    v_response  json_object_t := json_object_t();
    v_dest      INTEGER := 1;
    v_src       INTEGER := 1;
    v_ctx       INTEGER := DBMS_LOB.default_lang_ctx;
    v_warn      INTEGER;
BEGIN
    IF v_body_blob IS NOT NULL AND DBMS_LOB.getlength(v_body_blob) > 0 THEN
        DBMS_LOB.createtemporary(v_body, TRUE);
        DBMS_LOB.converttoclob(
            dest_lob     => v_body,
            src_blob     => v_body_blob,
            amount       => DBMS_LOB.lobmaxsize,
            dest_offset  => v_dest,
            src_offset   => v_src,
            blob_csid    => NLS_CHARSET_ID('AL32UTF8'),
            lang_context => v_ctx,
            warning      => v_warn
        );
    END IF;

    BEGIN
        pkg_aox_meta_api.pr_log_webhook_meta(pi_payload => v_body);
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        v_sig := :x_hub_signature_256;
    EXCEPTION
        WHEN OTHERS THEN
            v_sig := NULL;
    END;

    IF v_sig IS NULL THEN
        BEGIN
            v_sig := owa_util.get_cgi_env('HTTP_X_HUB_SIGNATURE_256');
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
    END IF;

    IF v_sig IS NULL THEN
        BEGIN
            v_sig := owa_util.get_cgi_env('X-Hub-Signature-256');
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
    END IF;

    IF NVL(pkg_aox_meta_api.fn_verify_webhook_signature(v_body_blob, v_sig), 0) <> 1 THEN
        BEGIN
            pkg_aox_meta_api.pr_log_webhook_meta(
                pi_payload => '{"hmac":"fail","sig_present":' ||
                    CASE WHEN v_sig IS NULL THEN 'false' ELSE 'true' END ||
                    ',"sig_prefix":"' || SUBSTR(REPLACE(NVL(v_sig, ''), '"', ''), 1, 12) ||
                    '","blob_len":' || NVL(TO_CHAR(DBMS_LOB.getlength(v_body_blob)), '0') || '}'
            );
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
        :status_code := 403;
        v_response.put('status', 'error');
        v_response.put('message', 'Firma de webhook invalida o META_APP_SECRET no configurado.');
        owa_util.mime_header('application/json', FALSE);
        owa_util.http_header_close;
        htp.prn(v_response.to_clob());
        RETURN;
    END IF;

    APEX_JSON.parse(v_body);

    v_payload := APEX_JSON.get_varchar2(
        p_path => 'entry[1].changes[1].value.messages[1].button.payload'
    );

    IF v_payload IS NULL THEN
        v_payload := APEX_JSON.get_varchar2(
            p_path => 'entry[1].changes[1].value.messages[1].interactive.button_reply.id'
        );
    END IF;

    IF v_payload IS NULL THEN
        v_payload := APEX_JSON.get_varchar2(
            p_path => 'entry[1].changes[1].value.messages[1].interactive.button_reply.payload'
        );
    END IF;

    IF v_payload IS NULL
       OR NOT REGEXP_LIKE(
            UPPER(TRIM(v_payload)),
            '^(CONFIRMAR_RESERVA_ID_|CANCELAR_RESERVA_ID_)[0-9]+$'
       ) THEN
        :status_code := 200;
        v_response.put('status', 'ignored');
        v_response.put('message', 'Evento sin payload de asistencia valido.');
        owa_util.mime_header('application/json', FALSE);
        owa_util.http_header_close;
        htp.prn(v_response.to_clob());
        RETURN;
    END IF;

    pkg_aox_meta_api.pr_apply_attendance_payload(pi_payload => v_payload);

    :status_code := 200;
    v_response.put('status', 'success');
    v_response.put('message', 'Respuesta registrada.');
    owa_util.mime_header('application/json', FALSE);
    owa_util.http_header_close;
    htp.prn(v_response.to_clob());
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
        v_response := json_object_t();
        v_response.put('status', 'error');
        v_response.put('message', REGEXP_REPLACE(SQLERRM, '^ORA-[0-9]+: ', ''));
        owa_util.mime_header('application/json', FALSE);
        owa_util.http_header_close;
        htp.prn(v_response.to_clob());
END;
]',
        p_items_per_page => 0
    );

    ORDS.define_parameter(
        p_module_name        => 'whatsapp',
        p_pattern            => 'attendance-reply',
        p_method             => 'POST',
        p_name               => 'X-Hub-Signature-256',
        p_bind_variable_name => 'x_hub_signature_256',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );
    COMMIT;
END;
/

PROMPT === 20260826_webhook_meta_log done ===
