-- Disputas de reembolso: tablas de caso/evidencia/strike/outbox + archivo de claims legacy.

PROMPT === 20260830_refund_disputes DDL ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_refund_dispute (
          id_dispute            NUMBER GENERATED BY DEFAULT AS IDENTITY,
          org_id_organization   NUMBER NOT NULL,
          app_id_appointment    NUMBER NOT NULL,
          dispute_source        VARCHAR2(20) NOT NULL,
          dispute_status        VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
          proof_due_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
          current_evidence_id   NUMBER NULL,
          close_reason          VARCHAR2(40) NULL,
          notes                 VARCHAR2(500) NULL,
          opened_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          closed_at             TIMESTAMP(6) WITH TIME ZONE NULL,
          closed_by             NUMBER NULL,
          created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT pk_org_refund_dispute PRIMARY KEY (id_dispute),
          CONSTRAINT fk_refund_dispute_org FOREIGN KEY (org_id_organization)
            REFERENCES organization (id_organization) ON DELETE CASCADE,
          CONSTRAINT fk_refund_dispute_app FOREIGN KEY (app_id_appointment)
            REFERENCES appointment (id_appointment),
          CONSTRAINT chk_refund_dispute_source CHECK (dispute_source IN ('CUSTOMER_SENT', 'CUSTOMER_PENDING')),
          CONSTRAINT chk_refund_dispute_status CHECK (dispute_status IN (
            'OPEN', 'EVIDENCE_PROCESSING', 'EVIDENCE_ACCEPTED', 'EXPIRED_STRIKE', 'CUSTOMER_FOLLOW_UP', 'DISMISSED'
          )),
          CONSTRAINT chk_refund_dispute_close CHECK (
            close_reason IS NULL OR close_reason IN ('PROOF_OK', 'TIMEOUT', 'WAIVED', 'CUSTOMER_INSISTED')
          )
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_refund_dispute_appointment ON org_refund_dispute (app_id_appointment)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_refund_dispute_timeout ON org_refund_dispute (dispute_status, proof_due_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_refund_dispute_org_status ON org_refund_dispute (org_id_organization, dispute_status)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_refund_dispute_evidence (
          id_evidence           NUMBER GENERATED BY DEFAULT AS IDENTITY,
          dispute_id            NUMBER NOT NULL,
          attempt_n             NUMBER NOT NULL,
          object_key            VARCHAR2(500) NOT NULL,
          mime_type             VARCHAR2(150) NULL,
          size_bytes            NUMBER DEFAULT 0 NOT NULL,
          sha256                VARCHAR2(64) NULL,
          uploaded_by           NUMBER NULL,
          uploaded_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          ocr_status            VARCHAR2(30) DEFAULT 'PROCESSING' NOT NULL,
          ocr_amount            NUMBER NULL,
          ocr_alias_hint        VARCHAR2(200) NULL,
          ocr_confidence        NUMBER NULL,
          ocr_raw               CLOB NULL,
          extractor_version     VARCHAR2(40) DEFAULT 'refund_proof_v1' NOT NULL,
          ocr_checked_at        TIMESTAMP(6) WITH TIME ZONE NULL,
          CONSTRAINT pk_org_refund_dispute_ev PRIMARY KEY (id_evidence),
          CONSTRAINT fk_refund_evidence_dispute FOREIGN KEY (dispute_id)
            REFERENCES org_refund_dispute (id_dispute) ON DELETE CASCADE,
          CONSTRAINT chk_refund_evidence_ocr CHECK (ocr_status IN (
            'PROCESSING', 'ACCEPTED', 'MANUAL_REVIEW', 'REJECTED_DEFINITE', 'TECHNICAL_FAILURE'
          ))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_refund_evidence_dispute ON org_refund_dispute_evidence (dispute_id, attempt_n)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_refund_strike (
          id_strike             NUMBER GENERATED BY DEFAULT AS IDENTITY,
          org_id_organization   NUMBER NOT NULL,
          dispute_id            NUMBER NOT NULL,
          reason                VARCHAR2(40) DEFAULT 'TIMEOUT' NOT NULL,
          created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT pk_org_refund_strike PRIMARY KEY (id_strike),
          CONSTRAINT uq_refund_strike_dispute UNIQUE (dispute_id),
          CONSTRAINT fk_refund_strike_org FOREIGN KEY (org_id_organization)
            REFERENCES organization (id_organization) ON DELETE CASCADE,
          CONSTRAINT fk_refund_strike_dispute FOREIGN KEY (dispute_id)
            REFERENCES org_refund_dispute (id_dispute),
          CONSTRAINT chk_refund_strike_reason CHECK (reason IN ('TIMEOUT'))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_refund_notify_outbox (
          id_outbox             NUMBER GENERATED BY DEFAULT AS IDENTITY,
          org_id_organization   NUMBER NOT NULL,
          dispute_id            NUMBER NOT NULL,
          channel               VARCHAR2(20) DEFAULT 'FCM' NOT NULL,
          event_code            VARCHAR2(40) NOT NULL,
          dedupe_key            VARCHAR2(120) NOT NULL,
          status                VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
          attempts              NUMBER DEFAULT 0 NOT NULL,
          last_error            VARCHAR2(400) NULL,
          payload               CLOB NULL,
          created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          processed_at          TIMESTAMP(6) WITH TIME ZONE NULL,
          CONSTRAINT pk_org_refund_notify_outbox PRIMARY KEY (id_outbox),
          CONSTRAINT uq_refund_notify_dedupe UNIQUE (dedupe_key),
          CONSTRAINT chk_refund_notify_channel CHECK (channel IN ('FCM', 'WA')),
          CONSTRAINT chk_refund_notify_status CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED'))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_refund_notify_pending ON org_refund_notify_outbox (status, created_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- Archivar reclamos OPEN legacy. No recalcular strikes historicos.
UPDATE org_refund_claim
   SET claim_status = 'RESOLVED',
       resolved_at  = NVL(resolved_at, CURRENT_TIMESTAMP),
       notes        = SUBSTR(NVL(notes || ' | ', '') || 'ARCHIVED: refund dispute module 20260830', 1, 500)
 WHERE claim_status = 'OPEN';

COMMIT;

PROMPT === 20260830_refund_disputes DDL done ===
