-- Embeddings por organizacion para busqueda vectorial (cita rapida por voz, fase 1).
-- Requiere Oracle 23ai+ / Autonomous 26ai con tipo VECTOR.

PROMPT === 1) Tabla org_entity_embedding ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE org_entity_embedding (
            id_embedding        NUMBER GENERATED BY DEFAULT AS IDENTITY,
            org_id_organization NUMBER NOT NULL,
            entity_type         VARCHAR2(30) NOT NULL,
            entity_id           NUMBER NOT NULL,
            source_text         VARCHAR2(1000) NOT NULL,
            embedding           VECTOR(1536, FLOAT32) NOT NULL,
            updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_org_entity_embedding PRIMARY KEY (id_embedding),
            CONSTRAINT uq_org_entity_embedding UNIQUE (org_id_organization, entity_type, entity_id),
            CONSTRAINT fk_oee_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization),
            CONSTRAINT chk_oee_entity_type CHECK (
                entity_type IN ('CUSTOMER', 'PROFESSIONAL', 'SERVICE', 'LOCATION')
            )
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('org_entity_embedding creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('org_entity_embedding ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE INDEX idx_oee_org_type
            ON org_entity_embedding (org_id_organization, entity_type)
    ]';
    DBMS_OUTPUT.PUT_LINE('idx_oee_org_type creado.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('idx_oee_org_type ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT === 2) Indice vectorial (opcional si el tenant lo soporta) ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE VECTOR INDEX idx_oee_embedding_vec
            ON org_entity_embedding (embedding)
            ORGANIZATION NEIGHBOR PARTITIONS
            DISTANCE COSINE
            WITH TARGET ACCURACY 95
    ]';
    DBMS_OUTPUT.PUT_LINE('Indice vectorial creado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Indice vectorial omitido: ' || SQLERRM);
END;
/

PROMPT === 3) Parametros Azure OpenAI Embeddings ===

MERGE INTO app_parameter t
USING (
    SELECT
        'AZURE_OPENAI_EMBEDDING_DEPLOYMENT' AS param_key,
        'text-embedding-3-small' AS param_value,
        'Deployment de embeddings en Azure OpenAI (dimension 1536 por defecto).' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.param_value = s.param_value, t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

MERGE INTO app_parameter t
USING (
    SELECT
        'AZURE_OPENAI_EMBEDDING_API_VERSION' AS param_key,
        '2024-02-01' AS param_value,
        'Version API para embeddings Azure OpenAI.' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.param_value = s.param_value, t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

MERGE INTO app_parameter t
USING (
    SELECT
        'AZURE_OPENAI_EMBEDDING_DIMENSIONS' AS param_key,
        '1536' AS param_value,
        'Dimension del vector (debe coincidir con la columna embedding).' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.param_value = s.param_value, t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

COMMIT;

PROMPT === 4) Paquete PKG_AOX_VECTOR_SEARCH ===
@@../packages/PKG_AOX_VECTOR_SEARCH.pls

BEGIN
    DBMS_UTILITY.compile_schema(schema => USER, compile_all => FALSE);
END;
/

PROMPT Verificacion:
SELECT object_name, object_type, status
  FROM user_objects
 WHERE object_name = 'PKG_AOX_VECTOR_SEARCH'
 ORDER BY object_type;

SELECT line, position, text
  FROM user_errors
 WHERE name = 'PKG_AOX_VECTOR_SEARCH'
 ORDER BY type, sequence;

