-- Puente addon ↔ org_specialty. 0 filas = modulo global; N filas = nicho.
-- Seed: ODONTOGRAM_3D solo para org_specialty.code = DENTAL.

PROMPT === ref_addon_specialty ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'REF_ADDON_SPECIALTY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ref_addon_specialty (
              id_addon_specialty     NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              rad_id_addon           NUMBER                      NOT NULL,
              osp_id_org_specialty   NUMBER                      NOT NULL,
              created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT pk_ref_addon_specialty PRIMARY KEY (id_addon_specialty),
              CONSTRAINT uq_ref_addon_specialty UNIQUE (rad_id_addon, osp_id_org_specialty),
              CONSTRAINT fk_refaddonspec_addon FOREIGN KEY (rad_id_addon)
                REFERENCES ref_addon (id_addon) ON DELETE CASCADE,
              CONSTRAINT fk_refaddonspec_spec FOREIGN KEY (osp_id_org_specialty)
                REFERENCES org_specialty (id_org_specialty) ON DELETE CASCADE
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_refaddonspec_addon ON ref_addon_specialty (rad_id_addon)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_refaddonspec_spec ON ref_addon_specialty (osp_id_org_specialty)';
    END IF;
END;
/

COMMENT ON TABLE ref_addon_specialty IS 'Puente addon↔especialidad de org. 0 filas=global; N filas=nicho (ej. ODONTOGRAM_3D→DENTAL).';
COMMENT ON COLUMN ref_addon_specialty.rad_id_addon IS 'FK a ref_addon.id_addon.';
COMMENT ON COLUMN ref_addon_specialty.osp_id_org_specialty IS 'FK a org_specialty.id_org_specialty.';

PROMPT === seed org_specialty DENTAL ===
BEGIN
    UPDATE org_specialty
       SET code = 'DENTAL',
           is_active = 1
     WHERE code IS NULL
       AND LOWER(name) LIKE '%odont%';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

DECLARE
    v_exists NUMBER;
    v_next   NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM org_specialty WHERE code = 'DENTAL';
    IF v_exists = 0 THEN
        SELECT NVL(MAX(id_org_specialty), 0) + 1 INTO v_next FROM org_specialty;
        INSERT INTO org_specialty (id_org_specialty, name, code, description, is_active)
        VALUES (v_next, 'Odontología', 'DENTAL', 'Clínicas y consultorios odontológicos.', 1);
        EXECUTE IMMEDIATE
            'ALTER TABLE org_specialty MODIFY (id_org_specialty GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    END IF;
END;
/

PROMPT === seed ODONTOGRAM_3D → DENTAL ===
MERGE INTO ref_addon_specialty t
USING (
    SELECT ra.id_addon AS rad_id_addon,
           os.id_org_specialty AS osp_id_org_specialty
      FROM ref_addon ra
      JOIN org_specialty os
        ON os.code = 'DENTAL'
     WHERE ra.code = 'ODONTOGRAM_3D'
) s
ON (t.rad_id_addon = s.rad_id_addon AND t.osp_id_org_specialty = s.osp_id_org_specialty)
WHEN NOT MATCHED THEN
    INSERT (rad_id_addon, osp_id_org_specialty)
    VALUES (s.rad_id_addon, s.osp_id_org_specialty);

COMMIT;

PROMPT OK: ref_addon_specialty
