-- HAS-29 / HAS-32: catalogo de capabilities + defaults por rol + overrides org x rol.
-- Reversible: DROP TABLE org_role_capability / role_capability_default / capability
-- (en ese orden) y ORDS.DELETE_HANDLER de permissions/*.
--
-- Defaults = comportamiento real de staging (HAS-28):
--   * Recepcionista ve sucursales/servicios/especialidades pero NO las edita.
--   * Recepcionista SI crea/edita clientes y gestiona cobros/agenda/horarios.
--   * Profesional ve clientes propios; no crea ni edita.
--   * Addons clinicos ON para los 3 roles, gated por entitlement de org.
--   * permissions.manage siempre ON y locked para Admin.

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE capability (
  id_capability          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  code                   VARCHAR2(80) NOT NULL,
  group_code             VARCHAR2(40) NOT NULL,
  group_label            VARCHAR2(80) NOT NULL,
  label                  VARCHAR2(120) NOT NULL,
  description            VARCHAR2(400),
  kind                   VARCHAR2(20) DEFAULT 'ACTION' NOT NULL,
  sort_order             NUMBER DEFAULT 0 NOT NULL,
  requires_entitlement   VARCHAR2(80),
  is_locked              NUMBER(1,0) DEFAULT 0 NOT NULL,
  is_active              NUMBER(1,0) DEFAULT 1 NOT NULL,
  created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_capability PRIMARY KEY (id_capability),
  CONSTRAINT uq_capability_code UNIQUE (code),
  CONSTRAINT chk_capability_kind CHECK (kind IN ('MENU', 'ACTION', 'ADDON')),
  CONSTRAINT chk_capability_active CHECK (is_active IN (0, 1)),
  CONSTRAINT chk_capability_locked CHECK (is_locked IN (0, 1))
)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE role_capability_default (
  id_role_capability_default NUMBER GENERATED BY DEFAULT AS IDENTITY,
  rol_id_role                NUMBER NOT NULL,
  cap_id_capability          NUMBER NOT NULL,
  is_granted                 NUMBER(1,0) DEFAULT 1 NOT NULL,
  created_at                 TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_role_cap_default PRIMARY KEY (id_role_capability_default),
  CONSTRAINT uq_role_cap_default UNIQUE (rol_id_role, cap_id_capability),
  CONSTRAINT fk_rcd_role FOREIGN KEY (rol_id_role) REFERENCES role (id_role),
  CONSTRAINT fk_rcd_capability FOREIGN KEY (cap_id_capability) REFERENCES capability (id_capability),
  CONSTRAINT chk_rcd_granted CHECK (is_granted IN (0, 1))
)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE org_role_capability (
  id_org_role_capability NUMBER GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization    NUMBER NOT NULL,
  rol_id_role            NUMBER NOT NULL,
  cap_id_capability      NUMBER NOT NULL,
  is_granted             NUMBER(1,0) DEFAULT 1 NOT NULL,
  updated_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by             NUMBER,
  CONSTRAINT pk_org_role_capability PRIMARY KEY (id_org_role_capability),
  CONSTRAINT uq_org_role_capability UNIQUE (org_id_organization, rol_id_role, cap_id_capability),
  CONSTRAINT fk_orc_org FOREIGN KEY (org_id_organization) REFERENCES organization (id_organization),
  CONSTRAINT fk_orc_role FOREIGN KEY (rol_id_role) REFERENCES role (id_role),
  CONSTRAINT fk_orc_capability FOREIGN KEY (cap_id_capability) REFERENCES capability (id_capability),
  CONSTRAINT chk_orc_granted CHECK (is_granted IN (0, 1))
)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_orc_org_role ON org_role_capability (org_id_organization, rol_id_role)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

MERGE INTO capability t
USING (
    SELECT column_value AS src FROM TABLE(sys.odcivarchar2list(
        'dashboard.view|dashboard|Dashboard|Ver dashboard|Acceso al inicio del panel.|MENU|10|-|0',
        'calendar.view|calendar|Calendario|Ver calendario|Ver la agenda y el detalle de citas.|MENU|20|-|0',
        'calendar.manage|calendar|Calendario|Crear y editar citas|Alta, edicion y cancelacion de turnos.|ACTION|21|-|0',
        'customers.view|customers|Clientes|Ver clientes|Listar y abrir fichas. El profesional solo ve los suyos.|MENU|30|-|0',
        'customers.create|customers|Clientes|Crear clientes|Alta de clientes desde el panel.|ACTION|31|-|0',
        'customers.edit|customers|Clientes|Editar clientes|Modificar datos de contacto de un cliente.|ACTION|32|-|0',
        'customers.export|customers|Clientes|Exportar clientes|Descargar el listado en CSV.|ACTION|33|-|0',
        'cobros.view|cobros|Cobros|Ver cobros|Listado de senas y reembolsos.|MENU|40|-|0',
        'cobros.manage|cobros|Cobros|Gestionar cobros|Aprobar, rechazar o marcar reembolsos.|ACTION|41|-|0',
        'services.view|services|Servicios|Ver servicios|Consultar el catalogo de servicios.|MENU|50|-|0',
        'services.manage|services|Servicios|Crear y editar servicios|Alta, edicion y baja de servicios.|ACTION|51|-|0',
        'locations.view|locations|Sucursales|Ver sucursales|Entrar a Sucursales en solo lectura.|MENU|60|-|0',
        'locations.manage|locations|Sucursales|Crear y editar sucursales|CRUD de sucursales y cierres. Default solo Admin.|ACTION|61|-|0',
        'public_profile.manage|public_profile|Perfil publico|Editar perfil publico|Branding y pagina publica del negocio.|MENU|70|-|0',
        'addons.view|addons|Complementos|Ver complementos|Abrir la pagina de complementos contratables.|MENU|80|-|0',
        'addons.manage|addons|Complementos|Contratar complementos|Activar o cancelar addons de la organizacion.|ACTION|81|-|0',
        'addons.odontogram|addons|Complementos|Usar odontograma|Abrir y editar odontograma. Requiere complemento contratado.|ADDON|82|ODONTOGRAM_3D|0',
        'addons.body_map|addons|Complementos|Usar mapa corporal|Abrir y editar mapa corporal. Requiere complemento contratado.|ADDON|83|BODY_MAP|0',
        'specialties.view|specialties|Especialidades|Ver especialidades|Consultar especialidades del equipo.|MENU|90|-|0',
        'specialties.manage|specialties|Especialidades|Crear y editar especialidades|Alta y edicion de especialidades.|ACTION|91|-|0',
        'professionals.view|professionals|Personal|Ver personal|Listar profesionales e invitaciones.|MENU|100|-|0',
        'professionals.manage|professionals|Personal|Invitar y editar personal|Invitaciones, roles y visibilidad publica.|ACTION|101|-|0',
        'schedules.view|schedules|Horarios|Ver horarios|Consultar horarios y excepciones.|MENU|110|-|0',
        'schedules.manage|schedules|Horarios|Editar horarios del equipo|Crear y modificar horarios de otros profesionales.|ACTION|111|-|0',
        'ajustes.view|ajustes|Ajustes|Ver ajustes|Abrir Ajustes (perfil y seguridad propios).|MENU|120|-|0',
        'workspace.manage|ajustes|Ajustes|Configurar negocio|Apariencia, datos del negocio, pagos y sistema.|ACTION|121|-|0',
        'plan.view|plan|Plan|Ver plan|Ver el plan y la facturacion Hasel.|MENU|130|-|0',
        'plan.manage|plan|Plan|Cambiar plan y facturacion|Checkout, cambio de plan y medios de pago.|ACTION|131|-|0',
        'permissions.manage|permissions|Permisos|Configurar permisos|Editar la matriz de accesos por rol. Siempre activo para Admin.|ACTION|140|-|1'
    ))
) s
ON (t.code = REGEXP_SUBSTR(s.src, '[^|]+', 1, 1))
WHEN MATCHED THEN UPDATE SET
    t.group_code = REGEXP_SUBSTR(s.src, '[^|]+', 1, 2),
    t.group_label = REGEXP_SUBSTR(s.src, '[^|]+', 1, 3),
    t.label = REGEXP_SUBSTR(s.src, '[^|]+', 1, 4),
    t.description = REGEXP_SUBSTR(s.src, '[^|]+', 1, 5),
    t.kind = REGEXP_SUBSTR(s.src, '[^|]+', 1, 6),
    t.sort_order = TO_NUMBER(REGEXP_SUBSTR(s.src, '[^|]+', 1, 7)),
    t.requires_entitlement = NULLIF(REGEXP_SUBSTR(s.src, '[^|]+', 1, 8), '-'),
    t.is_locked = TO_NUMBER(REGEXP_SUBSTR(s.src, '[^|]+', 1, 9)),
    t.is_active = 1
WHEN NOT MATCHED THEN INSERT (
    code, group_code, group_label, label, description, kind, sort_order, requires_entitlement, is_locked, is_active
) VALUES (
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 1),
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 2),
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 3),
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 4),
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 5),
    REGEXP_SUBSTR(s.src, '[^|]+', 1, 6),
    TO_NUMBER(REGEXP_SUBSTR(s.src, '[^|]+', 1, 7)),
    NULLIF(REGEXP_SUBSTR(s.src, '[^|]+', 1, 8), '-'),
    TO_NUMBER(REGEXP_SUBSTR(s.src, '[^|]+', 1, 9)),
    1
);
COMMIT;

-- Defaults: Admin todos; Recepcionista y Profesional segun matriz HAS-28.
DECLARE
    v_admin NUMBER := pkg_aox_util.fn_rol('ADMIN');
    v_prof  NUMBER := pkg_aox_util.fn_rol('PROFESIONAL');
    v_recep NUMBER := pkg_aox_util.fn_rol('RECEPCIONISTA');

    PROCEDURE upsert_grant(pi_role_id NUMBER, pi_code VARCHAR2, pi_granted NUMBER) IS
        v_cap_id NUMBER;
    BEGIN
        SELECT id_capability INTO v_cap_id FROM capability WHERE code = pi_code;
        MERGE INTO role_capability_default t
        USING (SELECT pi_role_id AS role_id, v_cap_id AS cap_id FROM dual) s
        ON (t.rol_id_role = s.role_id AND t.cap_id_capability = s.cap_id)
        WHEN MATCHED THEN UPDATE SET t.is_granted = pi_granted
        WHEN NOT MATCHED THEN INSERT (rol_id_role, cap_id_capability, is_granted)
        VALUES (s.role_id, s.cap_id, pi_granted);
    END;
BEGIN
    FOR rec IN (SELECT code FROM capability WHERE is_active = 1) LOOP
        upsert_grant(v_admin, rec.code, 1);
        upsert_grant(v_recep, rec.code, 0);
        upsert_grant(v_prof, rec.code, 0);
    END LOOP;

    -- Recepcionista
    upsert_grant(v_recep, 'dashboard.view', 1);
    upsert_grant(v_recep, 'calendar.view', 1);
    upsert_grant(v_recep, 'calendar.manage', 1);
    upsert_grant(v_recep, 'customers.view', 1);
    upsert_grant(v_recep, 'customers.create', 1);
    upsert_grant(v_recep, 'customers.edit', 1);
    upsert_grant(v_recep, 'customers.export', 1);
    upsert_grant(v_recep, 'cobros.view', 1);
    upsert_grant(v_recep, 'cobros.manage', 1);
    upsert_grant(v_recep, 'services.view', 1);
    upsert_grant(v_recep, 'locations.view', 1);
    upsert_grant(v_recep, 'addons.odontogram', 1);
    upsert_grant(v_recep, 'addons.body_map', 1);
    upsert_grant(v_recep, 'specialties.view', 1);
    upsert_grant(v_recep, 'professionals.view', 1);
    upsert_grant(v_recep, 'professionals.manage', 1);
    upsert_grant(v_recep, 'schedules.view', 1);
    upsert_grant(v_recep, 'schedules.manage', 1);
    upsert_grant(v_recep, 'ajustes.view', 1);

    -- Profesional
    upsert_grant(v_prof, 'dashboard.view', 1);
    upsert_grant(v_prof, 'calendar.view', 1);
    upsert_grant(v_prof, 'calendar.manage', 1);
    upsert_grant(v_prof, 'customers.view', 1);
    upsert_grant(v_prof, 'customers.export', 1);
    upsert_grant(v_prof, 'services.view', 1);
    upsert_grant(v_prof, 'addons.odontogram', 1);
    upsert_grant(v_prof, 'addons.body_map', 1);
    upsert_grant(v_prof, 'schedules.view', 1);
    upsert_grant(v_prof, 'ajustes.view', 1);
END;
/
COMMIT;

-- ORDS: /api/v1/permissions/me|matrix|reset
BEGIN
    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'permissions/me');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'permissions/me',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_permission_api.pr_get_my_capabilities(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'permissions/matrix');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'permissions/matrix',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_permission_api.pr_get_matrix(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'permissions/matrix',
        p_method      => 'PUT',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_permission_api.pr_put_matrix(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_body          => :body_text,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'permissions/reset');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'permissions/reset',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_permission_api.pr_reset_matrix(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    COMMIT;
END;
/
