-- Complementos mensuales (catalogo + kill-switch). No cobra Pagopar.
-- Tablas: ref_addon, org_addon, customer_odontogram_event.
-- Tambien: org_specialty.code, invoice_type MODULE_ADDON, ADDONS_BILLING_LIVE=0.

PROMPT === org_specialty.code ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SPECIALTY'
       AND column_name = 'CODE';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE org_specialty ADD (code VARCHAR2(30) NULL)';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE org_specialty ADD CONSTRAINT uk_org_specialty_code UNIQUE (code)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2260, -2275) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        UPDATE org_specialty
           SET code = 'DENTAL'
         WHERE code IS NULL
           AND LOWER(name) LIKE '%odont%'
    ]';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

COMMENT ON COLUMN org_specialty.code IS 'Codigo estable de vertical (ej. DENTAL). Independiente del name editable.';

PROMPT === ref_addon ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'REF_ADDON';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ref_addon (
              id_addon           NUMBER         NOT NULL,
              code               VARCHAR2(30)   NOT NULL,
              name               VARCHAR2(100)  NOT NULL,
              short_description  VARCHAR2(400)  NULL,
              feature_code       VARCHAR2(50)   NOT NULL,
              price_amount       NUMBER         DEFAULT 0 NOT NULL,
              currency           VARCHAR2(3)    DEFAULT 'PYG' NOT NULL,
              billing_period     VARCHAR2(10)   DEFAULT 'MONTHLY' NOT NULL,
              is_active          NUMBER(1,0)    DEFAULT 1 NOT NULL,
              sort_order         NUMBER         DEFAULT 0 NOT NULL,
              audience_code      VARCHAR2(30)   NULL,
              CONSTRAINT pk_ref_addon PRIMARY KEY (id_addon),
              CONSTRAINT uq_ref_addon_code UNIQUE (code),
              CONSTRAINT uq_ref_addon_feature UNIQUE (feature_code),
              CONSTRAINT chk_ref_addon_active CHECK (is_active IN (0, 1)),
              CONSTRAINT chk_ref_addon_period CHECK (billing_period IN ('MONTHLY', 'YEARLY'))
            )
        ]';
    END IF;
END;
/

PROMPT === org_addon ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'ORG_ADDON';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE org_addon (
              id_org_addon           NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization    NUMBER                      NOT NULL,
              rad_id_addon           NUMBER                      NOT NULL,
              status                 VARCHAR2(20)                DEFAULT 'ACTIVE' NOT NULL,
              grant_type             VARCHAR2(20)                DEFAULT 'PREVIEW' NOT NULL,
              price_snapshot_amount  NUMBER                      DEFAULT 0 NOT NULL,
              currency               VARCHAR2(3)                 DEFAULT 'PYG' NOT NULL,
              started_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              canceled_at            TIMESTAMP(6) WITH TIME ZONE NULL,
              billing_started_at     TIMESTAMP(6) WITH TIME ZONE NULL,
              created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              updated_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT pk_org_addon PRIMARY KEY (id_org_addon),
              CONSTRAINT uq_org_addon_org_addon UNIQUE (org_id_organization, rad_id_addon),
              CONSTRAINT chk_orgaddon_status CHECK (status IN ('ACTIVE', 'CANCELED', 'EXPIRED')),
              CONSTRAINT chk_orgaddon_grant CHECK (grant_type IN ('PREVIEW', 'PAID')),
              CONSTRAINT fk_orgaddon_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization) ON DELETE CASCADE,
              CONSTRAINT fk_orgaddon_addon FOREIGN KEY (rad_id_addon)
                REFERENCES ref_addon (id_addon)
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_orgaddon_org ON org_addon (org_id_organization)';
    END IF;
END;
/

PROMPT === customer_odontogram_event ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'CUSTOMER_ODONTOGRAM_EVENT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE customer_odontogram_event (
              id_event            NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization NUMBER                      NOT NULL,
              cus_id_customer     NUMBER                      NOT NULL,
              tooth_fdi           NUMBER(2,0)                 NOT NULL,
              face_occlusal       NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              face_vestibular     NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              face_palatal        NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              face_mesial         NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              face_distal         NUMBER(1,0)                 DEFAULT 0 NOT NULL,
              finding_code        VARCHAR2(20)                NOT NULL,
              notes               VARCHAR2(2000)              NULL,
              created_by_user     NUMBER                      NULL,
              created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT pk_customer_odontogram_event PRIMARY KEY (id_event),
              CONSTRAINT chk_odoevt_tooth CHECK (
                TRUNC(tooth_fdi / 10) IN (1, 2, 3, 4)
                AND MOD(tooth_fdi, 10) BETWEEN 1 AND 8
              ),
              CONSTRAINT chk_odoevt_finding CHECK (
                finding_code IN ('CARIES', 'RESTORATION', 'EXTRACTION', 'CROWN')
              ),
              CONSTRAINT chk_odoevt_faces CHECK (
                face_occlusal IN (0, 1)
                AND face_vestibular IN (0, 1)
                AND face_palatal IN (0, 1)
                AND face_mesial IN (0, 1)
                AND face_distal IN (0, 1)
              ),
              CONSTRAINT fk_odoevt_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization) ON DELETE CASCADE,
              CONSTRAINT fk_odoevt_customer FOREIGN KEY (cus_id_customer)
                REFERENCES customer (id_customer) ON DELETE CASCADE
            )
        ]';
        EXECUTE IMMEDIATE
            'CREATE INDEX idx_odoevt_org_cus ON customer_odontogram_event (org_id_organization, cus_id_customer, created_at)';
    END IF;
END;
/

PROMPT === org_subscription_invoice.rad_id_addon + invoice_type MODULE_ADDON ===
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'ORG_SUBSCRIPTION_INVOICE'
       AND column_name = 'RAD_ID_ADDON';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE org_subscription_invoice ADD (rad_id_addon NUMBER NULL)';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_module_addon
         FOREIGN KEY (rad_id_addon) REFERENCES ref_addon (id_addon)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2260) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE org_subscription_invoice DROP CONSTRAINT chk_orginv_type';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443, -23292) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_type CHECK (
            invoice_type IN ('SUBSCRIPTION', 'STORAGE_ADDON', 'MODULE_ADDON')
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2260, -2275) THEN
            RAISE;
        END IF;
END;
/

PROMPT === seed ADDONS_BILLING_LIVE + ODONTOGRAM_3D ===
MERGE INTO app_parameter t
USING (
    SELECT 'ADDONS_BILLING_LIVE' AS param_key,
           '0' AS param_value,
           '1=cobrar complementos (Pagopar). 0=activar PREVIEW sin cobro. Default 0.' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

MERGE INTO ref_addon t
USING (
    SELECT 1 AS id_addon,
           'ODONTOGRAM_3D' AS code,
           'Odontograma 3D' AS name,
           'Ficha clinica interactiva 3D y evolucion de tratamientos.' AS short_description,
           'ODONTOGRAM_3D' AS feature_code,
           100000 AS price_amount,
           'PYG' AS currency,
           'MONTHLY' AS billing_period,
           1 AS is_active,
           1 AS sort_order,
           'DENTAL' AS audience_code
      FROM dual
) s
ON (t.id_addon = s.id_addon)
WHEN MATCHED THEN
    UPDATE SET
        t.code = s.code,
        t.name = s.name,
        t.short_description = s.short_description,
        t.feature_code = s.feature_code,
        t.price_amount = s.price_amount,
        t.currency = s.currency,
        t.billing_period = s.billing_period,
        t.is_active = s.is_active,
        t.sort_order = s.sort_order,
        t.audience_code = s.audience_code
WHEN NOT MATCHED THEN
    INSERT (
        id_addon, code, name, short_description, feature_code,
        price_amount, currency, billing_period, is_active, sort_order, audience_code
    ) VALUES (
        s.id_addon, s.code, s.name, s.short_description, s.feature_code,
        s.price_amount, s.currency, s.billing_period, s.is_active, s.sort_order, s.audience_code
    );

COMMIT;

PROMPT OK: module addons catalog
