-- HAS-22: series semanales de citas (v1, sin RRULE).
-- Crea appointment_series y el FK opcional appointment.srs_id_series.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE appointment_series (
      id_series           NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
      org_id_organization NUMBER                      NOT NULL,
      loc_id_location     NUMBER                      NOT NULL,
      pro_id_professional NUMBER                      NOT NULL,
      ser_id_service      NUMBER                      NOT NULL,
      cus_id_customer     NUMBER                      NULL,
      frequency           VARCHAR2(20)                DEFAULT 'WEEKLY' NOT NULL,
      occurrence_count    NUMBER                      NOT NULL,
      first_start_time    TIMESTAMP(6)                NOT NULL,
      until_date          DATE                        NULL,
      created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_by          NUMBER                      NULL,
      CONSTRAINT pk_appointment_series PRIMARY KEY (id_series),
      CONSTRAINT chk_series_frequency CHECK (frequency IN ('WEEKLY')),
      CONSTRAINT chk_series_count CHECK (occurrence_count BETWEEN 1 AND 52)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment_series
      ADD CONSTRAINT fk_series_organization FOREIGN KEY (org_id_organization)
      REFERENCES organization (id_organization) ON DELETE CASCADE
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment_series
      ADD CONSTRAINT fk_series_location FOREIGN KEY (loc_id_location)
      REFERENCES location (id_location)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment_series
      ADD CONSTRAINT fk_series_professional FOREIGN KEY (pro_id_professional)
      REFERENCES professional (id_professional)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment_series
      ADD CONSTRAINT fk_series_service FOREIGN KEY (ser_id_service)
      REFERENCES service (id_service)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment_series
      ADD CONSTRAINT fk_series_customer FOREIGN KEY (cus_id_customer)
      REFERENCES customer (id_customer)
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_series_org ON appointment_series (org_id_organization)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE appointment ADD (srs_id_series NUMBER NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE appointment
      ADD CONSTRAINT fk_app_series FOREIGN KEY (srs_id_series)
      REFERENCES appointment_series (id_series)
      ON DELETE SET NULL
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_app_series ON appointment (srs_id_series)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE appointment_series IS
  'Serie semanal de citas (v1: cada 7 dias). Cada cita hija apunta con appointment.srs_id_series.';

COMMENT ON COLUMN appointment_series.frequency IS
  'Frecuencia de la serie. v1 solo WEEKLY.';

COMMENT ON COLUMN appointment_series.occurrence_count IS
  'Cantidad de citas generadas al crear la serie (1-52).';

COMMENT ON COLUMN appointment_series.first_start_time IS
  'Inicio de la primera ocurrencia (hora local de agenda, sin TZ).';

COMMENT ON COLUMN appointment_series.until_date IS
  'Fecha limite inclusiva si la serie se pidio por fecha de fin.';

COMMENT ON COLUMN appointment.srs_id_series IS
  'Serie semanal a la que pertenece la cita (HAS-22). NULL = cita suelta.';
/
