-- El import a aoxdevelop dejó las PK identity como NUMBER NOT NULL sin
-- secuencia y se perdió DEFAULT en flags/timestamps. Oracle no permite
-- CONVERTIR una columna existente a IDENTITY (ORA-30673), así que se
-- recrea el equivalente: SEQUENCE + DEFAULT ON NULL seq.NEXTVAL.
-- START WITH = MAX(col)+1 para no chocar con filas importadas.

PROMPT === 20260911_restore_identity_columns ===

DECLARE
    v_ok_seq   PLS_INTEGER := 0;
    v_ok_def   PLS_INTEGER := 0;
    v_skip     PLS_INTEGER := 0;
    v_fail     PLS_INTEGER := 0;
    v_errors   CLOB := EMPTY_CLOB();
    v_exists   PLS_INTEGER;
    v_next     NUMBER;

    PROCEDURE note_fail(pi_what VARCHAR2) IS
    BEGIN
        v_fail := v_fail + 1;
        v_errors := v_errors || pi_what || CHR(10);
    END;

    PROCEDURE restore_seq(pi_table VARCHAR2, pi_column VARCHAR2, pi_seq VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = UPPER(pi_table);
        IF v_exists = 0 THEN v_skip := v_skip + 1; RETURN; END IF;

        SELECT COUNT(*) INTO v_exists FROM user_sequences WHERE sequence_name = UPPER(pi_seq);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'SELECT NVL(MAX(' || pi_column || '),0)+1 FROM ' || pi_table INTO v_next;
            EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || pi_seq || ' START WITH ' || v_next || ' CACHE 20';
        END IF;

        EXECUTE IMMEDIATE 'ALTER TABLE ' || pi_table || ' MODIFY (' || pi_column
            || ' DEFAULT ON NULL ' || pi_seq || '.NEXTVAL)';
        v_ok_seq := v_ok_seq + 1;
    EXCEPTION
        WHEN OTHERS THEN note_fail(pi_table || '.' || pi_column || ' SEQ: ' || SQLERRM);
    END;

    PROCEDURE restore_def(pi_table VARCHAR2, pi_column VARCHAR2, pi_default VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM user_tab_columns
         WHERE table_name = UPPER(pi_table) AND column_name = UPPER(pi_column);
        IF v_exists = 0 THEN v_skip := v_skip + 1; RETURN; END IF;
        EXECUTE IMMEDIATE 'ALTER TABLE ' || pi_table || ' MODIFY (' || pi_column
            || ' DEFAULT ' || pi_default || ')';
        v_ok_def := v_ok_def + 1;
    EXCEPTION
        WHEN OTHERS THEN note_fail(pi_table || '.' || pi_column || ' DEF: ' || SQLERRM);
    END;
BEGIN
    restore_seq('ai_chat_message', 'id_message', 'seq_ai_chat_message');
    restore_seq('ai_chat_session', 'id_session', 'seq_ai_chat_session');
    restore_seq('aox_ai_log', 'id_log', 'seq_aox_ai_log');
    restore_seq('aox_api_log', 'id_log', 'seq_aox_api_log');
    restore_seq('aox_fcm_log', 'id_log', 'seq_aox_fcm_log');
    restore_seq('aox_log_webhook_meta', 'id_log', 'seq_aox_log_webhook_meta');
    restore_seq('aox_push_fcm_log', 'id_log', 'seq_aox_push_fcm_log');
    restore_seq('aox_whatsapp_template_log', 'id_log', 'seq_aox_whatsapp_template_log');
    restore_seq('appointment', 'id_appointment', 'seq_appointment');
    restore_seq('appointment_attachment', 'id_attachment', 'seq_appointment_attachment');
    restore_seq('appointment_session_record', 'id_session_record', 'seq_appointment_session_record');
    restore_seq('app_parameter', 'id_parameter', 'seq_app_parameter');
    restore_seq('app_user_email_verification', 'id_verification', 'seq_app_user_email_verification');
    restore_seq('app_user_pwd_reset', 'id_reset', 'seq_app_user_pwd_reset');
    restore_seq('app_user_session', 'id_session', 'seq_app_user_session');
    restore_seq('atc_kb_chunk', 'id_chunk', 'seq_atc_kb_chunk');
    restore_seq('atc_kb_document', 'id_document', 'seq_atc_kb_document');
    restore_seq('cities', 'id_city', 'seq_cities');
    restore_seq('customer', 'id_customer', 'seq_customer');
    restore_seq('customer_body_snapshot', 'id_body_snapshot', 'seq_customer_body_snapshot');
    restore_seq('customer_odontogram_event', 'id_event', 'seq_customer_odontogram_event');
    restore_seq('customer_phone_audit', 'id_audit', 'seq_customer_phone_audit');
    restore_seq('departments', 'id_department', 'seq_departments');
    restore_seq('embedding_sync_outbox', 'id_outbox', 'seq_embedding_sync_outbox');
    restore_seq('location', 'id_location', 'seq_location');
    restore_seq('location_closure', 'id_location_closure', 'seq_location_closure');
    restore_seq('organization', 'id_organization', 'seq_organization');
    restore_seq('org_addon', 'id_org_addon', 'seq_org_addon');
    restore_seq('org_billing_credit_ledger', 'id_credit_ledger', 'seq_org_billing_credit_ledger');
    restore_seq('org_billing_profile', 'id_billing_profile', 'seq_org_billing_profile');
    restore_seq('org_entity_embedding', 'id_embedding', 'seq_org_entity_embedding');
    restore_seq('org_gallery_image', 'id_gallery_image', 'seq_org_gallery_image');
    restore_seq('org_integration', 'id_integration', 'seq_org_integration');
    restore_seq('org_invitation', 'id_org_invitation', 'seq_org_invitation');
    restore_seq('org_member', 'id_org_member', 'seq_org_member');
    restore_seq('org_payment_card', 'id_payment_card', 'seq_org_payment_card');
    restore_seq('org_payment_settings', 'id_payment_settings', 'seq_org_payment_settings');
    restore_seq('org_refund_claim', 'id_claim', 'seq_org_refund_claim');
    restore_seq('org_refund_dispute', 'id_dispute', 'seq_org_refund_dispute');
    restore_seq('org_refund_dispute_compensation', 'id_compensation', 'seq_org_refund_dispute_compensation');
    restore_seq('org_refund_dispute_evidence', 'id_evidence', 'seq_org_refund_dispute_evidence');
    restore_seq('org_refund_dispute_ledger', 'id_ledger_entry', 'seq_org_refund_dispute_ledger');
    restore_seq('org_refund_enforcement_audit', 'id_enforcement_audit', 'seq_org_refund_enforcement_audit');
    restore_seq('org_refund_notify_outbox', 'id_outbox', 'seq_org_refund_notify_outbox');
    restore_seq('org_refund_strike', 'id_strike', 'seq_org_refund_strike');
    restore_seq('org_specialty', 'id_org_specialty', 'seq_org_specialty');
    restore_seq('org_storage_addon', 'id_org_storage_addon', 'seq_org_storage_addon');
    restore_seq('org_subscription', 'id_subscription', 'seq_org_subscription');
    restore_seq('org_subscription_invoice', 'id_invoice', 'seq_org_subscription_invoice');
    restore_seq('payment_transaction', 'id_transaction', 'seq_payment_transaction');
    restore_seq('platform_user', 'id_platform_user', 'seq_platform_user');
    restore_seq('professional', 'id_professional', 'seq_professional');
    restore_seq('professional_image', 'id_image', 'seq_professional_image');
    restore_seq('professional_schedule', 'id_professional_schedule', 'seq_professional_schedule');
    restore_seq('professional_schedule_exception', 'id_schedule_exception', 'seq_professional_schedule_exception');
    restore_seq('professional_schedule_exception_slot', 'id_exception_slot', 'seq_professional_schedule_exception_slot');
    restore_seq('push_campaign', 'id_campaign', 'seq_push_campaign');
    restore_seq('push_campaign_delivery', 'id_delivery', 'seq_push_campaign_delivery');
    restore_seq('push_campaign_var', 'id_campaign_var', 'seq_push_campaign_var');
    restore_seq('push_var_catalog', 'id_var_catalog', 'seq_push_var_catalog');
    restore_seq('ref_addon_specialty', 'id_addon_specialty', 'seq_ref_addon_specialty');
    restore_seq('ref_booking_slot_interval', 'id_slot_interval', 'seq_ref_booking_slot_interval');
    restore_seq('ref_cancel_wait_hours', 'id_cancel_wait_hours', 'seq_ref_cancel_wait_hours');
    restore_seq('ref_holiday', 'id_holiday', 'seq_ref_holiday');
    restore_seq('ref_plan_feature', 'id_plan_feature', 'seq_ref_plan_feature');
    restore_seq('ref_reminder_hours', 'id_reminder_hours', 'seq_ref_reminder_hours');
    restore_seq('role', 'id_role', 'seq_role');
    restore_seq('service', 'id_service', 'seq_service');
    restore_seq('specialty', 'id_specialty', 'seq_specialty');
    restore_seq('subscription_credit_note', 'id_credit_note', 'seq_subscription_credit_note');
    restore_seq('subscription_einvoice_outbox', 'id_outbox', 'seq_subscription_einvoice_outbox');
    restore_seq('subscription_einvoice_webhook_log', 'id_webhook_log', 'seq_subscription_einvoice_webhook_log');
    restore_seq('professional_service', 'id_pro_service', 'seq_professional_service');
    restore_seq('user_fcm_devices', 'device_id', 'seq_user_fcm_devices');
    restore_seq('user_integration', 'id_integration', 'seq_user_integration');
    restore_seq('user_notification', 'id_notification', 'seq_user_notification');
    restore_seq('workspace_setting', 'id_setting', 'seq_workspace_setting');
    restore_def('ai_chat_message', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('ai_chat_session', 'title', '''Nuevo Chat''');
    restore_def('ai_chat_session', 'is_active', '1');
    restore_def('ai_chat_session', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('ai_chat_session', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('aox_ai_log', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('aox_api_log', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('aox_fcm_log', 'log_date', 'CURRENT_TIMESTAMP');
    restore_def('aox_log_webhook_meta', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('aox_push_fcm_log', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('aox_whatsapp_template_log', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('api_idempotency_key', 'status', '''IN_PROGRESS''');
    restore_def('api_idempotency_key', 'created_at', 'SYSTIMESTAMP');
    restore_def('api_rate_limit_bucket', 'attempt_count', '1');
    restore_def('api_rate_limit_bucket', 'window_started_at', 'SYSTIMESTAMP');
    restore_def('api_rate_limit_bucket', 'updated_at', 'SYSTIMESTAMP');
    restore_def('appointment', 'status', '''CONFIRMADO''');
    restore_def('appointment', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('appointment', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('appointment', 'attendance_status', '''NOT_REQUESTED''');
    restore_def('appointment', 'refund_status', '''NONE''');
    restore_def('appointment', 'schedule_exception_approved', '0');
    restore_def('appointment', 'survey_status', '''NONE''');
    restore_def('appointment_attachment', 'size_bytes', '0');
    restore_def('appointment_attachment', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('appointment_session_record', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('appointment_session_record', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('app_parameter', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('app_user_email_verification', 'attempt_count', '0');
    restore_def('app_user_email_verification', 'max_attempts', '5');
    restore_def('app_user_email_verification', 'sent_at', 'CURRENT_TIMESTAMP');
    restore_def('app_user_email_verification', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('app_user_pwd_reset', 'is_used', '0');
    restore_def('app_user_pwd_reset', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('app_user_session', 'is_revoked', '0');
    restore_def('app_user_session', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('atc_kb_chunk', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('atc_kb_document', 'size_bytes', '0');
    restore_def('atc_kb_document', 'status', '''PENDING''');
    restore_def('atc_kb_document', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('atc_kb_document', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('customer', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('customer_body_snapshot', 'silhouette', '''NEUTRAL''');
    restore_def('customer_body_snapshot', 'captured_at', 'CURRENT_TIMESTAMP');
    restore_def('customer_body_snapshot', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('customer_body_snapshot', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('customer_odontogram_event', 'face_occlusal', '0');
    restore_def('customer_odontogram_event', 'face_vestibular', '0');
    restore_def('customer_odontogram_event', 'face_palatal', '0');
    restore_def('customer_odontogram_event', 'face_mesial', '0');
    restore_def('customer_odontogram_event', 'face_distal', '0');
    restore_def('customer_odontogram_event', 'clinical_phase', '''FINDING''');
    restore_def('customer_odontogram_event', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('customer_phone_audit', 'audited_at', 'CURRENT_TIMESTAMP');
    restore_def('embedding_sync_outbox', 'status', '''PENDING''');
    restore_def('embedding_sync_outbox', 'attempts', '0');
    restore_def('embedding_sync_outbox', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('location', 'is_active', '1');
    restore_def('location', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('location_closure', 'is_full_day', '1');
    restore_def('location_closure', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('organization', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('organization', 'country_code', '''PY''');
    restore_def('organization_specialty', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_addon', 'status', '''ACTIVE''');
    restore_def('org_addon', 'grant_type', '''PREVIEW''');
    restore_def('org_addon', 'price_snapshot_amount', '0');
    restore_def('org_addon', 'currency', '''PYG''');
    restore_def('org_addon', 'started_at', 'CURRENT_TIMESTAMP');
    restore_def('org_addon', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_addon', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_billing_credit_ledger', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_billing_profile', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_billing_profile', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_entity_embedding', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_gallery_image', 'size_bytes', '0');
    restore_def('org_gallery_image', 'sort_order', '1');
    restore_def('org_gallery_image', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_integration', 'is_active', '1');
    restore_def('org_integration', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_integration', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_invitation', 'status', '''PENDING''');
    restore_def('org_invitation', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_member', 'is_active', '1');
    restore_def('org_member', 'notify_all_professionals', '''N''');
    restore_def('org_member', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_payment_card', 'provider', '''uPay''');
    restore_def('org_payment_card', 'status', '''PENDING''');
    restore_def('org_payment_card', 'is_default', '0');
    restore_def('org_payment_card', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_payment_card', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_payment_settings', 'deposits_enabled', '0');
    restore_def('org_payment_settings', 'refund_strike_count', '0');
    restore_def('org_payment_settings', 'deposits_suspended', '0');
    restore_def('org_payment_settings', 'refund_enforcement_level', '''NONE''');
    restore_def('org_payment_settings', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_payment_settings', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_claim', 'claim_status', '''OPEN''');
    restore_def('org_refund_claim', 'strike_counted', '1');
    restore_def('org_refund_claim', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute', 'dispute_status', '''OPENED''');
    restore_def('org_refund_dispute', 'opened_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute_compensation', 'credit_status', '''PENDING''');
    restore_def('org_refund_dispute_compensation', 'debt_status', '''NONE''');
    restore_def('org_refund_dispute_compensation', 'recovered_amount_gs', '0');
    restore_def('org_refund_dispute_compensation', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute_compensation', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute_evidence', 'size_bytes', '0');
    restore_def('org_refund_dispute_evidence', 'uploaded_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_dispute_evidence', 'ocr_status', '''PROCESSING''');
    restore_def('org_refund_dispute_evidence', 'extractor_version', '''refund_proof_v1''');
    restore_def('org_refund_dispute_ledger', 'delta_due', '0');
    restore_def('org_refund_dispute_ledger', 'balance_due_after', '0');
    restore_def('org_refund_dispute_ledger', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_enforcement_audit', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_notify_outbox', 'channel', '''FCM''');
    restore_def('org_refund_notify_outbox', 'status', '''PENDING''');
    restore_def('org_refund_notify_outbox', 'attempts', '0');
    restore_def('org_refund_notify_outbox', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_refund_strike', 'reason', '''TIMEOUT''');
    restore_def('org_refund_strike', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_specialty', 'is_active', '1');
    restore_def('org_specialty', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_storage_addon', 'quantity', '1');
    restore_def('org_storage_addon', 'status', '''ACTIVE''');
    restore_def('org_storage_addon', 'started_at', 'CURRENT_TIMESTAMP');
    restore_def('org_storage_addon', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_subscription', 'is_founder', '0');
    restore_def('org_subscription', 'billing_exempt', '0');
    restore_def('org_subscription', 'storage_used_bytes', '0');
    restore_def('org_subscription', 'storage_limit_bytes', '0');
    restore_def('org_subscription', 'auto_renew', '1');
    restore_def('org_subscription', 'charge_retry_count', '0');
    restore_def('org_subscription', 'account_balance', '0');
    restore_def('org_subscription', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_subscription', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('org_subscription_invoice', 'invoice_type', '''SUBSCRIPTION''');
    restore_def('org_subscription_invoice', 'credit_applied', '0');
    restore_def('org_subscription_invoice', 'currency', '''PYG''');
    restore_def('org_subscription_invoice', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('org_subscription_invoice', 'einvoice_status', '''NONE''');
    restore_def('org_subscription_invoice', 'einvoice_email_status', '''NONE''');
    restore_def('org_subscription_invoice', 'einvoice_email_attempts', '0');
    restore_def('payment_transaction', 'provider', '''sipap''');
    restore_def('payment_transaction', 'currency', '''PYG''');
    restore_def('payment_transaction', 'payment_channel', '''TRANSFER''');
    restore_def('payment_transaction', 'receipt_size_bytes', '0');
    restore_def('payment_transaction', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('platform_user', 'is_active', '1');
    restore_def('platform_user', 'failed_login_attempts', '0');
    restore_def('platform_user', 'password_algo', '''SHA256_LEGACY''');
    restore_def('platform_user', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('professional', 'profile_image_size_bytes', '0');
    restore_def('professional', 'is_active', '1');
    restore_def('professional', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_image', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_schedule', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_schedule_exception', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_schedule_exception', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_schedule_exception_slot', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('push_campaign', 'status', '''DRAFT''');
    restore_def('push_campaign', 'is_enabled', '1');
    restore_def('push_campaign', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('push_campaign', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('push_campaign_delivery', 'status', '''PENDING''');
    restore_def('push_campaign_delivery', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('push_var_catalog', 'is_active', '1');
    restore_def('push_var_catalog', 'sort_order', '0');
    restore_def('ref_addon', 'price_amount', '0');
    restore_def('ref_addon', 'currency', '''PYG''');
    restore_def('ref_addon', 'billing_period', '''MONTHLY''');
    restore_def('ref_addon', 'is_active', '1');
    restore_def('ref_addon', 'sort_order', '0');
    restore_def('ref_addon', 'requires_specialty_bridge', '0');
    restore_def('ref_addon_specialty', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('ref_body_joint_test', 'sort_order', '0');
    restore_def('ref_body_joint_test', 'is_active', '1');
    restore_def('ref_body_region', 'sort_order', '0');
    restore_def('ref_body_region', 'is_active', '1');
    restore_def('ref_booking_slot_interval', 'sort_order', '0');
    restore_def('ref_booking_slot_interval', 'is_active', '1');
    restore_def('ref_cancel_wait_hours', 'sort_order', '0');
    restore_def('ref_cancel_wait_hours', 'is_active', '1');
    restore_def('ref_holiday', 'is_active', '1');
    restore_def('ref_odontogram_finding', 'needs_faces', '0');
    restore_def('ref_odontogram_finding', 'priority_rank', '50');
    restore_def('ref_odontogram_finding', 'visual_kind', '''TINT''');
    restore_def('ref_odontogram_finding', 'is_active', '1');
    restore_def('ref_odontogram_finding', 'sort_order', '0');
    restore_def('ref_pagopar_forma_pago', 'is_enabled_web', '1');
    restore_def('ref_pagopar_forma_pago', 'sort_order', '0');
    restore_def('ref_plan', 'price_amount', '0');
    restore_def('ref_plan', 'currency', '''PYG''');
    restore_def('ref_plan', 'billing_period', '''MONTHLY''');
    restore_def('ref_plan', 'storage_limit_bytes', '0');
    restore_def('ref_plan', 'is_active', '1');
    restore_def('ref_plan', 'sort_order', '0');
    restore_def('ref_plan_feature', 'is_enabled', '1');
    restore_def('ref_reminder_hours', 'sort_order', '0');
    restore_def('ref_reminder_hours', 'is_active', '1');
    restore_def('ref_sipap_bank', 'is_active', '1');
    restore_def('ref_sipap_bank', 'sort_order', '0');
    restore_def('ref_storage_addon', 'price_amount', '0');
    restore_def('ref_storage_addon', 'currency', '''PYG''');
    restore_def('ref_storage_addon', 'billing_period', '''MONTHLY''');
    restore_def('ref_storage_addon', 'is_active', '1');
    restore_def('ref_storage_addon', 'sort_order', '0');
    restore_def('role', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('role', 'is_active', '1');
    restore_def('service', 'hide_public_price', '0');
    restore_def('service', 'image_size_bytes', '0');
    restore_def('service', 'is_active', '1');
    restore_def('service', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('specialty', 'is_active', '1');
    restore_def('specialty', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('subscription_credit_note', 'motivo', '2');
    restore_def('subscription_credit_note', 'status', '''PENDING''');
    restore_def('subscription_credit_note', 'attempts', '0');
    restore_def('subscription_credit_note', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('subscription_einvoice_outbox', 'status', '''PENDING''');
    restore_def('subscription_einvoice_outbox', 'attempts', '0');
    restore_def('subscription_einvoice_outbox', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('subscription_einvoice_webhook_log', 'received_at', 'CURRENT_TIMESTAMP');
    restore_def('subscription_einvoice_webhook_log', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('professional_service', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('user_fcm_devices', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('user_fcm_devices', 'last_used_at', 'CURRENT_TIMESTAMP');
    restore_def('user_integration', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('user_integration', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('user_notification', 'action_type', '''OPEN_URL''');
    restore_def('user_notification', 'created_at', 'CURRENT_TIMESTAMP');
    restore_def('workspace_setting', 'logo_size_bytes', '0');
    restore_def('workspace_setting', 'banner_size_bytes', '0');
    restore_def('workspace_setting', 'time_format', '''24H''');
    restore_def('workspace_setting', 'theme_pref', '''light''');
    restore_def('workspace_setting', 'hidden_public_price_label', '''A evaluar''');
    restore_def('workspace_setting', 'updated_at', 'CURRENT_TIMESTAMP');
    restore_def('workspace_setting', 'unanswered_alert_action', '''KEEP''');
    restore_def('workspace_setting', 'survey_auto_enabled', '0');
    -- Defaults que viven en migraciones (no en tables/*.sql)
    restore_def('appointment', 'payment_status', '''NONE''');
    restore_def('service', 'requires_deposit', '0');
    DBMS_OUTPUT.PUT_LINE('seq=' || v_ok_seq || ' def=' || v_ok_def || ' skip=' || v_skip || ' fail=' || v_fail);
    IF v_fail > 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Fallaron ' || v_fail || ' ajustes:' || CHR(10) || v_errors);
    END IF;
END;
/

PROMPT === 20260911_restore_identity_columns done ===
