-- KB global ATC: documentos en OCI bucket + chunks con embeddings (1536-d).

PROMPT === 1) Tabla atc_kb_document ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE atc_kb_document (
            id_document    NUMBER GENERATED BY DEFAULT AS IDENTITY,
            file_name      VARCHAR2(255) NOT NULL,
            mime_type      VARCHAR2(150) NOT NULL,
            size_bytes     NUMBER DEFAULT 0 NOT NULL,
            storage_url    VARCHAR2(1000) NOT NULL,
            object_key     VARCHAR2(500) NOT NULL,
            extracted_text CLOB,
            status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
            error_message  VARCHAR2(4000),
            created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_atc_kb_document PRIMARY KEY (id_document),
            CONSTRAINT chk_atc_kb_doc_status CHECK (
                status IN ('PENDING', 'PROCESSING', 'READY', 'ERROR')
            ),
            CONSTRAINT chk_atc_kb_doc_size CHECK (size_bytes >= 0)
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('atc_kb_document creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('atc_kb_document ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[CREATE INDEX idx_atc_kb_doc_status ON atc_kb_document (status)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === 2) Tabla atc_kb_chunk ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE atc_kb_chunk (
            id_chunk        NUMBER GENERATED BY DEFAULT AS IDENTITY,
            doc_id_document NUMBER NOT NULL,
            chunk_index     NUMBER NOT NULL,
            chunk_text      CLOB NOT NULL,
            embedding       VECTOR(1536, FLOAT32) NOT NULL,
            updated_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_atc_kb_chunk PRIMARY KEY (id_chunk),
            CONSTRAINT fk_atc_kb_chunk_doc FOREIGN KEY (doc_id_document)
                REFERENCES atc_kb_document (id_document) ON DELETE CASCADE,
            CONSTRAINT uq_atc_kb_chunk_doc_idx UNIQUE (doc_id_document, chunk_index)
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('atc_kb_chunk creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('atc_kb_chunk ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[CREATE INDEX idx_atc_kb_chunk_doc ON atc_kb_chunk (doc_id_document)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT === 3) Indice vectorial ===

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE VECTOR INDEX idx_atc_kb_chunk_vec
            ON atc_kb_chunk (embedding)
            ORGANIZATION NEIGHBOR PARTITIONS
            DISTANCE COSINE
            WITH TARGET ACCURACY 95
    ]';
    DBMS_OUTPUT.PUT_LINE('Indice vectorial ATC creado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Indice vectorial ATC omitido: ' || SQLERRM);
END;
/

COMMIT;
/