-- NCE al cancelar addon de storage con FE previa (MVP mid-cycle STORAGE_ADDON).
-- Tabla subscription_credit_note + snapshot receptor FE + ORDS callback NCE.
-- Paquete: PKG_AOX_SUBSCRIPTION_BILLING_API (pr_enqueue/dispatch/save NCE).

SET SERVEROUTPUT ON

DECLARE
    PROCEDURE add_col(p_sql VARCHAR2, p_col VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('OK: ' || p_col);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1430 THEN
                DBMS_OUTPUT.PUT_LINE('SKIP (exists): ' || p_col);
            ELSE
                RAISE;
            END IF;
    END add_col;
    v_count NUMBER;
BEGIN
    add_col(
        'ALTER TABLE org_subscription_invoice ADD (einvoice_receptor_snapshot CLOB)',
        'EINVOICE_RECEPTOR_SNAPSHOT'
    );

    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'SUBSCRIPTION_CREDIT_NOTE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE subscription_credit_note (
              id_credit_note         NUMBER GENERATED BY DEFAULT AS IDENTITY,
              source_invoice_id      NUMBER NOT NULL,
              org_id_organization    NUMBER NOT NULL,
              cdc_ref                VARCHAR2(44) NOT NULL,
              amount                 NUMBER NOT NULL,
              motivo                 NUMBER DEFAULT 2 NOT NULL,
              description            VARCHAR2(255) NULL,
              status                 VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
              nce_cdc                VARCHAR2(44) NULL,
              nce_estado_sifen       VARCHAR2(20) NULL,
              nce_cod_res            VARCHAR2(10) NULL,
              nce_prot_aut           VARCHAR2(30) NULL,
              nce_error              VARCHAR2(500) NULL,
              emission_key           VARCHAR2(64) NULL,
              attempts               NUMBER DEFAULT 0 NOT NULL,
              last_error             VARCHAR2(500) NULL,
              lease_owner            VARCHAR2(64) NULL,
              lease_until            TIMESTAMP(6) WITH TIME ZONE NULL,
              processing_started_at  TIMESTAMP(6) WITH TIME ZONE NULL,
              created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              processed_at           TIMESTAMP(6) WITH TIME ZONE NULL,
              org_storage_addon_id   NUMBER NULL,
              CONSTRAINT pk_sub_credit_note PRIMARY KEY (id_credit_note),
              CONSTRAINT fk_sub_credit_note_inv FOREIGN KEY (source_invoice_id)
                REFERENCES org_subscription_invoice (id_invoice) ON DELETE CASCADE,
              CONSTRAINT fk_sub_credit_note_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization) ON DELETE CASCADE,
              CONSTRAINT chk_sub_credit_note_status CHECK (
                status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
              ),
              CONSTRAINT chk_sub_credit_note_motivo CHECK (motivo BETWEEN 1 AND 8),
              CONSTRAINT uq_sub_credit_note_invoice UNIQUE (source_invoice_id)
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sub_credit_note_pending ON subscription_credit_note (status, created_at)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sub_credit_note_lease ON subscription_credit_note (status, lease_until)';
        DBMS_OUTPUT.PUT_LINE('OK: SUBSCRIPTION_CREDIT_NOTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SKIP (exists): SUBSCRIPTION_CREDIT_NOTE');
    END IF;
END;
/

COMMENT ON COLUMN org_subscription_invoice.einvoice_receptor_snapshot IS
  'JSON del receptor usado al emitir la FE (snapshot para NCE referenciada).';

PROMPT === ORDS internal/subscription-credit-notes/:id/nce ===
BEGIN
    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'internal/subscription-credit-notes/:id/nce'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'internal/subscription-credit-notes/:id/nce',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_subscription_billing_api.pr_save_nce_result(
        pi_service_token  => :service_token,
        pi_credit_note_id => TO_NUMBER(:id),
        pi_body           => :body_text,
        po_status_code    => v_status_code,
        po_response_body  => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_parameter(
        p_module_name        => 'hasel',
        p_pattern            => 'internal/subscription-credit-notes/:id/nce',
        p_method             => 'POST',
        p_name               => 'X-Service-Token',
        p_bind_variable_name => 'service_token',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN',
        p_comments           => 'Token compartido Astro<->ORDS'
    );

    COMMIT;
END;
/

PROMPT === OK: 20260905_subscription_nce ===
