-- ORG_SUBSCRIPTION_ACCESS_AUDIT: auditoria de revoke/restore de acceso por ops (HASEL_ADMIN).
-- Existia en aoxdevelop sin DDL versionado; la usan pkg_aox_ops_admin_bridge y la
-- oleada VPD (pkg_aox_tenant_vpd). DDL tomado de AOXDEV con DBMS_METADATA.
-- Como AOXDEV / WKSP_AOX. Idempotente. Correr antes de recompilar el bridge y de la oleada VPD.

SET SERVEROUTPUT ON

DECLARE
    v_count NUMBER;

    PROCEDURE run_ddl(p_sql VARCHAR2, p_label VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('OK: ' || p_label);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE IN (-955, -1408, -2260, -2261, -2264, -2275) THEN
                DBMS_OUTPUT.PUT_LINE('SKIP (exists): ' || p_label);
            ELSE
                RAISE;
            END IF;
    END run_ddl;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'ORG_SUBSCRIPTION_ACCESS_AUDIT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE org_subscription_access_audit (
              id_access_audit      NUMBER GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization  NUMBER                      NOT NULL,
              action               VARCHAR2(20)                NOT NULL,
              reason               VARCHAR2(400)               NOT NULL,
              from_status          VARCHAR2(20)                NOT NULL,
              to_status            VARCHAR2(20)                NOT NULL,
              from_auto_renew      NUMBER(1,0)                 NULL,
              to_auto_renew        NUMBER(1,0)                 NULL,
              from_grace_ends_at   TIMESTAMP(6) WITH TIME ZONE NULL,
              to_grace_ends_at     TIMESTAMP(6) WITH TIME ZONE NULL,
              actor_employee_id    NUMBER                      NOT NULL,
              created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT chk_org_sub_access_action CHECK (action IN ('REVOKE', 'RESTORE')),
              CONSTRAINT pk_org_sub_access_audit PRIMARY KEY (id_access_audit),
              CONSTRAINT fk_org_sub_access_org FOREIGN KEY (org_id_organization)
                REFERENCES organization (id_organization)
            ) INITRANS 10
        ]';
        DBMS_OUTPUT.PUT_LINE('CREATED org_subscription_access_audit');
    ELSE
        DBMS_OUTPUT.PUT_LINE('org_subscription_access_audit ya existe');
    END IF;

    run_ddl(
        'CREATE INDEX idx_org_sub_access_org ON org_subscription_access_audit (org_id_organization, created_at)',
        'IDX_ORG_SUB_ACCESS_ORG'
    );
END;
/

ALTER PACKAGE pkg_aox_ops_admin_bridge COMPILE BODY;

SELECT object_name, object_type, status
  FROM user_objects
 WHERE object_name IN ('ORG_SUBSCRIPTION_ACCESS_AUDIT', 'PKG_AOX_OPS_ADMIN_BRIDGE')
 ORDER BY 1, 2;
