-- Migracion: Cierres/feriados por sucursal (LOCATION_CLOSURE)
-- Incluye:
--   1) Tabla LOCATION_CLOSURE + indices + checks
--   2) Instalacion del package PKG_AOX_LOCATION_CLOSURE_API (ver archivo aparte)
--   3) Recompilacion de PKG_AOX_UTIL / PKG_AOX_PUBLIC_BOOKING_API / PKG_AOX_LOCATION_API
--   4) Handlers ORDS (modulo hasel):
--      - GET    /locations/:id/closures
--      - POST   /locations/:id/closures
--      - DELETE /locations/:id/closures/:closure_id
--      - GET    /closures/org
--      - POST   /closures/org
--
-- Nota: los packages se despliegan via CREATE OR REPLACE de sus .pls (no incluidos aqui).

--------------------------------------------------------------------------------
-- 1) Tabla LOCATION_CLOSURE (creacion idempotente)
--------------------------------------------------------------------------------
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'LOCATION_CLOSURE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE location_closure (
              id_location_closure NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization NUMBER                      NOT NULL,
              loc_id_location     NUMBER                      NOT NULL,
              name                VARCHAR2(120)               NOT NULL,
              start_date          DATE                        NOT NULL,
              end_date            DATE                        NOT NULL,
              is_full_day         NUMBER(1,0)                 DEFAULT 1 NOT NULL,
              start_time          VARCHAR2(5)                 NULL,
              end_time            VARCHAR2(5)                 NULL,
              closure_group_id    RAW(16)                     NULL,
              created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              created_by          NUMBER                      NULL,
              CONSTRAINT pk_location_closure PRIMARY KEY (id_location_closure),
              CONSTRAINT fk_lclosure_org      FOREIGN KEY (org_id_organization) REFERENCES organization(id_organization) ON DELETE CASCADE,
              CONSTRAINT fk_lclosure_location FOREIGN KEY (loc_id_location)     REFERENCES location(id_location) ON DELETE CASCADE,
              CONSTRAINT chk_lclosure_dates    CHECK (end_date >= start_date),
              CONSTRAINT chk_lclosure_full_day CHECK (is_full_day IN (0, 1)),
              CONSTRAINT chk_lclosure_times    CHECK (
                (is_full_day = 1 AND start_time IS NULL AND end_time IS NULL)
                OR
                (is_full_day = 0
                  AND start_time IS NOT NULL AND end_time IS NOT NULL
                  AND REGEXP_LIKE(start_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
                  AND REGEXP_LIKE(end_time,   '^([01][0-9]|2[0-3]):[0-5][0-9]$')
                  AND start_time < end_time)
              )
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_loc_closure_lookup ON location_closure (loc_id_location, start_date, end_date)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_loc_closure_org    ON location_closure (org_id_organization, start_date)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_loc_closure_group  ON location_closure (closure_group_id)';
    END IF;
END;
/

--------------------------------------------------------------------------------
-- 2) ORDS: GET /locations/:id/closures
--------------------------------------------------------------------------------
BEGIN
    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'locations/:id/closures'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'locations/:id/closures',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_location_closure_api.pr_list_closures(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_location_id   => TO_NUMBER(:id),
        pi_from_date     => :from_date,
        pi_to_date       => :to_date,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'locations/:id/closures',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_location_closure_api.pr_create_closure(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_location_id   => TO_NUMBER(:id),
        pi_body          => :body_text,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );
    COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 3) ORDS: DELETE /locations/:id/closures/:closure_id
--------------------------------------------------------------------------------
BEGIN
    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'locations/:id/closures/:closure_id'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'locations/:id/closures/:closure_id',
        p_method      => 'DELETE',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
    v_delete_group  NUMBER := 0;
BEGIN
    BEGIN
        IF :delete_group IS NOT NULL AND LENGTH(TRIM(:delete_group)) > 0 THEN
            v_delete_group := TO_NUMBER(:delete_group);
        END IF;
    EXCEPTION
        WHEN OTHERS THEN v_delete_group := 0;
    END;

    pkg_aox_location_closure_api.pr_delete_closure(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_closure_id    => TO_NUMBER(:closure_id),
        pi_delete_group  => v_delete_group,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );
    COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 4) ORDS: GET /closures/org  y  POST /closures/org
--------------------------------------------------------------------------------
BEGIN
    ORDS.define_template(
        p_module_name => 'hasel',
        p_pattern     => 'closures/org'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'closures/org',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_location_closure_api.pr_list_org_closures(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_from_date     => :from_date,
        pi_to_date       => :to_date,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'closures/org',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    -- apply_all_locations = 1 forzado a nivel API (idempotente si el body ya lo trae)
    pkg_aox_location_closure_api.pr_create_closure(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_location_id   => NULL,
        pi_body          => :body_text,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status_code := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );
    COMMIT;
END;
/

PROMPT === Migracion LOCATION_CLOSURE + ORDS registrada ===
