-- Migracion: perfil fiscal de suscripcion Hasel (1:1 org)
-- Independiente de org_payment_settings (SIPAP senas).
-- Idempotente.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'ORG_BILLING_PROFILE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE org_billing_profile (
              id_billing_profile  NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
              org_id_organization NUMBER                      NOT NULL,
              billing_name        VARCHAR2(200)               NULL,
              billing_doc_type    VARCHAR2(10)                NULL,
              billing_doc_number  VARCHAR2(40)                NULL,
              billing_email       VARCHAR2(255)               NULL,
              created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              updated_by_user     NUMBER                      NULL
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_constraints
     WHERE constraint_name = 'PK_ORG_BILLING_PROFILE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_billing_profile ADD CONSTRAINT pk_org_billing_profile PRIMARY KEY (id_billing_profile)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_constraints
     WHERE constraint_name = 'UQ_ORG_BILLING_PROFILE_ORG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_billing_profile ADD CONSTRAINT uq_org_billing_profile_org UNIQUE (org_id_organization)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_constraints
     WHERE constraint_name = 'FK_ORG_BILLPROF_ORG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE org_billing_profile ADD CONSTRAINT fk_org_billprof_org FOREIGN KEY (org_id_organization) REFERENCES organization (id_organization) ON DELETE CASCADE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_constraints
     WHERE constraint_name = 'CHK_ORG_BILLPROF_DOC_TYPE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE org_billing_profile
              ADD CONSTRAINT chk_org_billprof_doc_type CHECK (
                billing_doc_type IS NULL OR billing_doc_type IN ('CI', 'RUC')
              )
        ]';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        COMMENT ON TABLE org_billing_profile IS
          'Datos fiscales 1:1 por org para facturacion de suscripcion Hasel (independiente de SIPAP senas).'
    ]';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

COMMIT;

PROMPT === org_billing_profile lista ===
