-- Inbox in-app (campanita) + feriados nacionales por pais.
--   1) organization.country_code (default PY)
--   2) ref_holiday + seed PY 2026-2027
--   3) user_notification
--   4) APP_PARAMETER HOLIDAY_NOTIFY_LEAD_DAYS / HOLIDAY_HINT_DAYS
--   5) ORDS modulo hasel:
--        GET  /inbox
--        GET  /inbox/unread-count
--        POST /inbox/:id/read
--        POST /inbox/read-all
--        GET  /inbox/holiday-hint
--   6) Job HASEL_HOLIDAY_REMINDERS (diario 08:00 America/Asuncion)
--
-- Packages: desplegar PKG_AOX_INBOX_API + recompilar PKG_AOX_FCM_API y PKG_AOX_PUSH_CAMPAIGN.

--------------------------------------------------------------------------------
-- 1) organization.country_code
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE organization ADD (
            country_code VARCHAR2(2) DEFAULT 'PY' NOT NULL
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('organization.country_code agregada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('organization.country_code ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE organization ADD CONSTRAINT chk_org_country_code
            CHECK (REGEXP_LIKE(country_code, '^[A-Z]{2}$'))
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2260, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[UPDATE organization SET country_code = ''PY'' WHERE country_code IS NULL]';
END;
/

COMMIT;

--------------------------------------------------------------------------------
-- 2) ref_holiday
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE ref_holiday (
          id_holiday    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
          country_code  VARCHAR2(2)                 NOT NULL,
          holiday_date  DATE                        NOT NULL,
          name          VARCHAR2(120)               NOT NULL,
          is_active     NUMBER(1,0)                 DEFAULT 1 NOT NULL,
          CONSTRAINT pk_ref_holiday PRIMARY KEY (id_holiday),
          CONSTRAINT uq_ref_holiday_country_date UNIQUE (country_code, holiday_date),
          CONSTRAINT chk_ref_holiday_active CHECK (is_active IN (0, 1)),
          CONSTRAINT chk_ref_holiday_country CHECK (REGEXP_LIKE(country_code, '^[A-Z]{2}$'))
        )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ref_holiday_lookup ON ref_holiday (country_code, holiday_date, is_active)';
    DBMS_OUTPUT.PUT_LINE('ref_holiday creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('ref_holiday ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

MERGE INTO ref_holiday t
USING (
    SELECT 'PY' AS country_code, DATE '2026-01-01' AS holiday_date, 'Año Nuevo' AS name FROM dual UNION ALL
    SELECT 'PY', DATE '2026-03-01', 'Día de los Héroes' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-04-02', 'Jueves Santo' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-04-03', 'Viernes Santo' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-05-01', 'Día del Trabajador' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-05-14', 'Independencia Nacional' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-05-15', 'Independencia Nacional' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-06-12', 'Paz del Chaco' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-08-15', 'Fundación de Asunción' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-09-29', 'Victoria de Boquerón' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-12-08', 'Virgen de Caacupé' FROM dual UNION ALL
    SELECT 'PY', DATE '2026-12-25', 'Navidad' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-01-01', 'Año Nuevo' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-03-01', 'Día de los Héroes' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-03-25', 'Jueves Santo' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-03-26', 'Viernes Santo' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-05-01', 'Día del Trabajador' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-05-14', 'Independencia Nacional' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-05-15', 'Independencia Nacional' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-06-12', 'Paz del Chaco' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-08-15', 'Fundación de Asunción' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-09-29', 'Victoria de Boquerón' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-12-08', 'Virgen de Caacupé' FROM dual UNION ALL
    SELECT 'PY', DATE '2027-12-25', 'Navidad' FROM dual
) s
ON (t.country_code = s.country_code AND t.holiday_date = s.holiday_date)
WHEN MATCHED THEN UPDATE SET t.name = s.name, t.is_active = 1
WHEN NOT MATCHED THEN INSERT (country_code, holiday_date, name, is_active)
VALUES (s.country_code, s.holiday_date, s.name, 1);

COMMIT;

--------------------------------------------------------------------------------
-- 3) user_notification
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE user_notification (
          id_notification      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
          org_id_organization  NUMBER                      NOT NULL,
          org_member_id        NUMBER                      NOT NULL,
          ntype                VARCHAR2(20)                NOT NULL,
          title                VARCHAR2(500)               NOT NULL,
          body                 VARCHAR2(4000)              NULL,
          action_type          VARCHAR2(30)                DEFAULT ''OPEN_URL'' NOT NULL,
          action_url           VARCHAR2(1000)              NULL,
          action_payload       CLOB                        NULL,
          appointment_id       NUMBER                      NULL,
          holiday_id           NUMBER                      NULL,
          campaign_id          NUMBER                      NULL,
          read_at              TIMESTAMP(6) WITH TIME ZONE NULL,
          created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
          dedupe_key           VARCHAR2(200)               NULL,
          CONSTRAINT pk_user_notification PRIMARY KEY (id_notification),
          CONSTRAINT fk_unotif_org FOREIGN KEY (org_id_organization)
            REFERENCES organization (id_organization) ON DELETE CASCADE,
          CONSTRAINT fk_unotif_member FOREIGN KEY (org_member_id)
            REFERENCES org_member (id_org_member) ON DELETE CASCADE,
          CONSTRAINT fk_unotif_appointment FOREIGN KEY (appointment_id)
            REFERENCES appointment (id_appointment) ON DELETE SET NULL,
          CONSTRAINT fk_unotif_holiday FOREIGN KEY (holiday_id)
            REFERENCES ref_holiday (id_holiday) ON DELETE SET NULL,
          CONSTRAINT chk_unotif_ntype CHECK (ntype IN (''APPOINTMENT'', ''PAYMENT'', ''HOLIDAY'', ''SYSTEM'')),
          CONSTRAINT chk_unotif_action CHECK (action_type IN (''OPEN_URL'', ''OPEN_CLOSURE'')),
          CONSTRAINT uq_unotif_dedupe UNIQUE (dedupe_key)
        )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_unotif_member_created ON user_notification (org_member_id, created_at)';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_unotif_member_unread ON user_notification (org_member_id, read_at)';
    DBMS_OUTPUT.PUT_LINE('user_notification creada.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('user_notification ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

--------------------------------------------------------------------------------
-- 4) Parametros
--------------------------------------------------------------------------------
MERGE INTO app_parameter t
USING (
    SELECT 'HOLIDAY_NOTIFY_LEAD_DAYS' AS param_key,
           '14' AS param_value,
           'Dias de anticipacion para avisar un feriado en la campanita.' AS description
      FROM dual
    UNION ALL
    SELECT 'HOLIDAY_HINT_DAYS',
           '15',
           'Ventana en dias para el hint de feriado en el dashboard.'
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN UPDATE SET t.param_value = s.param_value, t.description = s.description
WHEN NOT MATCHED THEN INSERT (param_key, param_value, description)
VALUES (s.param_key, s.param_value, s.description);

COMMIT;

--------------------------------------------------------------------------------
-- 5) ORDS
--------------------------------------------------------------------------------
BEGIN
    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'inbox');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'inbox',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_inbox_api.pr_list(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_limit         => CASE WHEN :limit IS NULL OR TRIM(:limit) IS NULL THEN NULL ELSE TO_NUMBER(:limit) END,
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'inbox/unread-count');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'inbox/unread-count',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_inbox_api.pr_unread_count(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'inbox/:id/read');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'inbox/:id/read',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_inbox_api.pr_mark_read(
        pi_auth_header     => owa_util.get_cgi_env('AUTHORIZATION'),
        pi_notification_id => TO_NUMBER(:id),
        po_status_code     => v_status_code,
        po_response_body   => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'inbox/read-all');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'inbox/read-all',
        p_method      => 'POST',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_inbox_api.pr_mark_all_read(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    ORDS.define_template(p_module_name => 'hasel', p_pattern => 'inbox/holiday-hint');
    ORDS.define_handler(
        p_module_name => 'hasel',
        p_pattern     => 'inbox/holiday-hint',
        p_method      => 'GET',
        p_source_type => ords.source_type_plsql,
        p_source      => q'[
DECLARE
    v_status_code   NUMBER;
    v_response_body CLOB;
BEGIN
    pkg_aox_inbox_api.pr_upcoming_holiday_hint(
        pi_auth_header   => owa_util.get_cgi_env('AUTHORIZATION'),
        po_status_code   => v_status_code,
        po_response_body => v_response_body
    );
    :status := v_status_code;
    owa_util.mime_header('application/json', TRUE);
    IF v_response_body IS NOT NULL THEN htp.prn(v_response_body); END IF;
END;
        ]'
    );

    COMMIT;
END;
/

PROMPT === ORDS inbox registrado ===

--------------------------------------------------------------------------------
-- 6) Job diario 08:00 America/Asuncion
--------------------------------------------------------------------------------
BEGIN
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(job_name => 'HASEL_HOLIDAY_REMINDERS', force => TRUE);
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'HASEL_HOLIDAY_REMINDERS',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN pkg_aox_inbox_api.pr_process_holiday_reminders; END;',
        start_date      => TO_TIMESTAMP_TZ('2026-01-01 08:00:00 America/Asuncion', 'YYYY-MM-DD HH24:MI:SS TZR'),
        repeat_interval => 'FREQ=DAILY; BYHOUR=8; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Avisa feriados nacionales en la campanita 14 dias antes.'
    );
    COMMIT;
END;
/

PROMPT === Job HASEL_HOLIDAY_REMINDERS creado ===
