-- Migracion Fase D: reclamos SLA + 3 strikes + suspension de senas

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE org_payment_settings ADD (refund_strike_count NUMBER DEFAULT 0 NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE org_payment_settings ADD (deposits_suspended NUMBER(1,0) DEFAULT 0 NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE org_payment_settings ADD (deposits_suspended_at TIMESTAMP(6) WITH TIME ZONE NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE org_payment_settings ADD (deposits_suspended_reason VARCHAR2(400) NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE org_payment_settings DROP CONSTRAINT chk_org_payset_suspended';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE org_payment_settings
  ADD CONSTRAINT chk_org_payset_suspended CHECK (deposits_suspended IN (0, 1))
/

COMMENT ON COLUMN org_payment_settings.refund_strike_count IS
  'Strikes acumulados por reembolsos fuera de SLA (3 = suspension de senas).';
/

COMMENT ON COLUMN org_payment_settings.deposits_suspended IS
  '1 = senas suspendidas por Hasel tras 3 strikes. No se puede reactivar desde el panel.';
/

-- Tabla de reclamos
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE org_refund_claim (
      id_claim            NUMBER GENERATED BY DEFAULT AS IDENTITY,
      org_id_organization NUMBER NOT NULL,
      app_id_appointment  NUMBER NOT NULL,
      claim_source        VARCHAR2(20) NOT NULL,
      claim_status        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
      strike_counted      NUMBER(1,0) DEFAULT 1 NOT NULL,
      notes               VARCHAR2(500) NULL,
      created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      resolved_at         TIMESTAMP(6) WITH TIME ZONE NULL,
      resolved_by         NUMBER NULL,
      CONSTRAINT pk_org_refund_claim PRIMARY KEY (id_claim),
      CONSTRAINT fk_refund_claim_org FOREIGN KEY (org_id_organization)
        REFERENCES organization (id_organization) ON DELETE CASCADE,
      CONSTRAINT fk_refund_claim_app FOREIGN KEY (app_id_appointment)
        REFERENCES appointment (id_appointment),
      CONSTRAINT chk_refund_claim_source CHECK (claim_source IN ('CUSTOMER', 'SLA_JOB')),
      CONSTRAINT chk_refund_claim_status CHECK (claim_status IN ('OPEN', 'RESOLVED', 'DISMISSED')),
      CONSTRAINT chk_refund_claim_strike CHECK (strike_counted IN (0, 1))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX idx_refund_claim_org_status ON org_refund_claim (org_id_organization, claim_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- Un solo reclamo OPEN por cita
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE UNIQUE INDEX uq_refund_claim_app_open
      ON org_refund_claim (CASE WHEN claim_status = 'OPEN' THEN app_id_appointment END)
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

COMMIT;

PROMPT === Fase D DDL finalizada ===
