-- =============================================================================
-- Migracion: invitaciones de personal a organizacion (sin crear platform_user)
--
-- ORDEN EN PRODUCCION: docs/DEPLOY_PRODUCTION_CHECKLIST.md (fase 3.4, despues de 20260528)
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT === FASE 1: Tabla org_invitation ===

BEGIN
    EXECUTE IMMEDIATE 'SELECT 1 FROM org_invitation WHERE ROWNUM = 1';
    DBMS_OUTPUT.PUT_LINE('org_invitation ya existe.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            EXECUTE IMMEDIATE q'[
                CREATE TABLE org_invitation (
                  id_org_invitation   NUMBER GENERATED BY DEFAULT AS IDENTITY,
                  org_id_organization NUMBER NOT NULL,
                  pro_id_professional NUMBER NOT NULL,
                  platform_user_id    NUMBER NULL,
                  invite_email        VARCHAR2(150) NOT NULL,
                  invite_first_name   VARCHAR2(50) NOT NULL,
                  invite_last_name    VARCHAR2(50) NOT NULL,
                  apex_user_name      VARCHAR2(100) NOT NULL,
                  rol_id_role         NUMBER NOT NULL,
                  invite_token        VARCHAR2(64) NOT NULL,
                  status              VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                  invited_by          NUMBER NULL,
                  expires_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                  accepted_at         TIMESTAMP(6) WITH TIME ZONE NULL,
                  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  CONSTRAINT pk_org_invitation PRIMARY KEY (id_org_invitation),
                  CONSTRAINT uq_org_invitation_token UNIQUE (invite_token),
                  CONSTRAINT chk_org_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED')),
                  CONSTRAINT fk_org_invitation_org FOREIGN KEY (org_id_organization)
                    REFERENCES organization (id_organization) ON DELETE CASCADE,
                  CONSTRAINT fk_org_invitation_pro FOREIGN KEY (pro_id_professional)
                    REFERENCES professional (id_professional) ON DELETE CASCADE,
                  CONSTRAINT fk_org_invitation_role FOREIGN KEY (rol_id_role)
                    REFERENCES role (id_role),
                  CONSTRAINT fk_org_invitation_platform_user FOREIGN KEY (platform_user_id)
                    REFERENCES platform_user (id_platform_user) ON DELETE SET NULL,
                  CONSTRAINT fk_org_invitation_invited_by FOREIGN KEY (invited_by)
                    REFERENCES org_member (id_org_member) ON DELETE SET NULL
                )]';
            EXECUTE IMMEDIATE '
                CREATE INDEX idx_org_invitation_org_email
                  ON org_invitation (org_id_organization, lower(invite_email), status)';
            EXECUTE IMMEDIATE '
                CREATE INDEX idx_org_invitation_pro
                  ON org_invitation (pro_id_professional, status)';
            DBMS_OUTPUT.PUT_LINE('org_invitation creada.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT === FASE 2: professional.usr_id_user nullable (invitaciones pendientes) ===

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE professional MODIFY (
          usr_id_user NUMBER NULL
        )';
    DBMS_OUTPUT.PUT_LINE('professional.usr_id_user ahora permite NULL.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1442 OR SQLCODE = -1451 THEN
            DBMS_OUTPUT.PUT_LINE('professional.usr_id_user ya era nullable o no requiere cambio.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT === FASE 3: Trigger slug con invitaciones pendientes ===

CREATE OR REPLACE TRIGGER trg_professional_slug
BEFORE INSERT OR UPDATE OF profile_slug, usr_id_user ON professional
FOR EACH ROW
DECLARE
    v_first_name platform_user.first_name%TYPE;
    v_last_name  platform_user.last_name%TYPE;
BEGIN
    IF :NEW.profile_slug IS NOT NULL THEN
        :NEW.profile_slug := pkg_aox_util.fn_generate_slug(:NEW.profile_slug);
        RETURN;
    END IF;

    IF :NEW.usr_id_user IS NOT NULL THEN
        SELECT pu.first_name, pu.last_name
          INTO v_first_name, v_last_name
          FROM org_member m
          JOIN platform_user pu ON pu.id_platform_user = m.platform_user_id
         WHERE m.id_org_member = :NEW.usr_id_user;

        :NEW.profile_slug :=
            pkg_aox_util.fn_generate_slug(v_first_name || ' ' || v_last_name || '-' || :NEW.usr_id_user);
        RETURN;
    END IF;

  -- Profesional pendiente de invitacion (sin org_member aun)
    :NEW.profile_slug := pkg_aox_util.fn_generate_slug('profesional-' || lower(rawtohex(sys_guid())));
END;
/

PROMPT === FASE 4: Post-validacion ===

DECLARE
    v_orphan_active NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_orphan_active
      FROM professional p
      LEFT JOIN org_member m ON m.id_org_member = p.usr_id_user
     WHERE p.usr_id_user IS NOT NULL
       AND m.id_org_member IS NULL;

    IF v_orphan_active > 0 THEN
        RAISE_APPLICATION_ERROR(-20005,
            'Profesionales activos sin org_member: ' || v_orphan_active);
    END IF;

    DBMS_OUTPUT.PUT_LINE('Post-validacion OK.');
END;
/
INSERT INTO app_parameter (param_key, param_value, description)
  VALUES('APP_PUBLIC_BASE_URL', 'https://staging.hasel.app', 'URL base de la app.');
COMMIT;


PROMPT === Migracion 20260529 completada ===
