-- =============================================================================
-- Migracion: identidad global (platform_user) + membresias (org_member)
-- Preserva id_org_member = antiguo app_user.id_user (JWT, professional, citas, sesiones).
--
-- ORDEN EN PRODUCCION: ver docs/DEPLOY_PRODUCTION_CHECKLIST.md
--   (Pagopar DDL antes; este script despues; invitaciones 20260529 despues de este)
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT === FASE 0: Pre-chequeos ===

DECLARE
    v_app_users   NUMBER;
    v_dup_email   NUMBER;
    v_orphans_pro NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_app_users FROM app_user;

    SELECT COUNT(*) INTO v_dup_email
      FROM (
        SELECT lower(email) e, COUNT(*) c
          FROM app_user
         GROUP BY lower(email)
        HAVING COUNT(*) > 1
      );

    IF v_dup_email > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Hay correos duplicados en app_user. Resolver manualmente antes de migrar.');
    END IF;

    SELECT COUNT(*) INTO v_orphans_pro
      FROM professional p
      LEFT JOIN app_user u ON u.id_user = p.usr_id_user
     WHERE u.id_user IS NULL;

    IF v_orphans_pro > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Profesionales sin app_user. Corregir antes de migrar.');
    END IF;

    DBMS_OUTPUT.PUT_LINE('app_user rows: ' || v_app_users);
    DBMS_OUTPUT.PUT_LINE('Pre-chequeos OK.');
END;
/

PROMPT === FASE 1: Tablas nuevas (si no existen) ===

BEGIN
    EXECUTE IMMEDIATE 'SELECT 1 FROM platform_user WHERE ROWNUM = 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            EXECUTE IMMEDIATE q'[
                CREATE TABLE platform_user (
                  id_platform_user  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                  apex_user_name    VARCHAR2(100) NOT NULL,
                  email             VARCHAR2(150) NOT NULL,
                  password_hash     VARCHAR2(255) NOT NULL,
                  first_name        VARCHAR2(50) NOT NULL,
                  last_name         VARCHAR2(50) NOT NULL,
                  is_active         NUMBER(1) DEFAULT 1 NOT NULL,
                  email_verified_at TIMESTAMP(6) WITH TIME ZONE NULL,
                  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  CONSTRAINT pk_platform_user PRIMARY KEY (id_platform_user),
                  CONSTRAINT uq_pu_email UNIQUE (email),
                  CONSTRAINT uq_pu_apex_user UNIQUE (apex_user_name),
                  CONSTRAINT chk_pu_active CHECK (is_active IN (0, 1))
                )]';
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'SELECT 1 FROM org_member WHERE ROWNUM = 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            EXECUTE IMMEDIATE q'[
                CREATE TABLE org_member (
                  id_org_member       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                  platform_user_id    NUMBER NOT NULL,
                  org_id_organization NUMBER NOT NULL,
                  rol_id_role         NUMBER NOT NULL,
                  is_active           NUMBER(1) DEFAULT 1 NOT NULL,
                  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  CONSTRAINT pk_org_member PRIMARY KEY (id_org_member),
                  CONSTRAINT uq_om_user_org UNIQUE (platform_user_id, org_id_organization),
                  CONSTRAINT chk_om_active CHECK (is_active IN (0, 1)),
                  CONSTRAINT fk_om_platform_user FOREIGN KEY (platform_user_id)
                    REFERENCES platform_user (id_platform_user),
                  CONSTRAINT fk_om_organization FOREIGN KEY (org_id_organization)
                    REFERENCES organization (id_organization) ON DELETE CASCADE,
                  CONSTRAINT fk_om_role FOREIGN KEY (rol_id_role) REFERENCES role (id_role)
                )]';
            EXECUTE IMMEDIATE 'CREATE INDEX idx_om_org ON org_member (org_id_organization)';
            EXECUTE IMMEDIATE 'CREATE INDEX idx_om_platform_user ON org_member (platform_user_id)';
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT === FASE 2: Copiar datos (IDs de membresia preservados) ===

DECLARE
    v_pu_count NUMBER;
    v_om_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_pu_count FROM platform_user;
    IF v_pu_count = 0 THEN
        INSERT INTO platform_user (
            apex_user_name, email, password_hash, first_name, last_name,
            is_active, email_verified_at, created_at
        )
        SELECT
            apex_user_name,
            lower(trim(email)),
            password_hash,
            first_name,
            last_name,
            is_active,
            email_verified_at,
            created_at
        FROM app_user;

        DBMS_OUTPUT.PUT_LINE('platform_user insertados: ' || SQL%ROWCOUNT);
    ELSE
        DBMS_OUTPUT.PUT_LINE('platform_user ya tiene datos, se omite INSERT.');
    END IF;

    SELECT COUNT(*) INTO v_om_count FROM org_member;
    IF v_om_count = 0 THEN
        INSERT INTO org_member (
            id_org_member,
            platform_user_id,
            org_id_organization,
            rol_id_role,
            is_active,
            created_at
        )
        SELECT
            au.id_user,
            pu.id_platform_user,
            au.org_id_organization,
            au.rol_id_role,
            au.is_active,
            au.created_at
        FROM app_user au
        INNER JOIN platform_user pu ON lower(pu.email) = lower(trim(au.email));

        DBMS_OUTPUT.PUT_LINE('org_member insertados: ' || SQL%ROWCOUNT);

        -- Alinear secuencia IDENTITY tras insertar IDs explícitos
        BEGIN
            EXECUTE IMMEDIATE '
                ALTER TABLE org_member MODIFY (
                    id_org_member GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)
                )';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    ELSE
        DBMS_OUTPUT.PUT_LINE('org_member ya tiene datos, se omite INSERT.');
    END IF;

    COMMIT;
END;
/

PROMPT === FASE 3: Validar conteos ===

DECLARE
    v_au NUMBER;
    v_om NUMBER;
    v_pu NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_au FROM app_user;
    SELECT COUNT(*) INTO v_om FROM org_member;
    SELECT COUNT(*) INTO v_pu FROM platform_user;

    IF v_au <> v_om THEN
        RAISE_APPLICATION_ERROR(-20003, 'Conteo app_user (' || v_au || ') <> org_member (' || v_om || ').');
    END IF;

    DBMS_OUTPUT.PUT_LINE('app_user=' || v_au || ' org_member=' || v_om || ' platform_user=' || v_pu);
END;
/

PROMPT === FASE 4: Reapuntar FKs hijas de app_user -> org_member ===

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE professional DROP CONSTRAINT fk_pro_user';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE professional
        ADD CONSTRAINT fk_pro_org_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE app_user_session DROP CONSTRAINT fk_session_user';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE app_user_session
        ADD CONSTRAINT fk_session_org_member FOREIGN KEY (use_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE app_user_email_verification DROP CONSTRAINT fk_email_ver_user';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE app_user_email_verification
        ADD CONSTRAINT fk_email_ver_org_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE app_user_pwd_reset DROP CONSTRAINT fk_pwd_reset_user';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE app_user_pwd_reset
        ADD CONSTRAINT fk_pwd_reset_org_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE user_integration DROP CONSTRAINT fk_user_integration_user';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE user_integration
        ADD CONSTRAINT fk_user_integration_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2261, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE user_fcm_devices DROP CONSTRAINT fk_fcm_user';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE user_fcm_devices
        ADD CONSTRAINT fk_fcm_org_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2261, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ai_chat_session DROP CONSTRAINT fk_ai_chat_user';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE ai_chat_session
        ADD CONSTRAINT fk_ai_chat_org_member FOREIGN KEY (usr_id_user)
        REFERENCES org_member (id_org_member) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2261, -942) THEN RAISE; END IF;
END;
/

PROMPT === FASE 5: Renombrar app_user (tabla) y crear vista de compatibilidad ===

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE app_user RENAME TO app_user_legacy';
    DBMS_OUTPUT.PUT_LINE('Tabla app_user renombrada a app_user_legacy.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('app_user ya no existe como tabla (ok si re-ejecucion).');
        ELSIF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('app_user_legacy ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

@@../views/APP_USER_COMPAT.sql

PROMPT === FASE 6: Trigger professional (slug) sobre platform_user ===

CREATE OR REPLACE TRIGGER trg_professional_slug
BEFORE INSERT OR UPDATE OF profile_slug, usr_id_user ON professional
FOR EACH ROW
DECLARE
    v_first_name platform_user.first_name%TYPE;
    v_last_name  platform_user.last_name%TYPE;
BEGIN
    IF :NEW.profile_slug IS NULL THEN
        SELECT pu.first_name, pu.last_name
          INTO v_first_name, v_last_name
          FROM org_member m
          JOIN platform_user pu ON pu.id_platform_user = m.platform_user_id
         WHERE m.id_org_member = :NEW.usr_id_user;

        :NEW.profile_slug :=
            pkg_aox_util.fn_generate_slug(v_first_name || ' ' || v_last_name || '-' || :NEW.usr_id_user);
    ELSE
        :NEW.profile_slug := pkg_aox_util.fn_generate_slug(:NEW.profile_slug);
    END IF;
END;
/

PROMPT === FASE 7: Post-validacion integridad ===

DECLARE
    v_orphan_pro NUMBER;
    v_orphan_ses NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_orphan_pro
      FROM professional p
      LEFT JOIN org_member m ON m.id_org_member = p.usr_id_user
     WHERE m.id_org_member IS NULL;

    SELECT COUNT(*) INTO v_orphan_ses
      FROM app_user_session s
      LEFT JOIN org_member m ON m.id_org_member = s.use_id_user
     WHERE m.id_org_member IS NULL;

    IF v_orphan_pro > 0 OR v_orphan_ses > 0 THEN
        RAISE_APPLICATION_ERROR(-20004,
            'Huerfanos tras migracion. professional=' || v_orphan_pro || ' sessions=' || v_orphan_ses);
    END IF;

    DBMS_OUTPUT.PUT_LINE('Post-validacion OK. Sin huérfanos.');
END;
/

PROMPT === Migracion completada ===
PROMPT Siguiente: recompilar paquetes y probar login de admin + empleado con citas.
