-- Hardening billing E2E (aoxdev): outbox FE (lease/emission_key), estados email
-- separados, ESIGN params reparativos SIN sobrescribir URL productiva, y fixture ID.
-- NO toca BILLING_ENABLED ni Consultorio General (org 1).
--
-- Fixture seed/cleanup: scripts/qa_billing_e2e_*.sql

PROMPT === 1) subscription_einvoice_outbox ===
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'SUBSCRIPTION_EINVOICE_OUTBOX';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE subscription_einvoice_outbox (
              id_outbox            NUMBER GENERATED BY DEFAULT AS IDENTITY,
              invoice_id           NUMBER NOT NULL,
              org_id_organization  NUMBER NOT NULL,
              status               VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
              attempts             NUMBER DEFAULT 0 NOT NULL,
              last_error           VARCHAR2(500),
              created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              processed_at         TIMESTAMP(6) WITH TIME ZONE,
              emission_key         VARCHAR2(64),
              lease_owner          VARCHAR2(64),
              lease_until          TIMESTAMP(6) WITH TIME ZONE,
              processing_started_at TIMESTAMP(6) WITH TIME ZONE
            )
        ]';
        EXECUTE IMMEDIATE 'ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT pk_sub_einvoice_outbox PRIMARY KEY (id_outbox)';
        EXECUTE IMMEDIATE 'ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT fk_sub_einv_outbox_inv FOREIGN KEY (invoice_id) REFERENCES org_subscription_invoice (id_invoice) ON DELETE CASCADE';
        EXECUTE IMMEDIATE 'ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT fk_sub_einv_outbox_org FOREIGN KEY (org_id_organization) REFERENCES organization (id_organization) ON DELETE CASCADE';
        EXECUTE IMMEDIATE q'[ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT chk_sub_einv_outbox_status CHECK (status IN ('PENDING','PROCESSING','DONE','FAILED'))]';
        EXECUTE IMMEDIATE 'ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT uq_sub_einv_outbox_invoice UNIQUE (invoice_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sub_einv_outbox_pending ON subscription_einvoice_outbox (status, created_at)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sub_einv_outbox_lease ON subscription_einvoice_outbox (status, lease_until)';
    END IF;
END;
/

DECLARE
    PROCEDURE add_col(pi_ddl IN VARCHAR2, pi_column IN VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
          FROM user_tab_columns
         WHERE table_name = 'SUBSCRIPTION_EINVOICE_OUTBOX'
           AND column_name = pi_column;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE pi_ddl;
        END IF;
    END add_col;
BEGIN
    add_col('ALTER TABLE subscription_einvoice_outbox ADD (emission_key VARCHAR2(64))', 'EMISSION_KEY');
    add_col('ALTER TABLE subscription_einvoice_outbox ADD (lease_owner VARCHAR2(64))', 'LEASE_OWNER');
    add_col('ALTER TABLE subscription_einvoice_outbox ADD (lease_until TIMESTAMP(6) WITH TIME ZONE)', 'LEASE_UNTIL');
    add_col('ALTER TABLE subscription_einvoice_outbox ADD (processing_started_at TIMESTAMP(6) WITH TIME ZONE)', 'PROCESSING_STARTED_AT');
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_sub_einv_outbox_lease ON subscription_einvoice_outbox (status, lease_until)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- Backfill emission_key inmutable para filas existentes.
UPDATE subscription_einvoice_outbox
   SET emission_key = 'INV-' || TO_CHAR(invoice_id)
 WHERE emission_key IS NULL;

COMMENT ON COLUMN subscription_einvoice_outbox.emission_key IS
  'Clave idempotente inmutable (INV-{invoice_id}) propagada a Astro/firmador.';
COMMENT ON COLUMN subscription_einvoice_outbox.lease_owner IS
  'Identificador del worker que reclamo la fila (lease).';
COMMENT ON COLUMN subscription_einvoice_outbox.lease_until IS
  'Vencimiento del lease; PROCESSING expirado se reclama de nuevo.';
COMMENT ON COLUMN subscription_einvoice_outbox.processing_started_at IS
  'Timestamp del ultimo reclamo atomico a PROCESSING.';

PROMPT === 2) Columnas email FE (separadas del ciclo SIFEN) ===
DECLARE
    PROCEDURE add_col(pi_ddl IN VARCHAR2, pi_column IN VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
          FROM user_tab_columns
         WHERE table_name = 'ORG_SUBSCRIPTION_INVOICE'
           AND column_name = pi_column;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE pi_ddl;
        END IF;
    END add_col;
BEGIN
    add_col(q'[ALTER TABLE org_subscription_invoice ADD (einvoice_email_status VARCHAR2(20) DEFAULT 'NONE' NOT NULL)]', 'EINVOICE_EMAIL_STATUS');
    add_col(q'[ALTER TABLE org_subscription_invoice ADD (einvoice_email_error VARCHAR2(500) NULL)]', 'EINVOICE_EMAIL_ERROR');
    add_col(q'[ALTER TABLE org_subscription_invoice ADD (einvoice_email_attempts NUMBER DEFAULT 0 NOT NULL)]', 'EINVOICE_EMAIL_ATTEMPTS');
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_einvoice_email_status CHECK (
            einvoice_email_status IN ('NONE', 'PENDING', 'SENT', 'FAILED')
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2264, -2260) THEN RAISE; END IF;
END;
/

COMMENT ON COLUMN org_subscription_invoice.einvoice_email_status IS
  'Envio de correo con KuDE: NONE | PENDING | SENT | FAILED. Independiente de einvoice_status (FE/KuDE).';
COMMENT ON COLUMN org_subscription_invoice.einvoice_email_error IS
  'Ultimo error al enviar el mail FACTURASUSCRIPCIONV2 (no debe reabrir emision FE).';
COMMENT ON COLUMN org_subscription_invoice.einvoice_email_attempts IS
  'Reintentos de envio de correo (acotados en pr_retry_pending_einvoice_emails).';

PROMPT === 3) ESIGN_WEBHOOK_URL: solo insert o reparar path viejo (NO pisar prod con staging) ===
-- Inserta si falta. Si existe un path legacy /api/esign/..., lo repara preservando el host.
-- Nunca fuerza staging.hasel.app sobre hasel.app u otro host ya configurado.
MERGE INTO app_parameter t
USING (
    SELECT 'ESIGN_WEBHOOK_URL' AS param_key,
           'https://staging.hasel.app/api/internal/esign/emit-invoice' AS param_value,
           'Base URL del callback Astro (POST emit-invoice). Configurar por ambiente en despliegue; no sobrescribir prod con staging.' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.description = s.description,
               t.param_value = CASE
                   WHEN REGEXP_LIKE(NVL(t.param_value, ''), '/api/esign(/|$)', 'i') THEN
                       REGEXP_REPLACE(t.param_value, '/api/esign(/|$)', '/api/internal/esign/emit-invoice', 1, 1, 'i')
                   ELSE t.param_value
               END
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

MERGE INTO app_parameter t
USING (
    SELECT 'ESIGN_CALLBACK_SERVICE_TOKEN' AS param_key,
           NULL AS param_value,
           'Secreto X-Service-Token Oracle↔Astro. NO versionar el valor: setear solo en app_parameter / secretos de despliegue.' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.description = s.description
    -- No pisa param_value existente (rotacion manual / script operativo).
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, NULL, s.description);

MERGE INTO app_parameter t
USING (
    SELECT 'QA_BILLING_E2E_ORG_NAME' AS param_key,
           'QA Billing E2E' AS param_value,
           'Nombre de la org fixture de pruebas E2E de billing (scripts/qa_billing_e2e_*.sql).' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.param_value = s.param_value,
               t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, s.param_value, s.description);

-- QA_BILLING_E2E_ORG_ID: solo insert placeholder NULL; el seed escribe el id real.
MERGE INTO app_parameter t
USING (
    SELECT 'QA_BILLING_E2E_ORG_ID' AS param_key,
           NULL AS param_value,
           'id_organization inmutable de la fixture QA Billing E2E (lo setea scripts/qa_billing_e2e_seed.sql).' AS description
      FROM dual
) s
ON (t.param_key = s.param_key)
WHEN MATCHED THEN
    UPDATE SET t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (param_key, param_value, description)
    VALUES (s.param_key, NULL, s.description);

COMMIT;

PROMPT === OK: 20260831_billing_e2e_hardening ===
PROMPT Siguiente: @@scripts/qa_billing_e2e_seed.sql  y recompilar PKG_AOX_SUBSCRIPTION_BILLING_API
