PROMPT CREATE TABLE ai_chat_message
CREATE TABLE ai_chat_message (
  id_message          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  ses_id_session      NUMBER                      NOT NULL,
  org_id_organization NUMBER                      NOT NULL,
  sender_role         VARCHAR2(20)                NOT NULL,
  content             CLOB                        NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_msg_org
CREATE INDEX idx_msg_org
  ON ai_chat_message (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_msg_session
CREATE INDEX idx_msg_session
  ON ai_chat_message (
    ses_id_session,
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ai_chat_message ADD CONSTRAINT chk_msg_role CHECK
ALTER TABLE ai_chat_message
  ADD CONSTRAINT chk_msg_role CHECK (
    sender_role IN ('user', 'assistant', 'system')
  )
/

PROMPT ALTER TABLE ai_chat_message ADD CONSTRAINT pk_ai_chat_message PRIMARY KEY
ALTER TABLE ai_chat_message
  ADD CONSTRAINT pk_ai_chat_message PRIMARY KEY (
    id_message
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ai_chat_message ADD CONSTRAINT fk_msg_session FOREIGN KEY
ALTER TABLE ai_chat_message
  ADD CONSTRAINT fk_msg_session FOREIGN KEY (
    ses_id_session,
    org_id_organization
  ) REFERENCES ai_chat_session (
    id_session,
    org_id_organization
  ) ON DELETE CASCADE
/

COMMENT ON COLUMN ai_chat_message.org_id_organization IS
  'Org denormalizada desde ai_chat_session. FK compuesta (sesion, org) impide desviarla.';
/
