PROMPT CREATE TABLE ai_chat_session
CREATE TABLE ai_chat_session (
  id_session          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  usr_id_user         NUMBER                      NOT NULL,
  title               VARCHAR2(200)               DEFAULT 'Nuevo Chat' NULL,
  is_active           NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ai_chat_session ADD CONSTRAINT pk_ai_chat_session PRIMARY KEY
ALTER TABLE ai_chat_session
  ADD CONSTRAINT pk_ai_chat_session PRIMARY KEY (
    id_session
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ai_chat_session ADD CONSTRAINT fk_chat_org FOREIGN KEY
ALTER TABLE ai_chat_session
  ADD CONSTRAINT fk_chat_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE ai_chat_session ADD CONSTRAINT fk_chat_usr FOREIGN KEY
ALTER TABLE ai_chat_session
  ADD CONSTRAINT fk_chat_usr FOREIGN KEY (
    usr_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/


