PROMPT CREATE TABLE aox_log_webhook_meta
CREATE TABLE aox_log_webhook_meta (
  id_log     NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  payload    CLOB                        NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/
