PROMPT CREATE TABLE aox_api_log
CREATE TABLE aox_api_log (
  id_log          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  api_name        VARCHAR2(200)               NULL,
  process_name    VARCHAR2(200)               NULL,
  http_method     VARCHAR2(20)                NULL,
  endpoint        VARCHAR2(500)               NULL,
  org_id          NUMBER                      NULL,
  user_id         NUMBER                      NULL,
  status          VARCHAR2(30)                NULL,
  status_code     NUMBER                      NULL,
  error_code      NUMBER                      NULL,
  error_message   VARCHAR2(4000)              NULL,
  error_stack     CLOB                        NULL,
  error_backtrace CLOB                        NULL,
  request_body    CLOB                        NULL,
  request_params  CLOB                        NULL,
  response_body   CLOB                        NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_aox_api_log_created
CREATE INDEX idx_aox_api_log_created
  ON aox_api_log (
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_aox_api_log_name
CREATE INDEX idx_aox_api_log_name
  ON aox_api_log (
    api_name,
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE aox_api_log ADD CONSTRAINT pk_aox_api_log PRIMARY KEY
ALTER TABLE aox_api_log
  ADD CONSTRAINT pk_aox_api_log PRIMARY KEY (
    id_log
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


