PROMPT CREATE TABLE aox_whatsapp_template_log
CREATE TABLE aox_whatsapp_template_log (
  id_log          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  process_name    VARCHAR2(200)               NULL,
  appointment_id  NUMBER                      NULL,
  template_name   VARCHAR2(120)               NULL,
  phone_number    VARCHAR2(50)                NULL,
  status          VARCHAR2(30)                NULL,
  status_code     NUMBER                      NULL,
  error_code      NUMBER                      NULL,
  error_message   VARCHAR2(4000)              NULL,
  error_stack     CLOB                        NULL,
  error_backtrace CLOB                        NULL,
  request_payload CLOB                        NULL,
  response_body   CLOB                        NULL,
  parameters      CLOB                        NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_aox_wa_tmpl_log_app
CREATE INDEX idx_aox_wa_tmpl_log_app
  ON aox_whatsapp_template_log (
    appointment_id,
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_aox_wa_tmpl_log_created
CREATE INDEX idx_aox_wa_tmpl_log_created
  ON aox_whatsapp_template_log (
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE aox_whatsapp_template_log ADD CONSTRAINT pk_aox_wa_tmpl_log PRIMARY KEY
ALTER TABLE aox_whatsapp_template_log
  ADD CONSTRAINT pk_aox_wa_tmpl_log PRIMARY KEY (
    id_log
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


