PROMPT CREATE TABLE aox_ai_log
CREATE TABLE aox_ai_log (
  id_log          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  process_name    VARCHAR2(200)               NULL,
  session_id      NUMBER                      NULL,
  org_id          NUMBER                      NULL,
  user_id         NUMBER                      NULL,
  role_id         NUMBER                      NULL,
  pro_id          NUMBER                      NULL,
  status          VARCHAR2(30)                NULL,
  status_code     NUMBER                      NULL,
  error_code      NUMBER                      NULL,
  error_message   VARCHAR2(4000)              NULL,
  error_stack     CLOB                        NULL,
  error_backtrace CLOB                        NULL,
  prompt          CLOB                        NULL,
  request_payload CLOB                        NULL,
  response_body   CLOB                        NULL,
  parameters      CLOB                        NULL
)
  INITRANS  10
/

PROMPT CREATE INDEX idx_aox_ai_log_context
CREATE INDEX idx_aox_ai_log_context
  ON aox_ai_log (
    org_id,
    user_id,
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
/

PROMPT CREATE INDEX idx_aox_ai_log_created
CREATE INDEX idx_aox_ai_log_created
  ON aox_ai_log (
    SYS_EXTRACT_UTC("CREATED_AT")
  )
  INITRANS  20
/

PROMPT ALTER TABLE aox_ai_log ADD CONSTRAINT pk_aox_ai_log PRIMARY KEY
ALTER TABLE aox_ai_log
  ADD CONSTRAINT pk_aox_ai_log PRIMARY KEY (
    id_log
  )
  USING INDEX
    INITRANS  20
/


