PROMPT CREATE TABLE app_user_email_verification
CREATE TABLE app_user_email_verification (
  id_verification NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  usr_id_user     NUMBER                      NOT NULL,
  code_hash       VARCHAR2(64)                NOT NULL,
  expires_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  consumed_at     TIMESTAMP(6) WITH TIME ZONE NULL,
  attempt_count   NUMBER(2,0)                 DEFAULT 0 NOT NULL,
  max_attempts    NUMBER(2,0)                 DEFAULT 5 NOT NULL,
  sent_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_usr_email_ver_exp
CREATE INDEX idx_usr_email_ver_exp
  ON app_user_email_verification (
    SYS_EXTRACT_UTC("EXPIRES_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_usr_email_ver_usr
CREATE INDEX idx_usr_email_ver_usr
  ON app_user_email_verification (
    usr_id_user,
    SYS_EXTRACT_UTC("CONSUMED_AT"),
    SYS_EXTRACT_UTC("EXPIRES_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE app_user_email_verification ADD CONSTRAINT chk_usr_email_ver_attempts CHECK
ALTER TABLE app_user_email_verification
  ADD CONSTRAINT chk_usr_email_ver_attempts CHECK (
    attempt_count >= 0
    AND max_attempts BETWEEN 1 AND 9
    AND attempt_count <= max_attempts
  )
/

PROMPT ALTER TABLE app_user_email_verification ADD CONSTRAINT pk_app_user_email_verification PRIMARY KEY
ALTER TABLE app_user_email_verification
  ADD CONSTRAINT pk_app_user_email_verification PRIMARY KEY (
    id_verification
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_user_email_verification ADD CONSTRAINT fk_email_ver_user FOREIGN KEY
ALTER TABLE app_user_email_verification
  ADD CONSTRAINT fk_email_ver_user FOREIGN KEY (
    usr_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/


