PROMPT CREATE TABLE app_user_session
CREATE TABLE app_user_session (
  id_session    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  use_id_user   NUMBER                      NOT NULL,
  refresh_token VARCHAR2(255)               NOT NULL,
  expires_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  is_revoked    NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE app_user_session ADD PRIMARY KEY
ALTER TABLE app_user_session
  ADD PRIMARY KEY (
    id_session
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_user_session ADD UNIQUE
ALTER TABLE app_user_session
  ADD UNIQUE (
    refresh_token
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_user_session ADD CONSTRAINT fk_session_user FOREIGN KEY
ALTER TABLE app_user_session
  ADD CONSTRAINT fk_session_user FOREIGN KEY (
    use_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/


