PROMPT CREATE TABLE app_user_pwd_reset
CREATE TABLE app_user_pwd_reset (
  id_reset    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  usr_id_user NUMBER                      NOT NULL,
  reset_token VARCHAR2(100)               NOT NULL,
  expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  is_used     NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE app_user_pwd_reset ADD CONSTRAINT pk_app_user_pwd_reset PRIMARY KEY
ALTER TABLE app_user_pwd_reset
  ADD CONSTRAINT pk_app_user_pwd_reset PRIMARY KEY (
    id_reset
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_user_pwd_reset ADD CONSTRAINT uk_app_user_pwd_reset_token UNIQUE
ALTER TABLE app_user_pwd_reset
  ADD CONSTRAINT uk_app_user_pwd_reset_token UNIQUE (
    reset_token
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_user_pwd_reset ADD CONSTRAINT fk_pwd_reset_user FOREIGN KEY
ALTER TABLE app_user_pwd_reset
  ADD CONSTRAINT fk_pwd_reset_user FOREIGN KEY (
    usr_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/


