PROMPT CREATE TABLE app_parameter
CREATE TABLE app_parameter (
  id_parameter NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  param_key    VARCHAR2(100)  NOT NULL,
  param_value  VARCHAR2(4000) NOT NULL,
  description  VARCHAR2(255)  NULL,
  created_at   TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE app_parameter ADD PRIMARY KEY
ALTER TABLE app_parameter
  ADD PRIMARY KEY (
    id_parameter
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE app_parameter ADD UNIQUE
ALTER TABLE app_parameter
  ADD UNIQUE (
    param_key
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


