PROMPT CREATE TABLE appointment_attachment
CREATE TABLE appointment_attachment (
  id_attachment       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  app_id_appointment  NUMBER                      NOT NULL,
  org_id_organization NUMBER                      NOT NULL,
  file_name           VARCHAR2(255)               NOT NULL,
  mime_type           VARCHAR2(150)               NULL,
  size_bytes          NUMBER                      DEFAULT 0 NOT NULL,
  storage_url         VARCHAR2(1000)              NOT NULL,
  created_by_user     NUMBER                      NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_appatt_appointment ON appointment_attachment (app_id_appointment)
CREATE INDEX idx_appatt_appointment
  ON appointment_attachment (
    app_id_appointment
  )
/

PROMPT CREATE INDEX idx_appatt_org ON appointment_attachment (org_id_organization)
CREATE INDEX idx_appatt_org
  ON appointment_attachment (
    org_id_organization
  )
/

PROMPT ALTER TABLE appointment_attachment ADD CONSTRAINT pk_appt_attachment PRIMARY KEY
ALTER TABLE appointment_attachment
  ADD CONSTRAINT pk_appt_attachment PRIMARY KEY (
    id_attachment
  )
/

PROMPT ALTER TABLE appointment_attachment ADD CONSTRAINT chk_appatt_size CHECK
ALTER TABLE appointment_attachment
  ADD CONSTRAINT chk_appatt_size CHECK (
    size_bytes >= 0
  )
/

PROMPT ALTER TABLE appointment_attachment ADD CONSTRAINT fk_appatt_appointment FOREIGN KEY
ALTER TABLE appointment_attachment
  ADD CONSTRAINT fk_appatt_appointment FOREIGN KEY (
    app_id_appointment
  ) REFERENCES appointment (
    id_appointment
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE appointment_attachment ADD CONSTRAINT fk_appatt_organization FOREIGN KEY
ALTER TABLE appointment_attachment
  ADD CONSTRAINT fk_appatt_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

COMMENT ON TABLE appointment_attachment IS 'Archivos adjuntos por cita (historial). Feature Premium APPOINTMENT_HISTORY. size_bytes suma al storage_used_bytes de la org (paywall).';
COMMENT ON COLUMN appointment_attachment.storage_url IS 'URL completa del objeto en el bucket OCI.';
COMMENT ON COLUMN appointment_attachment.size_bytes IS 'Tamano del archivo en bytes; se descuenta del limite de storage de la org.';
