PROMPT CREATE TABLE appointment_session_record
CREATE TABLE appointment_session_record (
  id_session_record   NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  app_id_appointment  NUMBER                      NOT NULL,
  org_id_organization NUMBER                      NOT NULL,
  notes               CLOB                        NULL,
  created_by_user     NUMBER                      NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE appointment_session_record ADD CONSTRAINT pk_appt_session_record PRIMARY KEY
ALTER TABLE appointment_session_record
  ADD CONSTRAINT pk_appt_session_record PRIMARY KEY (
    id_session_record
  )
/

PROMPT ALTER TABLE appointment_session_record ADD CONSTRAINT uq_appt_session_record UNIQUE
ALTER TABLE appointment_session_record
  ADD CONSTRAINT uq_appt_session_record UNIQUE (
    app_id_appointment
  )
/

PROMPT ALTER TABLE appointment_session_record ADD CONSTRAINT fk_asr_appointment FOREIGN KEY
ALTER TABLE appointment_session_record
  ADD CONSTRAINT fk_asr_appointment FOREIGN KEY (
    app_id_appointment
  ) REFERENCES appointment (
    id_appointment
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE appointment_session_record ADD CONSTRAINT fk_asr_organization FOREIGN KEY
ALTER TABLE appointment_session_record
  ADD CONSTRAINT fk_asr_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

COMMENT ON TABLE appointment_session_record IS 'Historial (notas) por cita. Feature Premium APPOINTMENT_HISTORY. Se crea al pasar la cita a COMPLETADO (misma transaccion). 1:1 con appointment.';
COMMENT ON COLUMN appointment_session_record.notes IS 'Notas de la sesion registradas al completar la cita.';
COMMENT ON COLUMN appointment_session_record.created_by_user IS 'Usuario (JWT) que registro el historial.';
