PROMPT CREATE TABLE appointment
CREATE TABLE appointment (
  id_appointment      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  loc_id_location     NUMBER                      NOT NULL,
  pro_id_professional NUMBER                      NOT NULL,
  ser_id_service      NUMBER                      NOT NULL,
  start_time          TIMESTAMP(6)                NOT NULL,
  end_time            TIMESTAMP(6)                NOT NULL,
  status              VARCHAR2(20)                DEFAULT 'CONFIRMADO' NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  cus_id_customer     NUMBER                      NOT NULL,
  public_manage_token VARCHAR2(64)                NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  attendance_status   VARCHAR2(20)                DEFAULT 'NOT_REQUESTED' NOT NULL,
  attendance_sent_at  TIMESTAMP(6) WITH TIME ZONE NULL,
  attendance_due_at   TIMESTAMP(6) WITH TIME ZONE NULL,
  attendance_reply_at TIMESTAMP(6) WITH TIME ZONE NULL,
  cancel_reason       VARCHAR2(100)               NULL,
  policy_code_snapshot VARCHAR2(20)               NULL,
  policy_accepted_at  TIMESTAMP(6) WITH TIME ZONE NULL,
  refund_status       VARCHAR2(20)                DEFAULT 'NONE' NOT NULL,
  refund_amount       NUMBER                      NULL,
  refund_alias        VARCHAR2(100)               NULL,
  refund_requested_at TIMESTAMP(6) WITH TIME ZONE NULL,
  refund_alias_submitted_at TIMESTAMP(6) WITH TIME ZONE NULL,
  refund_sent_at      TIMESTAMP(6) WITH TIME ZONE NULL,
  refund_marked_by    NUMBER                      NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_app_attendance_due
CREATE INDEX idx_app_attendance_due
  ON appointment (
    attendance_status,
    SYS_EXTRACT_UTC("ATTENDANCE_DUE_AT")
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_app_org
CREATE INDEX idx_app_org
  ON appointment (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_app_pro_time
CREATE INDEX idx_app_pro_time
  ON appointment (
    pro_id_professional,
    start_time
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_app_public_token
CREATE UNIQUE INDEX idx_app_public_token
  ON appointment (
    public_manage_token
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT chk_app_attendance_status CHECK
ALTER TABLE appointment
  ADD CONSTRAINT chk_app_attendance_status CHECK (
    attendance_status IN ('NOT_REQUESTED', 'SENT', 'CONFIRMED', 'DECLINED', 'EXPIRED')
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT chk_app_status CHECK
ALTER TABLE appointment
  ADD CONSTRAINT chk_app_status CHECK (
    status IN ('PENDIENTE', 'CONFIRMADO', 'COMPLETADO', 'CANCELADO')
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT chk_app_policy_snapshot CHECK
ALTER TABLE appointment
  ADD CONSTRAINT chk_app_policy_snapshot CHECK (
    policy_code_snapshot IS NULL
    OR policy_code_snapshot IN ('FLEXIBLE', 'MODERATE', 'STRICT')
  )
/

COMMENT ON COLUMN appointment.policy_code_snapshot IS
  'Politica de reembolso vigente al reservar con seña (FLEXIBLE|MODERATE|STRICT).';
/

COMMENT ON COLUMN appointment.policy_accepted_at IS
  'Momento en que el cliente acepto la politica en la reserva publica.';
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT chk_app_refund_status CHECK
ALTER TABLE appointment
  ADD CONSTRAINT chk_app_refund_status CHECK (
    refund_status IN (
      'NONE',
      'NOT_APPLICABLE',
      'AWAITING_ALIAS',
      'PENDING',
      'SENT',
      'WAIVED'
    )
  )
/

COMMENT ON COLUMN appointment.refund_status IS
  'Ciclo de reembolso de seña: NONE|NOT_APPLICABLE|AWAITING_ALIAS|PENDING|SENT|WAIVED.';
/

COMMENT ON COLUMN appointment.refund_amount IS
  'Monto a reembolsar (Gs).';
/

COMMENT ON COLUMN appointment.refund_alias IS
  'Alias SIPAP del cliente para recibir el reembolso.';
/

PROMPT CREATE INDEX idx_app_org_refund_status
CREATE INDEX idx_app_org_refund_status
  ON appointment (
    org_id_organization,
    refund_status
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT pk_appointment PRIMARY KEY
ALTER TABLE appointment
  ADD CONSTRAINT pk_appointment PRIMARY KEY (
    id_appointment
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT fk_app_customer FOREIGN KEY
ALTER TABLE appointment
  ADD CONSTRAINT fk_app_customer FOREIGN KEY (
    cus_id_customer
  ) REFERENCES customer (
    id_customer
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT fk_app_location FOREIGN KEY
ALTER TABLE appointment
  ADD CONSTRAINT fk_app_location FOREIGN KEY (
    loc_id_location
  ) REFERENCES location (
    id_location
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT fk_app_organization FOREIGN KEY
ALTER TABLE appointment
  ADD CONSTRAINT fk_app_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT fk_app_professional FOREIGN KEY
ALTER TABLE appointment
  ADD CONSTRAINT fk_app_professional FOREIGN KEY (
    pro_id_professional
  ) REFERENCES professional (
    id_professional
  )
/

PROMPT ALTER TABLE appointment ADD CONSTRAINT fk_app_service FOREIGN KEY
ALTER TABLE appointment
  ADD CONSTRAINT fk_app_service FOREIGN KEY (
    ser_id_service
  ) REFERENCES service (
    id_service
  )
/


