PROMPT CREATE TABLE atc_kb_document
CREATE TABLE atc_kb_document (
  id_document    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  file_name      VARCHAR2(255)               NOT NULL,
  mime_type      VARCHAR2(150)               NOT NULL,
  size_bytes     NUMBER                      DEFAULT 0 NOT NULL,
  storage_url    VARCHAR2(1000)              NOT NULL,
  object_key     VARCHAR2(500)               NOT NULL,
  extracted_text CLOB,
  status         VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  error_message  VARCHAR2(4000),
  created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE atc_kb_document ADD CONSTRAINT pk_atc_kb_document PRIMARY KEY
ALTER TABLE atc_kb_document
  ADD CONSTRAINT pk_atc_kb_document PRIMARY KEY (id_document)
/

PROMPT ALTER TABLE atc_kb_document ADD CONSTRAINT chk_atc_kb_doc_status CHECK
ALTER TABLE atc_kb_document
  ADD CONSTRAINT chk_atc_kb_doc_status CHECK (
    status IN ('PENDING', 'PROCESSING', 'READY', 'ERROR')
  )
/

PROMPT ALTER TABLE atc_kb_document ADD CONSTRAINT chk_atc_kb_doc_size CHECK
ALTER TABLE atc_kb_document
  ADD CONSTRAINT chk_atc_kb_doc_size CHECK (size_bytes >= 0)
/

PROMPT CREATE INDEX idx_atc_kb_doc_status
CREATE INDEX idx_atc_kb_doc_status
  ON atc_kb_document (status)
/
