PROMPT CREATE TABLE atc_kb_chunk
CREATE TABLE atc_kb_chunk (
  id_chunk         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  doc_id_document  NUMBER                      NOT NULL,
  chunk_index      NUMBER                      NOT NULL,
  chunk_text       CLOB                        NOT NULL,
  embedding        VECTOR(1536, FLOAT32)       NOT NULL,
  updated_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE atc_kb_chunk ADD CONSTRAINT pk_atc_kb_chunk PRIMARY KEY
ALTER TABLE atc_kb_chunk
  ADD CONSTRAINT pk_atc_kb_chunk PRIMARY KEY (id_chunk)
/

PROMPT ALTER TABLE atc_kb_chunk ADD CONSTRAINT fk_atc_kb_chunk_doc FOREIGN KEY
ALTER TABLE atc_kb_chunk
  ADD CONSTRAINT fk_atc_kb_chunk_doc FOREIGN KEY (doc_id_document)
  REFERENCES atc_kb_document (id_document)
  ON DELETE CASCADE
/

PROMPT ALTER TABLE atc_kb_chunk ADD CONSTRAINT uq_atc_kb_chunk_doc_idx UNIQUE
ALTER TABLE atc_kb_chunk
  ADD CONSTRAINT uq_atc_kb_chunk_doc_idx UNIQUE (doc_id_document, chunk_index)
/

PROMPT CREATE INDEX idx_atc_kb_chunk_doc
CREATE INDEX idx_atc_kb_chunk_doc
  ON atc_kb_chunk (doc_id_document)
/
