PROMPT CREATE TABLE capability
CREATE TABLE capability (
  id_capability          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  code                   VARCHAR2(80)                NOT NULL,
  group_code             VARCHAR2(40)                NOT NULL,
  group_label            VARCHAR2(80)                NOT NULL,
  label                  VARCHAR2(120)               NOT NULL,
  description            VARCHAR2(400)               NULL,
  kind                   VARCHAR2(20)                DEFAULT 'ACTION' NOT NULL,
  sort_order             NUMBER                      DEFAULT 0 NOT NULL,
  requires_entitlement   VARCHAR2(80)                NULL,
  is_locked              NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  is_active              NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE capability ADD CONSTRAINT pk_capability PRIMARY KEY
ALTER TABLE capability
  ADD CONSTRAINT pk_capability PRIMARY KEY (
    id_capability
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE capability ADD CONSTRAINT uq_capability_code UNIQUE
ALTER TABLE capability
  ADD CONSTRAINT uq_capability_code UNIQUE (
    code
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE capability ADD CONSTRAINT chk_capability_kind CHECK
ALTER TABLE capability
  ADD CONSTRAINT chk_capability_kind CHECK (
    kind IN ('MENU', 'ACTION', 'ADDON')
  )
/

PROMPT ALTER TABLE capability ADD CONSTRAINT chk_capability_active CHECK
ALTER TABLE capability
  ADD CONSTRAINT chk_capability_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE capability ADD CONSTRAINT chk_capability_locked CHECK
ALTER TABLE capability
  ADD CONSTRAINT chk_capability_locked CHECK (
    is_locked IN (0, 1)
  )
/

COMMENT ON TABLE capability IS 'Catalogo de capabilities del panel Hasel (menu, acciones y addons).';
/
COMMENT ON COLUMN capability.requires_entitlement IS 'Feature/addon de org requerido ademas del grant de rol. NULL = sin gate de entitlement.';
/
