PROMPT CREATE TABLE cities
CREATE TABLE cities (
  id_city           NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  dep_id_department NUMBER        NULL,
  dnit_code         NUMBER(5,0)   NOT NULL,
  description       VARCHAR2(150) NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE cities ADD PRIMARY KEY
ALTER TABLE cities
  ADD PRIMARY KEY (
    id_city
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE cities ADD FOREIGN KEY
ALTER TABLE cities
  ADD FOREIGN KEY (
    dep_id_department
  ) REFERENCES departments (
    id_department
  )
/


