PROMPT CREATE TABLE customer_phone_audit
CREATE TABLE customer_phone_audit (
  id_audit              NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  cus_id_customer       NUMBER                      NOT NULL,
  org_id_organization   NUMBER                      NOT NULL,
  full_name             VARCHAR2(150)               NULL,
  phone_number          VARCHAR2(40)                NULL,
  issue_code            VARCHAR2(40)                NOT NULL,
  audited_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE customer_phone_audit ADD CONSTRAINT pk_customer_phone_audit PRIMARY KEY
ALTER TABLE customer_phone_audit
  ADD CONSTRAINT pk_customer_phone_audit PRIMARY KEY (id_audit)
/

PROMPT CREATE INDEX idx_customer_phone_audit_org
CREATE INDEX idx_customer_phone_audit_org
  ON customer_phone_audit (org_id_organization, issue_code)
/

COMMENT ON TABLE customer_phone_audit IS
  'Snapshot de clientes historicos sin telefono +5959XXXXXXXX. No se declara NOT NULL en customer hasta backfill humano.';
/
