PROMPT CREATE TABLE customer_odontogram_event
CREATE TABLE customer_odontogram_event (
  id_event            NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  cus_id_customer     NUMBER                      NOT NULL,
  tooth_fdi           NUMBER(2,0)                 NOT NULL,
  face_occlusal       NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  face_vestibular     NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  face_palatal        NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  face_mesial         NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  face_distal         NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  finding_code        VARCHAR2(40)                NOT NULL,
  clinical_phase      VARCHAR2(20)                DEFAULT 'FINDING' NOT NULL,
  notes               VARCHAR2(2000)              NULL,
  created_by_user     NUMBER                      NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at          TIMESTAMP(6) WITH TIME ZONE NULL,
  deleted_by_user     NUMBER                      NULL
)
/

PROMPT CREATE INDEX idx_odoevt_org_cus ON customer_odontogram_event (org_id_organization, cus_id_customer, deleted_at, created_at)
CREATE INDEX idx_odoevt_org_cus
  ON customer_odontogram_event (
    org_id_organization,
    cus_id_customer,
    deleted_at,
    created_at
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT pk_customer_odontogram_event PRIMARY KEY
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT pk_customer_odontogram_event PRIMARY KEY (
    id_event
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT chk_odoevt_tooth CHECK
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT chk_odoevt_tooth CHECK (
    TRUNC(tooth_fdi / 10) IN (1, 2, 3, 4)
    AND MOD(tooth_fdi, 10) BETWEEN 1 AND 8
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT fk_odoevt_finding FOREIGN KEY
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT fk_odoevt_finding FOREIGN KEY (
    finding_code
  ) REFERENCES ref_odontogram_finding (
    finding_code
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT chk_odoevt_clinical_phase CHECK
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT chk_odoevt_clinical_phase CHECK (
    clinical_phase IN ('FINDING', 'PREEXISTING', 'PLAN')
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT chk_odoevt_faces CHECK
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT chk_odoevt_faces CHECK (
    face_occlusal IN (0, 1)
    AND face_vestibular IN (0, 1)
    AND face_palatal IN (0, 1)
    AND face_mesial IN (0, 1)
    AND face_distal IN (0, 1)
  )
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT fk_odoevt_org FOREIGN KEY
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT fk_odoevt_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE customer_odontogram_event ADD CONSTRAINT fk_odoevt_customer FOREIGN KEY
ALTER TABLE customer_odontogram_event
  ADD CONSTRAINT fk_odoevt_customer FOREIGN KEY (
    cus_id_customer
  ) REFERENCES customer (
    id_customer
  ) ON DELETE CASCADE
/

COMMENT ON TABLE customer_odontogram_event IS 'Bitacora clinica del odontograma (aislada del historial de citas). El estado vivo se deriva del ultimo evento por pieza.';
COMMENT ON COLUMN customer_odontogram_event.tooth_fdi IS 'Notacion FDI adulto: 11-18, 21-28, 31-38, 41-48.';
COMMENT ON COLUMN customer_odontogram_event.face_palatal IS 'Cara palatina (superior) o lingual (inferior).';
COMMENT ON COLUMN customer_odontogram_event.clinical_phase IS 'Fase clinica: FINDING, PREEXISTING o PLAN.';
COMMENT ON COLUMN customer_odontogram_event.created_by_user IS 'platform_user_id del JWT que registro el hallazgo.';
COMMENT ON COLUMN customer_odontogram_event.deleted_at IS 'Soft delete. NULL = activo. Nunca se borra la fila.';
COMMENT ON COLUMN customer_odontogram_event.deleted_by_user IS 'platform_user_id del JWT que anulo el hallazgo.';
