PROMPT CREATE TABLE customer
CREATE TABLE customer (
  id_customer         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  full_name           VARCHAR2(150)               NOT NULL,
  phone_number        VARCHAR2(20)                NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT pk_customer PRIMARY KEY
ALTER TABLE customer
  ADD CONSTRAINT pk_customer PRIMARY KEY (
    id_customer
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT uq_customer_phone UNIQUE
ALTER TABLE customer
  ADD CONSTRAINT uq_customer_phone UNIQUE (
    org_id_organization,
    phone_number
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT fk_customer_org FOREIGN KEY
ALTER TABLE customer
  ADD CONSTRAINT fk_customer_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  )
/


