PROMPT CREATE TABLE customer
CREATE TABLE customer (
  id_customer         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  full_name           VARCHAR2(150)               NOT NULL,
  first_name          VARCHAR2(80),
  last_name           VARCHAR2(80),
  document_number     VARCHAR2(20),
  email               VARCHAR2(150),
  phone_number        VARCHAR2(20),
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT pk_customer PRIMARY KEY
ALTER TABLE customer
  ADD CONSTRAINT pk_customer PRIMARY KEY (
    id_customer
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT uq_customer_phone UNIQUE
ALTER TABLE customer
  ADD CONSTRAINT uq_customer_phone UNIQUE (
    org_id_organization,
    phone_number
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT CREATE UNIQUE INDEX uq_customer_document
-- Unico por org solo cuando hay CI: varios NULL no chocan (a diferencia de UNIQUE constraint).
CREATE UNIQUE INDEX uq_customer_document
  ON customer (
    CASE WHEN document_number IS NOT NULL THEN org_id_organization END,
    document_number
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE UNIQUE INDEX uq_customer_email
CREATE UNIQUE INDEX uq_customer_email
  ON customer (
    CASE WHEN email IS NOT NULL THEN org_id_organization END,
    email
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE customer ADD CONSTRAINT fk_customer_org FOREIGN KEY
ALTER TABLE customer
  ADD CONSTRAINT fk_customer_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  )
/

COMMENT ON COLUMN customer.first_name IS 'Nombre de pila. Nullable: citas y reserva publica pueden seguir insertando solo full_name.';
COMMENT ON COLUMN customer.last_name IS 'Apellido. Nullable por el mismo motivo que first_name.';
COMMENT ON COLUMN customer.document_number IS 'CI paraguaya, solo digitos (5-8). Unica por organizacion cuando no es NULL.';
COMMENT ON COLUMN customer.email IS 'Correo en minusculas. Unico por organizacion cuando no es NULL.';
COMMENT ON COLUMN customer.full_name IS 'Nombre visible. En alta/edicion del panel se arma como TRIM(first_name || '' '' || last_name).';
