PROMPT CREATE TABLE customer_body_snapshot
CREATE TABLE customer_body_snapshot (
  id_body_snapshot    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  cus_id_customer     NUMBER                      NOT NULL,
  app_id_appointment  NUMBER                      NOT NULL,
  silhouette          VARCHAR2(10)                DEFAULT 'NEUTRAL' NOT NULL,
  snapshot_json       CLOB                        NOT NULL,
  captured_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by_user     NUMBER                      NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE UNIQUE INDEX uq_body_snap_org_appt ON customer_body_snapshot (org_id_organization, app_id_appointment)
CREATE UNIQUE INDEX uq_body_snap_org_appt
  ON customer_body_snapshot (
    org_id_organization,
    app_id_appointment
  )
/

PROMPT CREATE INDEX idx_body_snap_org_cus ON customer_body_snapshot (org_id_organization, cus_id_customer, captured_at)
CREATE INDEX idx_body_snap_org_cus
  ON customer_body_snapshot (
    org_id_organization,
    cus_id_customer,
    captured_at
  )
/

PROMPT ALTER TABLE customer_body_snapshot ADD CONSTRAINT pk_customer_body_snapshot PRIMARY KEY
ALTER TABLE customer_body_snapshot
  ADD CONSTRAINT pk_customer_body_snapshot PRIMARY KEY (
    id_body_snapshot
  )
/

PROMPT ALTER TABLE customer_body_snapshot ADD CONSTRAINT chk_body_snap_silhouette CHECK
ALTER TABLE customer_body_snapshot
  ADD CONSTRAINT chk_body_snap_silhouette CHECK (
    silhouette IN ('NEUTRAL', 'FEMALE', 'MALE', 'CHILD')
  )
/

PROMPT ALTER TABLE customer_body_snapshot ADD CONSTRAINT fk_body_snap_customer FOREIGN KEY
ALTER TABLE customer_body_snapshot
  ADD CONSTRAINT fk_body_snap_customer FOREIGN KEY (
    cus_id_customer
  ) REFERENCES customer (
    id_customer
  )
/

PROMPT ALTER TABLE customer_body_snapshot ADD CONSTRAINT fk_body_snap_appointment FOREIGN KEY
ALTER TABLE customer_body_snapshot
  ADD CONSTRAINT fk_body_snap_appointment FOREIGN KEY (
    app_id_appointment
  ) REFERENCES appointment (
    id_appointment
  )
/

COMMENT ON TABLE customer_body_snapshot IS 'Snapshot de mapa corporal por cita (1 fila org+cita). JSON alineado a BodySessionSnapshot TS.';
COMMENT ON COLUMN customer_body_snapshot.snapshot_json IS 'Marcas, juntas y metadatos de sesión (contrato frontend/OR DS futuro).';
