PROMPT CREATE TABLE departments
CREATE TABLE departments (
  id_department NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  dnit_code     NUMBER(3,0)   NOT NULL,
  description   VARCHAR2(100) NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE departments ADD PRIMARY KEY
ALTER TABLE departments
  ADD PRIMARY KEY (
    id_department
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


