PROMPT CREATE TABLE embedding_sync_outbox
CREATE TABLE embedding_sync_outbox (
  id_outbox           NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization  NUMBER                      NOT NULL,
  entity_type          VARCHAR2(30)                NOT NULL,
  entity_id            NUMBER                      NOT NULL,
  action               VARCHAR2(10)                NOT NULL,
  status               VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  attempts             NUMBER                      DEFAULT 0 NOT NULL,
  error_message        VARCHAR2(4000)              NULL,
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at         TIMESTAMP(6) WITH TIME ZONE NULL
)
/

PROMPT ALTER TABLE embedding_sync_outbox ADD CONSTRAINT pk_embedding_sync_outbox PRIMARY KEY
ALTER TABLE embedding_sync_outbox
  ADD CONSTRAINT pk_embedding_sync_outbox PRIMARY KEY (id_outbox)
/

PROMPT ALTER TABLE embedding_sync_outbox ADD CONSTRAINT chk_embedding_outbox_action CHECK
ALTER TABLE embedding_sync_outbox
  ADD CONSTRAINT chk_embedding_outbox_action CHECK (action IN ('SYNC', 'DELETE'))
/

PROMPT ALTER TABLE embedding_sync_outbox ADD CONSTRAINT chk_embedding_outbox_status CHECK
ALTER TABLE embedding_sync_outbox
  ADD CONSTRAINT chk_embedding_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED'))
/

PROMPT CREATE INDEX idx_embedding_outbox_pending ON embedding_sync_outbox
CREATE INDEX idx_embedding_outbox_pending
  ON embedding_sync_outbox (status, created_at)
/

COMMENT ON TABLE embedding_sync_outbox IS 'Outbox transaccional: los triggers de customer/professional/service/location insertan aqui en vez de llamar a Azure OpenAI de forma sincrona. Un job DBMS_SCHEDULER (PKG_AOX_VECTOR_SEARCH.PR_PROCESS_EMBEDDING_OUTBOX) procesa la cola con FOR UPDATE SKIP LOCKED.';
/
