PROMPT CREATE TABLE location_closure
CREATE TABLE location_closure (
  id_location_closure NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  loc_id_location     NUMBER                      NOT NULL,
  name                VARCHAR2(120)               NOT NULL,
  start_date          DATE                        NOT NULL,
  end_date            DATE                        NOT NULL,
  is_full_day         NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  start_time          VARCHAR2(5)                 NULL,
  end_time            VARCHAR2(5)                 NULL,
  closure_group_id    RAW(16)                     NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by          NUMBER                      NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_closure_lookup
CREATE INDEX idx_loc_closure_lookup
  ON location_closure (
    loc_id_location,
    start_date,
    end_date
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_closure_org
CREATE INDEX idx_loc_closure_org
  ON location_closure (
    org_id_organization,
    start_date
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_closure_group
CREATE INDEX idx_loc_closure_group
  ON location_closure (
    closure_group_id
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT pk_location_closure PRIMARY KEY
ALTER TABLE location_closure
  ADD CONSTRAINT pk_location_closure PRIMARY KEY (
    id_location_closure
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT fk_lclosure_org FOREIGN KEY
ALTER TABLE location_closure
  ADD CONSTRAINT fk_lclosure_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT fk_lclosure_location FOREIGN KEY
ALTER TABLE location_closure
  ADD CONSTRAINT fk_lclosure_location FOREIGN KEY (
    loc_id_location
  ) REFERENCES location (
    id_location
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT chk_lclosure_dates CHECK
ALTER TABLE location_closure
  ADD CONSTRAINT chk_lclosure_dates CHECK (
    end_date >= start_date
  )
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT chk_lclosure_full_day CHECK
ALTER TABLE location_closure
  ADD CONSTRAINT chk_lclosure_full_day CHECK (
    is_full_day IN (0, 1)
  )
/

PROMPT ALTER TABLE location_closure ADD CONSTRAINT chk_lclosure_times CHECK
ALTER TABLE location_closure
  ADD CONSTRAINT chk_lclosure_times CHECK (
    (is_full_day = 1 AND start_time IS NULL AND end_time IS NULL)
    OR
    (is_full_day = 0
      AND start_time IS NOT NULL AND end_time IS NOT NULL
      AND REGEXP_LIKE(start_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
      AND REGEXP_LIKE(end_time,   '^([01][0-9]|2[0-3]):[0-5][0-9]$')
      AND start_time < end_time)
  )
/
