PROMPT CREATE TABLE location
CREATE TABLE location (
  id_location         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  name                VARCHAR2(100)               NOT NULL,
  address             VARCHAR2(255)               NOT NULL,
  cit_id_city         NUMBER                      NOT NULL,
  latitude            NUMBER(12,8)                NULL,
  longitude           NUMBER(12,8)                NULL,
  is_active           NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  dep_id_department   NUMBER                      NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_city
CREATE INDEX idx_loc_city
  ON location (
    cit_id_city
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_dept
CREATE INDEX idx_loc_dept
  ON location (
    dep_id_department
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_loc_org
CREATE INDEX idx_loc_org
  ON location (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE location ADD CONSTRAINT chk_loc_active CHECK
ALTER TABLE location
  ADD CONSTRAINT chk_loc_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE location ADD CONSTRAINT pk_location PRIMARY KEY
ALTER TABLE location
  ADD CONSTRAINT pk_location PRIMARY KEY (
    id_location
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE location ADD CONSTRAINT fk_loc_city FOREIGN KEY
ALTER TABLE location
  ADD CONSTRAINT fk_loc_city FOREIGN KEY (
    cit_id_city
  ) REFERENCES cities (
    id_city
  )
/

PROMPT ALTER TABLE location ADD CONSTRAINT fk_loc_department FOREIGN KEY
ALTER TABLE location
  ADD CONSTRAINT fk_loc_department FOREIGN KEY (
    dep_id_department
  ) REFERENCES departments (
    id_department
  )
/

PROMPT ALTER TABLE location ADD CONSTRAINT fk_loc_organization FOREIGN KEY
ALTER TABLE location
  ADD CONSTRAINT fk_loc_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/


