PROMPT CREATE TABLE org_refund_enforcement_audit
CREATE TABLE org_refund_enforcement_audit (
  id_enforcement_audit NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization  NUMBER                      NOT NULL,
  dispute_id           NUMBER                      NULL,
  from_level           VARCHAR2(30)                NOT NULL,
  to_level             VARCHAR2(30)                NOT NULL,
  reason               VARCHAR2(400)               NOT NULL,
  actor_user_id        NUMBER                      NULL,
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE org_refund_enforcement_audit ADD CONSTRAINT pk_org_refund_enf_audit PRIMARY KEY
ALTER TABLE org_refund_enforcement_audit
  ADD CONSTRAINT pk_org_refund_enf_audit PRIMARY KEY (id_enforcement_audit)
/

PROMPT CREATE INDEX idx_refund_enf_audit_org
CREATE INDEX idx_refund_enf_audit_org
  ON org_refund_enforcement_audit (org_id_organization, created_at)
/

PROMPT ALTER TABLE org_refund_enforcement_audit ADD CONSTRAINT fk_refund_enf_audit_org FOREIGN KEY
ALTER TABLE org_refund_enforcement_audit
  ADD CONSTRAINT fk_refund_enf_audit_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

COMMENT ON TABLE org_refund_enforcement_audit IS
  'Historial de escaladas y levantamientos de sanciones operativas de reembolso. Solo Operaciones Hasel restaura.';
/
