PROMPT CREATE TABLE org_addon
CREATE TABLE org_addon (
  id_org_addon           NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization    NUMBER                      NOT NULL,
  rad_id_addon           NUMBER                      NOT NULL,
  status                 VARCHAR2(20)                DEFAULT 'ACTIVE' NOT NULL,
  grant_type             VARCHAR2(20)                DEFAULT 'PREVIEW' NOT NULL,
  price_snapshot_amount  NUMBER                      DEFAULT 0 NOT NULL,
  currency               VARCHAR2(3)                 DEFAULT 'PYG' NOT NULL,
  started_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  canceled_at            TIMESTAMP(6) WITH TIME ZONE NULL,
  billing_started_at     TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgaddon_org ON org_addon (org_id_organization)
CREATE INDEX idx_orgaddon_org
  ON org_addon (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT pk_org_addon PRIMARY KEY
ALTER TABLE org_addon
  ADD CONSTRAINT pk_org_addon PRIMARY KEY (
    id_org_addon
  )
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT uq_org_addon_org_addon UNIQUE
ALTER TABLE org_addon
  ADD CONSTRAINT uq_org_addon_org_addon UNIQUE (
    org_id_organization,
    rad_id_addon
  )
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT chk_orgaddon_status CHECK
ALTER TABLE org_addon
  ADD CONSTRAINT chk_orgaddon_status CHECK (
    status IN ('ACTIVE', 'CANCELED', 'EXPIRED')
  )
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT chk_orgaddon_grant CHECK
ALTER TABLE org_addon
  ADD CONSTRAINT chk_orgaddon_grant CHECK (
    grant_type IN ('PREVIEW', 'PAID')
  )
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT fk_orgaddon_org FOREIGN KEY
ALTER TABLE org_addon
  ADD CONSTRAINT fk_orgaddon_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_addon ADD CONSTRAINT fk_orgaddon_addon FOREIGN KEY
ALTER TABLE org_addon
  ADD CONSTRAINT fk_orgaddon_addon FOREIGN KEY (
    rad_id_addon
  ) REFERENCES ref_addon (
    id_addon
  )
/

COMMENT ON TABLE org_addon IS 'Complemento contratado por organizacion (1 fila por org+addon). PREVIEW no es billable; PAID se usara cuando ADDONS_BILLING_LIVE=1.';
COMMENT ON COLUMN org_addon.grant_type IS 'PREVIEW=activacion gratuita (kill-switch off). PAID=cobrado (fase posterior).';
COMMENT ON COLUMN org_addon.price_snapshot_amount IS 'Precio de lista al activar. No implica cobro en PREVIEW.';
COMMENT ON COLUMN org_addon.billing_started_at IS 'Inicio del periodo cobrado. NULL mientras grant_type=PREVIEW.';
