PROMPT CREATE TABLE org_billing_profile
CREATE TABLE org_billing_profile (
  id_billing_profile  NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  billing_name        VARCHAR2(200)               NULL,
  billing_doc_type    VARCHAR2(10)                NULL,
  billing_doc_number  VARCHAR2(40)                NULL,
  billing_email       VARCHAR2(255)               NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by_user     NUMBER                      NULL
)
/

PROMPT ALTER TABLE org_billing_profile ADD CONSTRAINT pk_org_billing_profile PRIMARY KEY
ALTER TABLE org_billing_profile
  ADD CONSTRAINT pk_org_billing_profile PRIMARY KEY (
    id_billing_profile
  )
/

PROMPT ALTER TABLE org_billing_profile ADD CONSTRAINT uq_org_billing_profile_org UNIQUE
ALTER TABLE org_billing_profile
  ADD CONSTRAINT uq_org_billing_profile_org UNIQUE (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_billing_profile ADD CONSTRAINT fk_org_billprof_org FOREIGN KEY
ALTER TABLE org_billing_profile
  ADD CONSTRAINT fk_org_billprof_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_billing_profile ADD CONSTRAINT chk_org_billprof_doc_type CHECK
ALTER TABLE org_billing_profile
  ADD CONSTRAINT chk_org_billprof_doc_type CHECK (
    billing_doc_type IS NULL
    OR billing_doc_type IN ('CI', 'RUC')
  )
/

COMMENT ON TABLE org_billing_profile IS
  'Datos fiscales 1:1 por org para facturacion de suscripcion Hasel (independiente de SIPAP senas).';
/

COMMENT ON COLUMN org_billing_profile.billing_name IS
  'Razon social o nombre a quien se emite la factura de la suscripcion.';
/

COMMENT ON COLUMN org_billing_profile.billing_doc_type IS
  'CI | RUC. Tipo de documento fiscal del comprador.';
/

COMMENT ON COLUMN org_billing_profile.billing_doc_number IS
  'Numero de C.I. o RUC del comprador.';
/

COMMENT ON COLUMN org_billing_profile.billing_email IS
  'Email donde Hasel envia / asocia la factura de suscripcion.';
/
