PROMPT CREATE TABLE org_refund_claim
CREATE TABLE org_refund_claim (
  id_claim            NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  app_id_appointment  NUMBER                      NOT NULL,
  claim_source        VARCHAR2(20)                NOT NULL,
  claim_status        VARCHAR2(20)                DEFAULT 'OPEN' NOT NULL,
  strike_counted      NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  notes               VARCHAR2(500)               NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  resolved_at         TIMESTAMP(6) WITH TIME ZONE NULL,
  resolved_by         NUMBER                      NULL
)
/

PROMPT CREATE INDEX idx_refund_claim_org_status
CREATE INDEX idx_refund_claim_org_status
  ON org_refund_claim (org_id_organization, claim_status)
/

PROMPT CREATE UNIQUE INDEX uq_refund_claim_app_open
CREATE UNIQUE INDEX uq_refund_claim_app_open
  ON org_refund_claim (
    CASE WHEN claim_status = 'OPEN' THEN app_id_appointment END
  )
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT pk_org_refund_claim PRIMARY KEY
ALTER TABLE org_refund_claim
  ADD CONSTRAINT pk_org_refund_claim PRIMARY KEY (id_claim)
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT fk_refund_claim_org FOREIGN KEY
ALTER TABLE org_refund_claim
  ADD CONSTRAINT fk_refund_claim_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT fk_refund_claim_app FOREIGN KEY
ALTER TABLE org_refund_claim
  ADD CONSTRAINT fk_refund_claim_app FOREIGN KEY (app_id_appointment)
  REFERENCES appointment (id_appointment)
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT chk_refund_claim_source CHECK
ALTER TABLE org_refund_claim
  ADD CONSTRAINT chk_refund_claim_source CHECK (
    claim_source IN ('CUSTOMER', 'SLA_JOB')
  )
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT chk_refund_claim_status CHECK
ALTER TABLE org_refund_claim
  ADD CONSTRAINT chk_refund_claim_status CHECK (
    claim_status IN ('OPEN', 'RESOLVED', 'DISMISSED')
  )
/

PROMPT ALTER TABLE org_refund_claim ADD CONSTRAINT chk_refund_claim_strike CHECK
ALTER TABLE org_refund_claim
  ADD CONSTRAINT chk_refund_claim_strike CHECK (
    strike_counted IN (0, 1)
  )
/

COMMENT ON TABLE org_refund_claim IS
  'Reclamos de reembolso por SLA (48h habiles) o accion del cliente. Alimenta contador de 3 strikes.';
/
