PROMPT CREATE TABLE org_entity_embedding
CREATE TABLE org_entity_embedding (
  id_embedding        NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  entity_type         VARCHAR2(30)                NOT NULL,
  entity_id           NUMBER                      NOT NULL,
  source_text         VARCHAR2(1000)              NOT NULL,
  embedding           VECTOR(1536, FLOAT32)       NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_oee_org_type
CREATE INDEX idx_oee_org_type
  ON org_entity_embedding (
    org_id_organization,
    entity_type
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE org_entity_embedding ADD CONSTRAINT pk_org_entity_embedding PRIMARY KEY
ALTER TABLE org_entity_embedding
  ADD CONSTRAINT pk_org_entity_embedding PRIMARY KEY (
    id_embedding
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_entity_embedding ADD CONSTRAINT uq_org_entity_embedding UNIQUE
ALTER TABLE org_entity_embedding
  ADD CONSTRAINT uq_org_entity_embedding UNIQUE (
    org_id_organization,
    entity_type,
    entity_id
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_entity_embedding ADD CONSTRAINT fk_oee_org FOREIGN KEY
ALTER TABLE org_entity_embedding
  ADD CONSTRAINT fk_oee_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  )
/

PROMPT ALTER TABLE org_entity_embedding ADD CONSTRAINT chk_oee_entity_type CHECK
ALTER TABLE org_entity_embedding
  ADD CONSTRAINT chk_oee_entity_type CHECK (
    entity_type IN ('CUSTOMER', 'PROFESSIONAL', 'SERVICE', 'LOCATION')
  )
/

