PROMPT CREATE TABLE org_gallery_image
CREATE TABLE org_gallery_image (
  id_gallery_image    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  image_url           VARCHAR2(1000)              NOT NULL,
  filename            VARCHAR2(255)               NULL,
  mime_type           VARCHAR2(150)               NULL,
  sort_order          NUMBER                      DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_orggal_org_sort ON org_gallery_image (org_id_organization, sort_order)
CREATE INDEX idx_orggal_org_sort
  ON org_gallery_image (
    org_id_organization,
    sort_order
  )
/

PROMPT ALTER TABLE org_gallery_image ADD CONSTRAINT pk_org_gallery_image PRIMARY KEY
ALTER TABLE org_gallery_image
  ADD CONSTRAINT pk_org_gallery_image PRIMARY KEY (
    id_gallery_image
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_gallery_image ADD CONSTRAINT chk_orggal_sort CHECK
ALTER TABLE org_gallery_image
  ADD CONSTRAINT chk_orggal_sort CHECK (
    sort_order BETWEEN 1 AND 30
  )
/

PROMPT ALTER TABLE org_gallery_image ADD CONSTRAINT fk_orggal_organization FOREIGN KEY
ALTER TABLE org_gallery_image
  ADD CONSTRAINT fk_orggal_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/
