PROMPT CREATE TABLE org_subscription_invoice
CREATE TABLE org_subscription_invoice (
  id_invoice          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  sub_id_subscription NUMBER                      NULL,
  invoice_type        VARCHAR2(20)                DEFAULT 'SUBSCRIPTION' NOT NULL,
  pln_id_plan         NUMBER                      NULL,
  sad_id_storage_addon NUMBER                     NULL,
  description         VARCHAR2(255)               NULL,
  amount              NUMBER                      NOT NULL,
  gross_amount        NUMBER                      NULL,
  credit_applied      NUMBER                      DEFAULT 0 NOT NULL,
  currency            VARCHAR2(3)                 DEFAULT 'PYG' NOT NULL,
  status              VARCHAR2(20)                NOT NULL,
  period_start        TIMESTAMP(6) WITH TIME ZONE NULL,
  period_end          TIMESTAMP(6) WITH TIME ZONE NULL,
  due_date            TIMESTAMP(6) WITH TIME ZONE NULL,
  paid_at             TIMESTAMP(6) WITH TIME ZONE NULL,
  payment_provider    VARCHAR2(50)                NULL,
  external_reference  VARCHAR2(128)               NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  einvoice_status       VARCHAR2(20)                DEFAULT 'NONE' NOT NULL,
  einvoice_cdc          VARCHAR2(44)                NULL,
  einvoice_estado_sifen VARCHAR2(20)                NULL,
  einvoice_cod_res      VARCHAR2(10)                NULL,
  einvoice_prot_aut     VARCHAR2(30)                NULL,
  einvoice_kude_url     VARCHAR2(500)               NULL,
  einvoice_ambiente     VARCHAR2(10)                NULL,
  einvoice_sent_at      TIMESTAMP(6) WITH TIME ZONE NULL,
  einvoice_error        VARCHAR2(500)               NULL
)
/

PROMPT CREATE INDEX idx_orginv_org_created ON org_subscription_invoice (org_id_organization, created_at)
CREATE INDEX idx_orginv_org_created
  ON org_subscription_invoice (
    org_id_organization,
    created_at
  )
/

PROMPT CREATE INDEX idx_orginv_status ON org_subscription_invoice (status)
CREATE INDEX idx_orginv_status
  ON org_subscription_invoice (
    status
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT pk_org_sub_invoice PRIMARY KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT pk_org_sub_invoice PRIMARY KEY (
    id_invoice
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_type CHECK
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT chk_orginv_type CHECK (
    invoice_type IN ('SUBSCRIPTION', 'STORAGE_ADDON')
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_status CHECK
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT chk_orginv_status CHECK (
    status IN ('PENDING', 'PAID', 'FAILED', 'VOID')
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_einvoice_status CHECK
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT chk_orginv_einvoice_status CHECK (
    einvoice_status IN ('NONE', 'PENDING', 'SENT_PENDING_KUDE', 'SENT', 'FAILED')
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_org FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_sub FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_sub FOREIGN KEY (
    sub_id_subscription
  ) REFERENCES org_subscription (
    id_subscription
  ) ON DELETE SET NULL
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_plan FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_plan FOREIGN KEY (
    pln_id_plan
  ) REFERENCES ref_plan (
    id_plan
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_storage_addon FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_storage_addon FOREIGN KEY (
    sad_id_storage_addon
  ) REFERENCES ref_storage_addon (
    id_storage_addon
  )
/

COMMENT ON TABLE org_subscription_invoice IS 'Facturacion de plan y addons de storage (separado de payment_transaction, que corresponde a senas de citas).';
COMMENT ON COLUMN org_subscription_invoice.sad_id_storage_addon IS 'Addon de storage asociado (facturas STORAGE_ADDON mid-cycle / prorrateo).';
COMMENT ON COLUMN org_subscription_invoice.gross_amount IS 'Monto antes de descontar saldo a favor.';
COMMENT ON COLUMN org_subscription_invoice.credit_applied IS 'Gs de saldo a favor aplicados (se consumen al pasar a PAID).';
COMMENT ON COLUMN org_subscription_invoice.einvoice_status IS 'Ciclo de emision de Factura Electronica SIFEN: NONE (no aplica/no configurado) | PENDING (webhook enviado al firmador) | SENT_PENDING_KUDE (FE aprobada, esperando PDF) | SENT (email con KuDE enviado) | FAILED.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_cdc IS 'CDC (44 digitos) del documento emitido en el firmador esign.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_estado_sifen IS 'estado devuelto por POST /v1/documents del firmador (APROBADO | RECHAZADO | FIRMADO).';
COMMENT ON COLUMN org_subscription_invoice.einvoice_cod_res IS 'codRes SIFEN (ej. 0260 aprobado).';
COMMENT ON COLUMN org_subscription_invoice.einvoice_prot_aut IS 'Protocolo de autorizacion SIFEN.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_kude_url IS 'URL publica del KuDE (PDF) en el bucket del firmador, una vez listo.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_ambiente IS 'Ambiente SIFEN de la emision (test | prod), segun el prefijo de la api key usada.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_sent_at IS 'Cuando se envio el email de factura con el KuDE adjunto al billing_email.';
COMMENT ON COLUMN org_subscription_invoice.einvoice_error IS 'Ultimo error del ciclo de emision (SIFEN rechazado o fallo de envio de email).';
