PROMPT CREATE TABLE org_refund_dispute_compensation
CREATE TABLE org_refund_dispute_compensation (
  id_compensation       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  dispute_id            NUMBER                      NOT NULL,
  org_id_organization   NUMBER                      NOT NULL,
  app_id_appointment    NUMBER                      NOT NULL,
  cus_id_customer       NUMBER                      NOT NULL,
  amount_gs             NUMBER                      NOT NULL,
  credit_status         VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  debt_status           VARCHAR2(20)                DEFAULT 'NONE' NOT NULL,
  issued_at             TIMESTAMP(6) WITH TIME ZONE NULL,
  issued_by             NUMBER                      NULL,
  recovered_at          TIMESTAMP(6) WITH TIME ZONE NULL,
  recovered_amount_gs   NUMBER                      DEFAULT 0 NOT NULL,
  notes                 VARCHAR2(500)               NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT pk_org_refund_disp_comp PRIMARY KEY
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT pk_org_refund_disp_comp PRIMARY KEY (id_compensation)
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT uq_refund_disp_comp_dispute UNIQUE
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT uq_refund_disp_comp_dispute UNIQUE (dispute_id)
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT fk_refund_disp_comp_disp FOREIGN KEY
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT fk_refund_disp_comp_disp FOREIGN KEY (dispute_id)
  REFERENCES org_refund_dispute (id_dispute)
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT fk_refund_disp_comp_org FOREIGN KEY
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT fk_refund_disp_comp_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT chk_refund_disp_comp_credit CHECK
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT chk_refund_disp_comp_credit CHECK (
    credit_status IN ('PENDING', 'ISSUED', 'REDEEMED', 'REVERSED', 'EXPIRED')
  )
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT chk_refund_disp_comp_debt CHECK
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT chk_refund_disp_comp_debt CHECK (
    debt_status IN ('NONE', 'OPEN', 'RECOVERED', 'WAIVED')
  )
/

PROMPT ALTER TABLE org_refund_dispute_compensation ADD CONSTRAINT chk_refund_disp_comp_amt CHECK
ALTER TABLE org_refund_dispute_compensation
  ADD CONSTRAINT chk_refund_disp_comp_amt CHECK (amount_gs > 0)
/

COMMENT ON TABLE org_refund_dispute_compensation IS
  'Agregado financiero 1:1 por disputa. Gated por DISPUTE_COMPENSATION_ENABLED. No reutiliza org_billing_credit_ledger.';
/
