PROMPT CREATE TABLE org_refund_notify_outbox
CREATE TABLE org_refund_notify_outbox (
  id_outbox             NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  dispute_id            NUMBER                      NOT NULL,
  channel               VARCHAR2(20)                DEFAULT 'FCM' NOT NULL,
  event_code            VARCHAR2(40)                NOT NULL,
  dedupe_key            VARCHAR2(120)               NOT NULL,
  status                VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  attempts              NUMBER                      DEFAULT 0 NOT NULL,
  last_error            VARCHAR2(400)               NULL,
  payload               CLOB                        NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at          TIMESTAMP(6) WITH TIME ZONE NULL
)
/

PROMPT ALTER TABLE org_refund_notify_outbox ADD CONSTRAINT pk_org_refund_notify_outbox PRIMARY KEY
ALTER TABLE org_refund_notify_outbox
  ADD CONSTRAINT pk_org_refund_notify_outbox PRIMARY KEY (id_outbox)
/

PROMPT ALTER TABLE org_refund_notify_outbox ADD CONSTRAINT uq_refund_notify_dedupe UNIQUE
ALTER TABLE org_refund_notify_outbox
  ADD CONSTRAINT uq_refund_notify_dedupe UNIQUE (dedupe_key)
/

PROMPT CREATE INDEX idx_refund_notify_pending
CREATE INDEX idx_refund_notify_pending
  ON org_refund_notify_outbox (status, created_at)
/

PROMPT ALTER TABLE org_refund_notify_outbox ADD CONSTRAINT chk_refund_notify_channel CHECK
ALTER TABLE org_refund_notify_outbox
  ADD CONSTRAINT chk_refund_notify_channel CHECK (channel IN ('FCM', 'WA'))
/

PROMPT ALTER TABLE org_refund_notify_outbox ADD CONSTRAINT chk_refund_notify_status CHECK
ALTER TABLE org_refund_notify_outbox
  ADD CONSTRAINT chk_refund_notify_status CHECK (
    status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
  )
/

COMMENT ON TABLE org_refund_notify_outbox IS
  'Outbox durable de notificaciones de disputa (FCM/WA) con dedupe e intentos.';
/
