PROMPT CREATE TABLE org_payment_card
CREATE TABLE org_payment_card (
  id_payment_card       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  provider              VARCHAR2(20)                DEFAULT 'uPay' NOT NULL,
  pagopar_identificador VARCHAR2(64)                NOT NULL,
  pagopar_card_id       VARCHAR2(64)                NULL,
  brand                 VARCHAR2(40)                NULL,
  masked_number         VARCHAR2(40)                NULL,
  card_type             VARCHAR2(20)                NULL,
  issuer                VARCHAR2(120)               NULL,
  status                VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  is_default            NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  confirmed_at          TIMESTAMP(6) WITH TIME ZONE NULL,
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgcard_org_status ON org_payment_card (org_id_organization, status)
CREATE INDEX idx_orgcard_org_status
  ON org_payment_card (
    org_id_organization,
    status
  )
/

PROMPT ALTER TABLE org_payment_card ADD CONSTRAINT pk_org_payment_card PRIMARY KEY
ALTER TABLE org_payment_card
  ADD CONSTRAINT pk_org_payment_card PRIMARY KEY (
    id_payment_card
  )
/

PROMPT ALTER TABLE org_payment_card ADD CONSTRAINT chk_orgcard_status CHECK
ALTER TABLE org_payment_card
  ADD CONSTRAINT chk_orgcard_status CHECK (
    status IN ('PENDING', 'ACTIVE', 'DELETED')
  )
/

PROMPT ALTER TABLE org_payment_card ADD CONSTRAINT chk_orgcard_default CHECK
ALTER TABLE org_payment_card
  ADD CONSTRAINT chk_orgcard_default CHECK (
    is_default IN (0, 1)
  )
/

PROMPT ALTER TABLE org_payment_card ADD CONSTRAINT fk_orgcard_org FOREIGN KEY
ALTER TABLE org_payment_card
  ADD CONSTRAINT fk_orgcard_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

COMMENT ON TABLE org_payment_card IS 'Tarjetas catastradas en Pagopar (pago-recurrente/3.0, proveedor uPay) para el cobro automatico de la suscripcion Hasel.';
COMMENT ON COLUMN org_payment_card.pagopar_identificador IS 'Identificador del comprador en Pagopar (= org_id de Hasel).';
COMMENT ON COLUMN org_payment_card.pagopar_card_id IS 'Identificador numerico estable de la tarjeta (campo "tarjeta" de listar-tarjeta). El alias_token es temporal (15 min) y NO se persiste.';
COMMENT ON COLUMN org_payment_card.status IS 'PENDING (catastro iniciado), ACTIVE (confirmada), DELETED (eliminada en Pagopar).';
COMMENT ON COLUMN org_payment_card.is_default IS 'Tarjeta usada por defecto para el debito recurrente de la suscripcion.';
