PROMPT CREATE TABLE org_subscription_access_audit
CREATE TABLE org_subscription_access_audit (
  id_access_audit       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  action                VARCHAR2(20)                NOT NULL,
  reason                VARCHAR2(400)               NOT NULL,
  from_status           VARCHAR2(20)                NOT NULL,
  to_status             VARCHAR2(20)                NOT NULL,
  from_auto_renew       NUMBER(1,0)                 NULL,
  to_auto_renew         NUMBER(1,0)                 NULL,
  from_grace_ends_at    TIMESTAMP(6) WITH TIME ZONE NULL,
  to_grace_ends_at      TIMESTAMP(6) WITH TIME ZONE NULL,
  actor_employee_id     NUMBER                      NOT NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
) INITRANS 10
/

PROMPT ALTER TABLE org_subscription_access_audit ADD CONSTRAINT chk_org_sub_access_action CHECK
ALTER TABLE org_subscription_access_audit
  ADD CONSTRAINT chk_org_sub_access_action CHECK (action IN ('REVOKE', 'RESTORE'))
/

PROMPT ALTER TABLE org_subscription_access_audit ADD CONSTRAINT pk_org_sub_access_audit PRIMARY KEY
ALTER TABLE org_subscription_access_audit
  ADD CONSTRAINT pk_org_sub_access_audit PRIMARY KEY (id_access_audit)
/

PROMPT ALTER TABLE org_subscription_access_audit ADD CONSTRAINT fk_org_sub_access_org FOREIGN KEY
ALTER TABLE org_subscription_access_audit
  ADD CONSTRAINT fk_org_sub_access_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization)
/

PROMPT CREATE INDEX idx_org_sub_access_org
CREATE INDEX idx_org_sub_access_org ON org_subscription_access_audit (org_id_organization, created_at)
/

COMMENT ON TABLE org_subscription_access_audit IS
  'Auditoria de revoke/restore de acceso por ops (HASEL_ADMIN via pkg_aox_ops_admin_bridge).';
