PROMPT CREATE TABLE org_billing_credit_ledger
CREATE TABLE org_billing_credit_ledger (
  id_credit_ledger    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  delta_amount        NUMBER                      NOT NULL,
  balance_after       NUMBER                      NOT NULL,
  reason              VARCHAR2(30)                NOT NULL,
  invoice_id          NUMBER                      NULL,
  ref_code            VARCHAR2(40)                NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgbcl_org_created ON org_billing_credit_ledger (org_id_organization, created_at)
CREATE INDEX idx_orgbcl_org_created
  ON org_billing_credit_ledger (
    org_id_organization,
    created_at
  )
/

PROMPT ALTER TABLE org_billing_credit_ledger ADD CONSTRAINT pk_org_billing_credit_ledger PRIMARY KEY
ALTER TABLE org_billing_credit_ledger
  ADD CONSTRAINT pk_org_billing_credit_ledger PRIMARY KEY (
    id_credit_ledger
  )
/

PROMPT ALTER TABLE org_billing_credit_ledger ADD CONSTRAINT chk_orgbcl_reason CHECK
ALTER TABLE org_billing_credit_ledger
  ADD CONSTRAINT chk_orgbcl_reason CHECK (
    reason IN ('CANCEL_ADDON', 'APPLY_INVOICE', 'MANUAL_ADJ')
  )
/

PROMPT ALTER TABLE org_billing_credit_ledger ADD CONSTRAINT fk_orgbcl_org FOREIGN KEY
ALTER TABLE org_billing_credit_ledger
  ADD CONSTRAINT fk_orgbcl_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_billing_credit_ledger ADD CONSTRAINT fk_orgbcl_invoice FOREIGN KEY
ALTER TABLE org_billing_credit_ledger
  ADD CONSTRAINT fk_orgbcl_invoice FOREIGN KEY (
    invoice_id
  ) REFERENCES org_subscription_invoice (
    id_invoice
  ) ON DELETE SET NULL
/

COMMENT ON TABLE org_billing_credit_ledger IS 'Movimientos de saldo a favor de facturacion (credito por cancelacion de addon / aplicacion en factura).';
COMMENT ON COLUMN org_billing_credit_ledger.delta_amount IS 'Positivo = credito otorgado; negativo = credito aplicado a una factura.';
COMMENT ON COLUMN org_billing_credit_ledger.reason IS 'CANCEL_ADDON | APPLY_INVOICE | MANUAL_ADJ';
