PROMPT CREATE TABLE org_role_capability
CREATE TABLE org_role_capability (
  id_org_role_capability NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization    NUMBER                      NOT NULL,
  rol_id_role            NUMBER                      NOT NULL,
  cap_id_capability      NUMBER                      NOT NULL,
  is_granted             NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  updated_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by             NUMBER                      NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT pk_org_role_capability PRIMARY KEY
ALTER TABLE org_role_capability
  ADD CONSTRAINT pk_org_role_capability PRIMARY KEY (
    id_org_role_capability
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT uq_org_role_capability UNIQUE
ALTER TABLE org_role_capability
  ADD CONSTRAINT uq_org_role_capability UNIQUE (
    org_id_organization,
    rol_id_role,
    cap_id_capability
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT fk_orc_org FOREIGN KEY
ALTER TABLE org_role_capability
  ADD CONSTRAINT fk_orc_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT fk_orc_role FOREIGN KEY
ALTER TABLE org_role_capability
  ADD CONSTRAINT fk_orc_role FOREIGN KEY (
    rol_id_role
  ) REFERENCES role (
    id_role
  )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT fk_orc_capability FOREIGN KEY
ALTER TABLE org_role_capability
  ADD CONSTRAINT fk_orc_capability FOREIGN KEY (
    cap_id_capability
  ) REFERENCES capability (
    id_capability
  )
/

PROMPT ALTER TABLE org_role_capability ADD CONSTRAINT chk_orc_granted CHECK
ALTER TABLE org_role_capability
  ADD CONSTRAINT chk_orc_granted CHECK (
    is_granted IN (0, 1)
  )
/

PROMPT CREATE INDEX idx_orc_org_role
CREATE INDEX idx_orc_org_role
  ON org_role_capability (
    org_id_organization,
    rol_id_role
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

COMMENT ON TABLE org_role_capability IS 'Overrides de capabilities por organizacion x rol. v1: no hay override por membership_id.';
/
