PROMPT CREATE TABLE org_refund_dispute_ledger
CREATE TABLE org_refund_dispute_ledger (
  id_ledger_entry       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  dispute_id            NUMBER                      NOT NULL,
  compensation_id       NUMBER                      NOT NULL,
  event_type            VARCHAR2(40)                NOT NULL,
  amount_gs             NUMBER                      NOT NULL,
  delta_due             NUMBER                      DEFAULT 0 NOT NULL,
  balance_due_after     NUMBER                      DEFAULT 0 NOT NULL,
  idempotency_key       VARCHAR2(120)               NOT NULL,
  actor_user_id         NUMBER                      NULL,
  metadata              CLOB                        NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT pk_org_refund_disp_ledger PRIMARY KEY
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT pk_org_refund_disp_ledger PRIMARY KEY (id_ledger_entry)
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT uq_refund_disp_ledger_idem UNIQUE
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT uq_refund_disp_ledger_idem UNIQUE (idempotency_key)
/

PROMPT CREATE UNIQUE INDEX uq_refund_disp_ledger_term
CREATE UNIQUE INDEX uq_refund_disp_ledger_term
  ON org_refund_dispute_ledger (
    CASE
      WHEN event_type IN (
        'CUSTOMER_CREDIT_ISSUED',
        'ORG_DEBT_OPENED',
        'CREDIT_REVERSED',
        'DEBT_WAIVED'
      ) THEN dispute_id
      ELSE NULL
    END,
    CASE
      WHEN event_type IN (
        'CUSTOMER_CREDIT_ISSUED',
        'ORG_DEBT_OPENED',
        'CREDIT_REVERSED',
        'DEBT_WAIVED'
      ) THEN event_type
      ELSE NULL
    END
  )
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT fk_refund_disp_ledger_org FOREIGN KEY
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT fk_refund_disp_ledger_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT fk_refund_disp_ledger_disp FOREIGN KEY
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT fk_refund_disp_ledger_disp FOREIGN KEY (dispute_id)
  REFERENCES org_refund_dispute (id_dispute)
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT fk_refund_disp_ledger_comp FOREIGN KEY
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT fk_refund_disp_ledger_comp FOREIGN KEY (compensation_id)
  REFERENCES org_refund_dispute_compensation (id_compensation)
/

PROMPT ALTER TABLE org_refund_dispute_ledger ADD CONSTRAINT chk_refund_disp_ledger_evt CHECK
ALTER TABLE org_refund_dispute_ledger
  ADD CONSTRAINT chk_refund_disp_ledger_evt CHECK (
    event_type IN (
      'CUSTOMER_CREDIT_ISSUED',
      'ORG_DEBT_OPENED',
      'DEBT_RECOVERED',
      'CREDIT_REVERSED',
      'DEBT_WAIVED'
    )
  )
/

COMMENT ON TABLE org_refund_dispute_ledger IS
  'Journal inmutable del riel de compensacion/recupero. Idempotente por clave de accion. Separado de facturacion de suscripcion.';
/
