PROMPT CREATE TABLE org_subscription
CREATE TABLE org_subscription (
  id_subscription       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  pln_id_plan           NUMBER                      NOT NULL,
  status                VARCHAR2(20)                NOT NULL,
  is_founder            NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  billing_exempt        NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  storage_used_bytes    NUMBER                      DEFAULT 0 NOT NULL,
  storage_limit_bytes   NUMBER                      DEFAULT 0 NOT NULL,
  trial_started_at      TIMESTAMP(6) WITH TIME ZONE NULL,
  trial_ends_at         TIMESTAMP(6) WITH TIME ZONE NULL,
  current_period_start  TIMESTAMP(6) WITH TIME ZONE NULL,
  current_period_end    TIMESTAMP(6) WITH TIME ZONE NULL,
  grace_ends_at         TIMESTAMP(6) WITH TIME ZONE NULL,
  canceled_at           TIMESTAMP(6) WITH TIME ZONE NULL,
  auto_renew            NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  last_charge_at        TIMESTAMP(6) WITH TIME ZONE NULL,
  charge_retry_count    NUMBER                      DEFAULT 0 NOT NULL,
  account_balance       NUMBER                      DEFAULT 0 NOT NULL,
  pending_pln_id_plan   NUMBER                      NULL,
  pending_plan_change_at TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgsub_status ON org_subscription (status)
CREATE INDEX idx_orgsub_status
  ON org_subscription (
    status
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT pk_org_subscription PRIMARY KEY
ALTER TABLE org_subscription
  ADD CONSTRAINT pk_org_subscription PRIMARY KEY (
    id_subscription
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT uq_orgsub_org UNIQUE
ALTER TABLE org_subscription
  ADD CONSTRAINT uq_orgsub_org UNIQUE (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT chk_orgsub_status CHECK
ALTER TABLE org_subscription
  ADD CONSTRAINT chk_orgsub_status CHECK (
    status IN ('TRIAL', 'ACTIVE', 'PAST_DUE', 'READ_ONLY', 'CANCELED', 'FOUNDER')
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT chk_orgsub_founder CHECK
ALTER TABLE org_subscription
  ADD CONSTRAINT chk_orgsub_founder CHECK (
    is_founder IN (0, 1)
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT chk_orgsub_exempt CHECK
ALTER TABLE org_subscription
  ADD CONSTRAINT chk_orgsub_exempt CHECK (
    billing_exempt IN (0, 1)
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT chk_orgsub_autorenew CHECK
ALTER TABLE org_subscription
  ADD CONSTRAINT chk_orgsub_autorenew CHECK (
    auto_renew IN (0, 1)
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT fk_orgsub_org FOREIGN KEY
ALTER TABLE org_subscription
  ADD CONSTRAINT fk_orgsub_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT fk_orgsub_plan FOREIGN KEY
ALTER TABLE org_subscription
  ADD CONSTRAINT fk_orgsub_plan FOREIGN KEY (
    pln_id_plan
  ) REFERENCES ref_plan (
    id_plan
  )
/

PROMPT ALTER TABLE org_subscription ADD CONSTRAINT fk_orgsub_pending_plan FOREIGN KEY
ALTER TABLE org_subscription
  ADD CONSTRAINT fk_orgsub_pending_plan FOREIGN KEY (
    pending_pln_id_plan
  ) REFERENCES ref_plan (
    id_plan
  )
/

COMMENT ON TABLE org_subscription IS 'Suscripcion vigente por organizacion (1:1). Fuente de verdad del estado de facturacion y entitlements.';
COMMENT ON COLUMN org_subscription.status IS 'TRIAL, ACTIVE, PAST_DUE (3d gracia), READ_ONLY (vencido), CANCELED, FOUNDER (early adopter).';
COMMENT ON COLUMN org_subscription.billing_exempt IS 'Si es 1, la organizacion no se factura. Fundadores usan is_founder=1 con 50% permanente en checkout (no exencion total).';
COMMENT ON COLUMN org_subscription.storage_limit_bytes IS 'Limite total = storage del plan + addons activos. En Base baja a 0.';
COMMENT ON COLUMN org_subscription.storage_used_bytes IS 'Bytes ocupados por adjuntos. Se congela en downgrade a Base.';
COMMENT ON COLUMN org_subscription.grace_ends_at IS 'Fin de los 3 dias de gracia en PAST_DUE; luego pasa a READ_ONLY.';
COMMENT ON COLUMN org_subscription.auto_renew IS 'Si es 1, el job de facturacion cobra automaticamente con la tarjeta catastrada al vencer el periodo.';
COMMENT ON COLUMN org_subscription.last_charge_at IS 'Ultimo intento de debito recurrente disparado por el job / activacion.';
COMMENT ON COLUMN org_subscription.charge_retry_count IS 'Intentos de cobro del ciclo actual (dunning). Se resetea a 0 cuando el webhook confirma el pago.';
COMMENT ON COLUMN org_subscription.account_balance IS 'Saldo a favor en Gs. Se aplica automaticamente en el proximo cargo.';
COMMENT ON COLUMN org_subscription.pending_pln_id_plan IS 'Plan agendado (downgrade) que se aplica al fin del ciclo.';
COMMENT ON COLUMN org_subscription.pending_plan_change_at IS 'Fecha/hora de aplicacion del plan pendiente (normalmente current_period_end).';
