PROMPT CREATE TABLE org_specialty
CREATE TABLE org_specialty (
  id_org_specialty NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  name             VARCHAR2(100)               NOT NULL,
  description      VARCHAR2(255)               NULL,
  is_active        NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE org_specialty ADD CONSTRAINT pk_org_specialty PRIMARY KEY
ALTER TABLE org_specialty
  ADD CONSTRAINT pk_org_specialty PRIMARY KEY (
    id_org_specialty
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE org_specialty ADD CONSTRAINT uk_org_specialty_name UNIQUE
ALTER TABLE org_specialty
  ADD CONSTRAINT uk_org_specialty_name UNIQUE (
    name
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


