PROMPT CREATE TABLE org_refund_dispute_evidence
CREATE TABLE org_refund_dispute_evidence (
  id_evidence           NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  dispute_id            NUMBER                      NOT NULL,
  attempt_n             NUMBER                      NOT NULL,
  object_key            VARCHAR2(500)               NOT NULL,
  mime_type             VARCHAR2(150)               NULL,
  size_bytes            NUMBER                      DEFAULT 0 NOT NULL,
  sha256                VARCHAR2(64)                NULL,
  uploaded_by           NUMBER                      NULL,
  uploaded_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ocr_status            VARCHAR2(30)                DEFAULT 'PROCESSING' NOT NULL,
  ocr_amount            NUMBER                      NULL,
  ocr_alias_hint        VARCHAR2(200)               NULL,
  ocr_confidence        NUMBER                      NULL,
  ocr_raw               CLOB                        NULL,
  extractor_version     VARCHAR2(40)                DEFAULT 'refund_proof_v1' NOT NULL,
  ocr_checked_at        TIMESTAMP(6) WITH TIME ZONE NULL
)
/

PROMPT CREATE INDEX idx_refund_evidence_dispute
CREATE INDEX idx_refund_evidence_dispute
  ON org_refund_dispute_evidence (dispute_id, attempt_n)
/

PROMPT ALTER TABLE org_refund_dispute_evidence ADD CONSTRAINT pk_org_refund_dispute_ev PRIMARY KEY
ALTER TABLE org_refund_dispute_evidence
  ADD CONSTRAINT pk_org_refund_dispute_ev PRIMARY KEY (id_evidence)
/

PROMPT ALTER TABLE org_refund_dispute_evidence ADD CONSTRAINT fk_refund_evidence_dispute FOREIGN KEY
ALTER TABLE org_refund_dispute_evidence
  ADD CONSTRAINT fk_refund_evidence_dispute FOREIGN KEY (dispute_id)
  REFERENCES org_refund_dispute (id_dispute) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_refund_dispute_evidence ADD CONSTRAINT chk_refund_evidence_ocr CHECK
ALTER TABLE org_refund_dispute_evidence
  ADD CONSTRAINT chk_refund_evidence_ocr CHECK (
    ocr_status IN (
      'PROCESSING',
      'ACCEPTED',
      'MANUAL_REVIEW',
      'REJECTED_DEFINITE',
      'TECHNICAL_FAILURE'
    )
  )
/

COMMENT ON TABLE org_refund_dispute_evidence IS
  'Pruebas de transferencia de reembolso (append-only). No reutiliza payment_transaction.receipt_url.';
/
