PROMPT CREATE TABLE org_storage_addon
CREATE TABLE org_storage_addon (
  id_org_storage_addon NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization  NUMBER                      NOT NULL,
  sad_id_storage_addon NUMBER                      NOT NULL,
  quantity             NUMBER                      DEFAULT 1 NOT NULL,
  status               VARCHAR2(20)                DEFAULT 'ACTIVE' NOT NULL,
  started_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ends_at              TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgsad_org ON org_storage_addon (org_id_organization)
CREATE INDEX idx_orgsad_org
  ON org_storage_addon (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_storage_addon ADD CONSTRAINT pk_org_storage_addon PRIMARY KEY
ALTER TABLE org_storage_addon
  ADD CONSTRAINT pk_org_storage_addon PRIMARY KEY (
    id_org_storage_addon
  )
/

PROMPT ALTER TABLE org_storage_addon ADD CONSTRAINT chk_orgsad_status CHECK
ALTER TABLE org_storage_addon
  ADD CONSTRAINT chk_orgsad_status CHECK (
    status IN ('ACTIVE', 'CANCELED', 'EXPIRED')
  )
/

PROMPT ALTER TABLE org_storage_addon ADD CONSTRAINT chk_orgsad_qty CHECK
ALTER TABLE org_storage_addon
  ADD CONSTRAINT chk_orgsad_qty CHECK (
    quantity >= 1
  )
/

PROMPT ALTER TABLE org_storage_addon ADD CONSTRAINT fk_orgsad_org FOREIGN KEY
ALTER TABLE org_storage_addon
  ADD CONSTRAINT fk_orgsad_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_storage_addon ADD CONSTRAINT fk_orgsad_addon FOREIGN KEY
ALTER TABLE org_storage_addon
  ADD CONSTRAINT fk_orgsad_addon FOREIGN KEY (
    sad_id_storage_addon
  ) REFERENCES ref_storage_addon (
    id_storage_addon
  )
/

COMMENT ON TABLE org_storage_addon IS 'Paquetes de storage adicional contratados por organizacion. Solo suman al limite los que estan en status ACTIVE.';
