PROMPT CREATE TABLE org_subscription_invoice
CREATE TABLE org_subscription_invoice (
  id_invoice          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  sub_id_subscription NUMBER                      NULL,
  invoice_type        VARCHAR2(20)                DEFAULT 'SUBSCRIPTION' NOT NULL,
  pln_id_plan         NUMBER                      NULL,
  description         VARCHAR2(255)               NULL,
  amount              NUMBER                      NOT NULL,
  currency            VARCHAR2(3)                 DEFAULT 'PYG' NOT NULL,
  status              VARCHAR2(20)                NOT NULL,
  period_start        TIMESTAMP(6) WITH TIME ZONE NULL,
  period_end          TIMESTAMP(6) WITH TIME ZONE NULL,
  due_date            TIMESTAMP(6) WITH TIME ZONE NULL,
  paid_at             TIMESTAMP(6) WITH TIME ZONE NULL,
  payment_provider    VARCHAR2(50)                NULL,
  external_reference  VARCHAR2(128)               NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orginv_org_created ON org_subscription_invoice (org_id_organization, created_at)
CREATE INDEX idx_orginv_org_created
  ON org_subscription_invoice (
    org_id_organization,
    created_at
  )
/

PROMPT CREATE INDEX idx_orginv_status ON org_subscription_invoice (status)
CREATE INDEX idx_orginv_status
  ON org_subscription_invoice (
    status
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT pk_org_sub_invoice PRIMARY KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT pk_org_sub_invoice PRIMARY KEY (
    id_invoice
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_type CHECK
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT chk_orginv_type CHECK (
    invoice_type IN ('SUBSCRIPTION', 'STORAGE_ADDON')
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT chk_orginv_status CHECK
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT chk_orginv_status CHECK (
    status IN ('PENDING', 'PAID', 'FAILED', 'VOID')
  )
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_org FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_sub FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_sub FOREIGN KEY (
    sub_id_subscription
  ) REFERENCES org_subscription (
    id_subscription
  ) ON DELETE SET NULL
/

PROMPT ALTER TABLE org_subscription_invoice ADD CONSTRAINT fk_orginv_plan FOREIGN KEY
ALTER TABLE org_subscription_invoice
  ADD CONSTRAINT fk_orginv_plan FOREIGN KEY (
    pln_id_plan
  ) REFERENCES ref_plan (
    id_plan
  )
/

COMMENT ON TABLE org_subscription_invoice IS 'Facturacion de plan y addons de storage (separado de payment_transaction, que corresponde a senas de citas).';
