PROMPT CREATE TABLE org_payment_settings
CREATE TABLE org_payment_settings (
  id_payment_settings NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  deposits_enabled    NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  refund_policy       VARCHAR2(20)                NULL,
  bank_id             NUMBER                      NULL,
  account_holder      VARCHAR2(200)               NULL,
  document_id         VARCHAR2(40)                NULL,
  bank_alias          VARCHAR2(120)               NULL,
  refund_strike_count NUMBER                      DEFAULT 0 NOT NULL,
  deposits_suspended  NUMBER(1,0)                 DEFAULT 0 NOT NULL,
  deposits_suspended_at TIMESTAMP(6) WITH TIME ZONE NULL,
  deposits_suspended_reason VARCHAR2(400)         NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by_user     NUMBER                      NULL
)
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT pk_org_payment_settings PRIMARY KEY
ALTER TABLE org_payment_settings
  ADD CONSTRAINT pk_org_payment_settings PRIMARY KEY (
    id_payment_settings
  )
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT uq_org_payment_settings_org UNIQUE
ALTER TABLE org_payment_settings
  ADD CONSTRAINT uq_org_payment_settings_org UNIQUE (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT fk_org_payset_org FOREIGN KEY
ALTER TABLE org_payment_settings
  ADD CONSTRAINT fk_org_payset_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT fk_org_payset_bank FOREIGN KEY
ALTER TABLE org_payment_settings
  ADD CONSTRAINT fk_org_payset_bank FOREIGN KEY (
    bank_id
  ) REFERENCES ref_sipap_bank (
    id_bank
  )
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT chk_org_payset_enabled CHECK
ALTER TABLE org_payment_settings
  ADD CONSTRAINT chk_org_payset_enabled CHECK (
    deposits_enabled IN (0, 1)
  )
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT chk_org_payset_suspended CHECK
ALTER TABLE org_payment_settings
  ADD CONSTRAINT chk_org_payset_suspended CHECK (
    deposits_suspended IN (0, 1)
  )
/

PROMPT ALTER TABLE org_payment_settings ADD CONSTRAINT chk_org_payset_policy CHECK
ALTER TABLE org_payment_settings
  ADD CONSTRAINT chk_org_payset_policy CHECK (
    refund_policy IS NULL
    OR refund_policy IN ('FLEXIBLE', 'MODERATE', 'STRICT')
  )
/

COMMENT ON TABLE org_payment_settings IS
  'Configuracion de cobro de senas por transferencia SIPAP (1:1 org). Separado de Pagopar de suscripcion Hasel.';
/

COMMENT ON COLUMN org_payment_settings.deposits_enabled IS
  '1 = el comercio habilito senas; requiere politica + datos SIPAP completos.';
/

COMMENT ON COLUMN org_payment_settings.refund_policy IS
  'FLEXIBLE | MODERATE | STRICT. Obligatoria si deposits_enabled = 1.';
/

COMMENT ON COLUMN org_payment_settings.bank_id IS
  'FK a ref_sipap_bank. Obligatoria si deposits_enabled = 1.';
/

COMMENT ON COLUMN org_payment_settings.bank_alias IS
  'Alias SIPAP del comercio (campo estrella para recibir transferencias).';
/

COMMENT ON COLUMN org_payment_settings.refund_strike_count IS
  'Strikes por reembolsos fuera de SLA (3 = suspension).';
/

COMMENT ON COLUMN org_payment_settings.deposits_suspended IS
  '1 = senas suspendidas tras 3 strikes.';
/
