PROMPT CREATE TABLE org_integration
CREATE TABLE org_integration (
  id_integration      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  provider            VARCHAR2(50)                NOT NULL,
  public_key          VARCHAR2(500)               NOT NULL,
  private_key         VARCHAR2(500)               NOT NULL,
  is_active           NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_orgint_org ON org_integration
CREATE INDEX idx_orgint_org
  ON org_integration (
    org_id_organization
  )
/

PROMPT ALTER TABLE org_integration ADD CONSTRAINT pk_org_integration PRIMARY KEY
ALTER TABLE org_integration
  ADD CONSTRAINT pk_org_integration PRIMARY KEY (
    id_integration
  )
/

PROMPT ALTER TABLE org_integration ADD CONSTRAINT uq_orgint_org_prov UNIQUE
ALTER TABLE org_integration
  ADD CONSTRAINT uq_orgint_org_prov UNIQUE (
    org_id_organization,
    provider
  )
/

PROMPT ALTER TABLE org_integration ADD CONSTRAINT fk_orgint_org FOREIGN KEY
ALTER TABLE org_integration
  ADD CONSTRAINT fk_orgint_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_integration ADD CONSTRAINT chk_orgint_active CHECK
ALTER TABLE org_integration
  ADD CONSTRAINT chk_orgint_active CHECK (
    is_active IN (0, 1)
  )
/
