PROMPT CREATE TABLE org_refund_strike
CREATE TABLE org_refund_strike (
  id_strike             NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  dispute_id            NUMBER                      NOT NULL,
  reason                VARCHAR2(40)                DEFAULT 'TIMEOUT' NOT NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE org_refund_strike ADD CONSTRAINT pk_org_refund_strike PRIMARY KEY
ALTER TABLE org_refund_strike
  ADD CONSTRAINT pk_org_refund_strike PRIMARY KEY (id_strike)
/

PROMPT ALTER TABLE org_refund_strike ADD CONSTRAINT uq_refund_strike_dispute UNIQUE
ALTER TABLE org_refund_strike
  ADD CONSTRAINT uq_refund_strike_dispute UNIQUE (dispute_id)
/

PROMPT ALTER TABLE org_refund_strike ADD CONSTRAINT fk_refund_strike_org FOREIGN KEY
ALTER TABLE org_refund_strike
  ADD CONSTRAINT fk_refund_strike_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_refund_strike ADD CONSTRAINT fk_refund_strike_dispute FOREIGN KEY
ALTER TABLE org_refund_strike
  ADD CONSTRAINT fk_refund_strike_dispute FOREIGN KEY (dispute_id)
  REFERENCES org_refund_dispute (id_dispute)
/

PROMPT ALTER TABLE org_refund_strike ADD CONSTRAINT chk_refund_strike_reason CHECK
ALTER TABLE org_refund_strike
  ADD CONSTRAINT chk_refund_strike_reason CHECK (reason IN ('TIMEOUT', 'OPS_ADVERSE'))
/

COMMENT ON TABLE org_refund_strike IS
  'Ledger inmutable de sanciones. UNIQUE(dispute_id) garantiza un strike por disputa.';
/
