PROMPT CREATE TABLE org_invitation
CREATE TABLE org_invitation (
  id_org_invitation   NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  pro_id_professional NUMBER                      NOT NULL,
  platform_user_id    NUMBER                      NULL,
  invite_email        VARCHAR2(150)               NOT NULL,
  display_name        VARCHAR2(150)               NOT NULL,
  apex_user_name      VARCHAR2(100)               NOT NULL,
  rol_id_role         NUMBER                      NOT NULL,
  invite_token        VARCHAR2(64)                NOT NULL,
  status              VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  invited_by          NUMBER                      NULL,
  expires_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  accepted_at         TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_org_invitation PRIMARY KEY (id_org_invitation),
  CONSTRAINT uq_org_invitation_token UNIQUE (invite_token),
  CONSTRAINT chk_org_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED')),
  CONSTRAINT fk_org_invitation_org FOREIGN KEY (org_id_organization)
    REFERENCES organization (id_organization) ON DELETE CASCADE,
  CONSTRAINT fk_org_invitation_pro FOREIGN KEY (pro_id_professional)
    REFERENCES professional (id_professional) ON DELETE CASCADE,
  CONSTRAINT fk_org_invitation_role FOREIGN KEY (rol_id_role)
    REFERENCES role (id_role),
  CONSTRAINT fk_org_invitation_platform_user FOREIGN KEY (platform_user_id)
    REFERENCES platform_user (id_platform_user) ON DELETE SET NULL,
  CONSTRAINT fk_org_invitation_invited_by FOREIGN KEY (invited_by)
    REFERENCES org_member (id_org_member) ON DELETE SET NULL
)
/

PROMPT CREATE INDEX idx_org_invitation_org_email
CREATE INDEX idx_org_invitation_org_email
  ON org_invitation (org_id_organization, lower(invite_email), status)
/

PROMPT CREATE INDEX idx_org_invitation_pro
CREATE INDEX idx_org_invitation_pro
  ON org_invitation (pro_id_professional, status)
/
