PROMPT CREATE TABLE org_member
CREATE TABLE org_member (
  id_org_member              NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  platform_user_id           NUMBER                      NOT NULL,
  org_id_organization        NUMBER                      NOT NULL,
  rol_id_role                NUMBER                      NOT NULL,
  is_active                  NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  notify_all_professionals   CHAR(1)                     DEFAULT 'N' NOT NULL,
  created_at                 TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_om_org ON org_member (org_id_organization)
CREATE INDEX idx_om_org
  ON org_member (org_id_organization)
/

PROMPT CREATE INDEX idx_om_platform_user ON org_member (platform_user_id)
CREATE INDEX idx_om_platform_user
  ON org_member (platform_user_id)
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT chk_om_active CHECK (is_active IN (0, 1))
ALTER TABLE org_member
  ADD CONSTRAINT chk_om_active CHECK (is_active IN (0, 1))
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT chk_om_notify_all_professionals
ALTER TABLE org_member
  ADD CONSTRAINT chk_om_notify_all_professionals CHECK (notify_all_professionals IN ('Y', 'N'))
/

PROMPT ALTER TABLE org_member ADD PRIMARY KEY
ALTER TABLE org_member
  ADD CONSTRAINT pk_org_member PRIMARY KEY (id_org_member)
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT uq_om_user_org UNIQUE (platform_user_id, org_id_organization)
ALTER TABLE org_member
  ADD CONSTRAINT uq_om_user_org UNIQUE (platform_user_id, org_id_organization)
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT fk_om_platform_user FOREIGN KEY
ALTER TABLE org_member
  ADD CONSTRAINT fk_om_platform_user FOREIGN KEY (platform_user_id)
  REFERENCES platform_user (id_platform_user)
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT fk_om_organization FOREIGN KEY
ALTER TABLE org_member
  ADD CONSTRAINT fk_om_organization FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization) ON DELETE CASCADE
/

PROMPT ALTER TABLE org_member ADD CONSTRAINT fk_om_role FOREIGN KEY
ALTER TABLE org_member
  ADD CONSTRAINT fk_om_role FOREIGN KEY (rol_id_role)
  REFERENCES role (id_role)
/

COMMENT ON TABLE org_member IS 'Membresia usuario-organizacion con rol. id_org_member conserva el antiguo app_user.id_user.';
COMMENT ON COLUMN org_member.id_org_member IS 'JWT user_id / professional.usr_id_user apuntan aqui.';
COMMENT ON COLUMN org_member.notify_all_professionals IS 'Y = el admin recibe pushes de citas de otros profesionales de la org. Default N.';
