PROMPT CREATE TABLE payment_transaction
CREATE TABLE payment_transaction (
  id_transaction        NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  app_id_appointment    NUMBER                      NOT NULL,
  provider              VARCHAR2(50)                DEFAULT 'sipap' NOT NULL,
  external_reference    VARCHAR2(128)               NULL,
  id_pedido_comercio    VARCHAR2(64)                NOT NULL,
  idempotency_key       VARCHAR2(128)               NOT NULL,
  amount                NUMBER                      NOT NULL,
  currency              VARCHAR2(3)                 DEFAULT 'PYG' NOT NULL,
  payment_status        VARCHAR2(20)                NOT NULL,
  payment_channel       VARCHAR2(20)                DEFAULT 'TRANSFER' NOT NULL,
  payment_reference     VARCHAR2(32)                NULL,
  source                VARCHAR2(20)                NOT NULL,
  forma_pago_requested  NUMBER                      NULL,
  forma_pago_confirmed  NUMBER                      NULL,
  forma_pago_label      VARCHAR2(150)               NULL,
  signature_received    VARCHAR2(256)               NULL,
  signature_valid       NUMBER(1,0)                 NULL,
  raw_request           CLOB                        NULL,
  raw_response          CLOB                        NULL,
  receipt_object_key    VARCHAR2(500)               NULL,
  receipt_url           VARCHAR2(1000)              NULL,
  receipt_mime_type     VARCHAR2(150)               NULL,
  receipt_uploaded_at   TIMESTAMP(6) WITH TIME ZONE NULL,
  ocr_raw_json          CLOB                        NULL,
  ocr_reference         VARCHAR2(64)                NULL,
  ocr_amount            NUMBER                      NULL,
  ocr_transferred_at    TIMESTAMP(6) WITH TIME ZONE NULL,
  ocr_confidence        NUMBER                      NULL,
  ocr_status            VARCHAR2(20)                NULL,
  ocr_checked_at        TIMESTAMP(6) WITH TIME ZONE NULL,
  reviewed_at           TIMESTAMP(6) WITH TIME ZONE NULL,
  reviewed_by           NUMBER                      NULL,
  reject_reason         VARCHAR2(400)               NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at          TIMESTAMP(6) WITH TIME ZONE NULL
)
/

PROMPT CREATE INDEX idx_paytx_app ON payment_transaction
CREATE INDEX idx_paytx_app
  ON payment_transaction (
    app_id_appointment
  )
/

PROMPT CREATE INDEX idx_paytx_ext_ref ON payment_transaction
CREATE INDEX idx_paytx_ext_ref
  ON payment_transaction (
    external_reference
  )
/

PROMPT CREATE UNIQUE INDEX uq_paytx_payment_reference ON payment_transaction
CREATE UNIQUE INDEX uq_paytx_payment_reference
  ON payment_transaction (
    payment_reference
  )
/

COMMENT ON COLUMN payment_transaction.payment_reference IS
  'Codigo HASEL-XXXXXXXX para asunto SIPAP / conciliacion OCR. Unique cuando no es null.';
/

COMMENT ON COLUMN payment_transaction.receipt_object_key IS
  'Object key relativo: organizations/{org}/payments/{yyyy}/{mm}/{customer}/{id}.{ext}';
/

COMMENT ON COLUMN payment_transaction.receipt_url IS
  'URL del comprobante (pruebas: bucket publico). En prod usar PAR/proxy.';
/

COMMENT ON COLUMN payment_transaction.ocr_status IS
  'PENDING|MATCH|MISMATCH|MANUAL_REVIEW|FAILED — ciclo OCR del comprobante SIPAP.';
/

PROMPT CREATE INDEX idx_paytx_org_created ON payment_transaction
CREATE INDEX idx_paytx_org_created
  ON payment_transaction (
    org_id_organization,
    created_at
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT chk_paytx_ocr_status CHECK
ALTER TABLE payment_transaction
  ADD CONSTRAINT chk_paytx_ocr_status CHECK (
    ocr_status IS NULL
    OR ocr_status IN ('PENDING','MATCH','MISMATCH','MANUAL_REVIEW','FAILED')
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT pk_payment_transaction PRIMARY KEY
ALTER TABLE payment_transaction
  ADD CONSTRAINT pk_payment_transaction PRIMARY KEY (
    id_transaction
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT uq_paytx_idempotency UNIQUE
ALTER TABLE payment_transaction
  ADD CONSTRAINT uq_paytx_idempotency UNIQUE (
    provider,
    idempotency_key
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT fk_paytx_app FOREIGN KEY
ALTER TABLE payment_transaction
  ADD CONSTRAINT fk_paytx_app FOREIGN KEY (
    app_id_appointment
  ) REFERENCES appointment (
    id_appointment
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT fk_paytx_org FOREIGN KEY
ALTER TABLE payment_transaction
  ADD CONSTRAINT fk_paytx_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT fk_paytx_forma_req FOREIGN KEY
ALTER TABLE payment_transaction
  ADD CONSTRAINT fk_paytx_forma_req FOREIGN KEY (
    forma_pago_requested
  ) REFERENCES ref_pagopar_forma_pago (
    id_forma_pago
  )
/

PROMPT ALTER TABLE payment_transaction ADD CONSTRAINT fk_paytx_forma_conf FOREIGN KEY
ALTER TABLE payment_transaction
  ADD CONSTRAINT fk_paytx_forma_conf FOREIGN KEY (
    forma_pago_confirmed
  ) REFERENCES ref_pagopar_forma_pago (
    id_forma_pago
  )
/
