PROMPT CREATE TABLE platform_user
CREATE TABLE platform_user (
  id_platform_user  NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  apex_user_name    VARCHAR2(100)               NOT NULL,
  email             VARCHAR2(150)               NOT NULL,
  password_hash     VARCHAR2(255)               NOT NULL,
  first_name               VARCHAR2(50)                NOT NULL,
  last_name                VARCHAR2(50)                NOT NULL,
  public_slug              VARCHAR2(100)               NULL,
  profile_image_url        VARCHAR2(4000)              NULL,
  profile_image_mime       VARCHAR2(100)               NULL,
  profile_image_file_name  VARCHAR2(255)               NULL,
  is_active                NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  email_verified_at TIMESTAMP(6) WITH TIME ZONE NULL,
  failed_login_attempts    NUMBER                      DEFAULT 0 NOT NULL,
  locked_until             TIMESTAMP(6) WITH TIME ZONE NULL,
  password_salt            VARCHAR2(64)                NULL,
  password_algo            VARCHAR2(30)                DEFAULT 'SHA256_LEGACY' NOT NULL,
  password_iterations      NUMBER                      NULL,
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT chk_pu_active CHECK (is_active IN (0, 1))
ALTER TABLE platform_user
  ADD CONSTRAINT chk_pu_active CHECK (is_active IN (0, 1))
/

PROMPT ALTER TABLE platform_user ADD PRIMARY KEY
ALTER TABLE platform_user
  ADD CONSTRAINT pk_platform_user PRIMARY KEY (id_platform_user)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_email UNIQUE (email)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_email UNIQUE (email)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_apex_user UNIQUE (apex_user_name)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_apex_user UNIQUE (apex_user_name)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_public_slug UNIQUE (public_slug)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_public_slug UNIQUE (public_slug)
/

COMMENT ON TABLE platform_user IS 'Identidad global: credenciales y perfil de la persona en la plataforma.';
COMMENT ON COLUMN platform_user.public_slug IS 'Slug global unico para /u/{slug} (link in bio del usuario).';
COMMENT ON COLUMN platform_user.profile_image_url IS 'Foto publica global del usuario (OCI).';
COMMENT ON COLUMN platform_user.profile_image_mime IS 'MIME type de la foto publica global.';
COMMENT ON COLUMN platform_user.profile_image_file_name IS 'Nombre de archivo en bucket para la foto global.';
COMMENT ON COLUMN platform_user.email_verified_at IS 'Verificacion de correo a nivel de cuenta global.';
COMMENT ON COLUMN platform_user.failed_login_attempts IS 'Contador de intentos fallidos de login consecutivos; se resetea a 0 en login exitoso.';
COMMENT ON COLUMN platform_user.locked_until IS 'Timestamp hasta el cual la cuenta esta bloqueada por exceso de intentos fallidos (NULL = no bloqueada).';
COMMENT ON COLUMN platform_user.password_salt IS 'Salt aleatorio (hex) por usuario para password_algo = PBKDF2_HMAC_SHA256_V1. NULL para hashes legados.';
COMMENT ON COLUMN platform_user.password_algo IS 'Algoritmo del password_hash: SHA256_LEGACY (sin salt, legado) o PBKDF2_HMAC_SHA256_V1 (con salt e iteraciones).';
COMMENT ON COLUMN platform_user.password_iterations IS 'Cantidad de iteraciones usadas al generar password_hash cuando password_algo = PBKDF2_HMAC_SHA256_V1.';
