PROMPT CREATE TABLE platform_user
CREATE TABLE platform_user (
  id_platform_user  NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  apex_user_name    VARCHAR2(100)               NOT NULL,
  email             VARCHAR2(150)               NOT NULL,
  password_hash     VARCHAR2(255)               NOT NULL,
  first_name               VARCHAR2(50)                NOT NULL,
  last_name                VARCHAR2(50)                NOT NULL,
  public_slug              VARCHAR2(100)               NULL,
  profile_image_url        VARCHAR2(4000)              NULL,
  profile_image_mime       VARCHAR2(100)               NULL,
  profile_image_file_name  VARCHAR2(255)               NULL,
  is_active                NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  email_verified_at TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT chk_pu_active CHECK (is_active IN (0, 1))
ALTER TABLE platform_user
  ADD CONSTRAINT chk_pu_active CHECK (is_active IN (0, 1))
/

PROMPT ALTER TABLE platform_user ADD PRIMARY KEY
ALTER TABLE platform_user
  ADD CONSTRAINT pk_platform_user PRIMARY KEY (id_platform_user)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_email UNIQUE (email)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_email UNIQUE (email)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_apex_user UNIQUE (apex_user_name)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_apex_user UNIQUE (apex_user_name)
/

PROMPT ALTER TABLE platform_user ADD CONSTRAINT uq_pu_public_slug UNIQUE (public_slug)
ALTER TABLE platform_user
  ADD CONSTRAINT uq_pu_public_slug UNIQUE (public_slug)
/

COMMENT ON TABLE platform_user IS 'Identidad global: credenciales y perfil de la persona en la plataforma.';
COMMENT ON COLUMN platform_user.public_slug IS 'Slug global unico para /u/{slug} (link in bio del usuario).';
COMMENT ON COLUMN platform_user.profile_image_url IS 'Foto publica global del usuario (OCI).';
COMMENT ON COLUMN platform_user.profile_image_mime IS 'MIME type de la foto publica global.';
COMMENT ON COLUMN platform_user.profile_image_file_name IS 'Nombre de archivo en bucket para la foto global.';
COMMENT ON COLUMN platform_user.email_verified_at IS 'Verificacion de correo a nivel de cuenta global.';
