PROMPT CREATE TABLE professional_schedule_exception_slot
CREATE TABLE professional_schedule_exception_slot (
  id_exception_slot       NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  exc_id_schedule_exception NUMBER                    NOT NULL,
  loc_id_location         NUMBER                      NOT NULL,
  start_time              VARCHAR2(5)                 NOT NULL,
  end_time                VARCHAR2(5)                 NOT NULL,
  created_at              TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_sch_exc_slot_exc
CREATE INDEX idx_sch_exc_slot_exc
  ON professional_schedule_exception_slot (
    exc_id_schedule_exception
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT chk_sch_exc_slot_end CHECK
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT chk_sch_exc_slot_end CHECK (
    REGEXP_LIKE(end_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  )
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT chk_sch_exc_slot_start CHECK
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT chk_sch_exc_slot_start CHECK (
    REGEXP_LIKE(start_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  )
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT chk_sch_exc_slot_time CHECK
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT chk_sch_exc_slot_time CHECK (
    start_time < end_time
  )
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT pk_sch_exc_slot PRIMARY KEY
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT pk_sch_exc_slot PRIMARY KEY (
    id_exception_slot
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT fk_sch_exc_slot_exception FOREIGN KEY
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT fk_sch_exc_slot_exception FOREIGN KEY (
    exc_id_schedule_exception
  ) REFERENCES professional_schedule_exception (
    id_schedule_exception
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_schedule_exception_slot ADD CONSTRAINT fk_sch_exc_slot_location FOREIGN KEY
ALTER TABLE professional_schedule_exception_slot
  ADD CONSTRAINT fk_sch_exc_slot_location FOREIGN KEY (
    loc_id_location
  ) REFERENCES location (
    id_location
  ) ON DELETE CASCADE
/

