PROMPT CREATE TABLE professional
CREATE TABLE professional (
  id_professional     NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  usr_id_user         NUMBER                      NOT NULL,
  profile_slug        VARCHAR2(100)               NULL,
  profile_image_url   VARCHAR2(255)               NULL,
  is_active           NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  spe_id_specialty    NUMBER                      NULL,
  phone_number        VARCHAR2(20)                NOT NULL,
  display_name        VARCHAR2(150)               NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_pro_org
CREATE INDEX idx_pro_org
  ON professional (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional ADD CONSTRAINT chk_pro_active CHECK
ALTER TABLE professional
  ADD CONSTRAINT chk_pro_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE professional ADD CONSTRAINT pk_professional PRIMARY KEY
ALTER TABLE professional
  ADD CONSTRAINT pk_professional PRIMARY KEY (
    id_professional
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional ADD CONSTRAINT uq_pro_org_slug UNIQUE
ALTER TABLE professional
  ADD CONSTRAINT uq_pro_org_slug UNIQUE (
    org_id_organization,
    profile_slug
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional ADD CONSTRAINT fk_prof_specialty FOREIGN KEY
ALTER TABLE professional
  ADD CONSTRAINT fk_prof_specialty FOREIGN KEY (
    spe_id_specialty
  ) REFERENCES specialty (
    id_specialty
  ) ON DELETE SET NULL
/

PROMPT ALTER TABLE professional ADD CONSTRAINT fk_pro_organization FOREIGN KEY
ALTER TABLE professional
  ADD CONSTRAINT fk_pro_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional ADD CONSTRAINT fk_pro_org_member FOREIGN KEY
ALTER TABLE professional
  ADD CONSTRAINT fk_pro_org_member FOREIGN KEY (
    usr_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/

PROMPT CREATE OR REPLACE TRIGGER trg_professional_slug
CREATE OR REPLACE TRIGGER trg_professional_slug
BEFORE INSERT OR UPDATE OF profile_slug, usr_id_user, display_name ON professional
FOR EACH ROW
DECLARE
    v_first_name platform_user.first_name%TYPE;
    v_last_name  platform_user.last_name%TYPE;
    v_source     VARCHAR2(300);
BEGIN
    IF :NEW.profile_slug IS NOT NULL THEN
        :NEW.profile_slug := pkg_aox_util.fn_generate_slug(:NEW.profile_slug);
        RETURN;
    END IF;

    IF :NEW.usr_id_user IS NOT NULL THEN
        IF :NEW.display_name IS NOT NULL AND TRIM(:NEW.display_name) IS NOT NULL THEN
            v_source := TRIM(:NEW.display_name) || '-' || :NEW.usr_id_user;
        ELSE
            SELECT pu.first_name, pu.last_name
              INTO v_first_name, v_last_name
              FROM org_member m
              JOIN platform_user pu ON pu.id_platform_user = m.platform_user_id
             WHERE m.id_org_member = :NEW.usr_id_user;

            v_source := v_first_name || ' ' || v_last_name || '-' || :NEW.usr_id_user;
        END IF;

        :NEW.profile_slug := pkg_aox_util.fn_generate_slug(v_source);
        RETURN;
    END IF;

    IF :NEW.display_name IS NOT NULL AND TRIM(:NEW.display_name) IS NOT NULL THEN
        :NEW.profile_slug := pkg_aox_util.fn_generate_slug(TRIM(:NEW.display_name));
        RETURN;
    END IF;

    :NEW.profile_slug := pkg_aox_util.fn_generate_slug('profesional-' || lower(rawtohex(sys_guid())));
END;
/


