PROMPT CREATE TABLE professional_schedule_exception
CREATE TABLE professional_schedule_exception (
  id_schedule_exception NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization   NUMBER                      NOT NULL,
  pro_id_professional   NUMBER                      NOT NULL,
  exception_date        DATE                        NOT NULL,
  exception_type        VARCHAR2(20)                NOT NULL,
  note                  VARCHAR2(500)               NULL,
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_sch_exc_pro_date
CREATE INDEX idx_sch_exc_pro_date
  ON professional_schedule_exception (
    pro_id_professional,
    exception_date
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional_schedule_exception ADD CONSTRAINT chk_sch_exc_type CHECK
ALTER TABLE professional_schedule_exception
  ADD CONSTRAINT chk_sch_exc_type CHECK (
    exception_type IN ('BLOCKED', 'OVERRIDE')
  )
/

PROMPT ALTER TABLE professional_schedule_exception ADD CONSTRAINT uq_sch_exc_pro_date UNIQUE
ALTER TABLE professional_schedule_exception
  ADD CONSTRAINT uq_sch_exc_pro_date UNIQUE (
    pro_id_professional,
    exception_date
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_schedule_exception ADD CONSTRAINT pk_sch_exception PRIMARY KEY
ALTER TABLE professional_schedule_exception
  ADD CONSTRAINT pk_sch_exception PRIMARY KEY (
    id_schedule_exception
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_schedule_exception ADD CONSTRAINT fk_sch_exc_organization FOREIGN KEY
ALTER TABLE professional_schedule_exception
  ADD CONSTRAINT fk_sch_exc_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_schedule_exception ADD CONSTRAINT fk_sch_exc_professional FOREIGN KEY
ALTER TABLE professional_schedule_exception
  ADD CONSTRAINT fk_sch_exc_professional FOREIGN KEY (
    pro_id_professional
  ) REFERENCES professional (
    id_professional
  ) ON DELETE CASCADE
/

