PROMPT CREATE TABLE professional_schedule
CREATE TABLE professional_schedule (
  id_professional_schedule NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization      NUMBER                      NOT NULL,
  pro_id_professional      NUMBER                      NOT NULL,
  loc_id_location          NUMBER                      NOT NULL,
  day_of_week              NUMBER(1,0)                 NOT NULL,
  start_time               VARCHAR2(5)                 NOT NULL,
  end_time                 VARCHAR2(5)                 NOT NULL,
  created_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_sch_pro_loc_day
CREATE INDEX idx_sch_pro_loc_day
  ON professional_schedule (
    pro_id_professional,
    loc_id_location,
    day_of_week
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT chk_sch_day CHECK
ALTER TABLE professional_schedule
  ADD CONSTRAINT chk_sch_day CHECK (
    day_of_week BETWEEN 1 AND 7
  )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT chk_sch_end_time CHECK
ALTER TABLE professional_schedule
  ADD CONSTRAINT chk_sch_end_time CHECK (
    REGEXP_LIKE(end_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT chk_sch_start_time CHECK
ALTER TABLE professional_schedule
  ADD CONSTRAINT chk_sch_start_time CHECK (
    REGEXP_LIKE(start_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT chk_sch_time_logic CHECK
ALTER TABLE professional_schedule
  ADD CONSTRAINT chk_sch_time_logic CHECK (
    start_time < end_time
  )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT pk_pro_schedule PRIMARY KEY
ALTER TABLE professional_schedule
  ADD CONSTRAINT pk_pro_schedule PRIMARY KEY (
    id_professional_schedule
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT fk_sch_location FOREIGN KEY
ALTER TABLE professional_schedule
  ADD CONSTRAINT fk_sch_location FOREIGN KEY (
    loc_id_location
  ) REFERENCES location (
    id_location
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT fk_sch_organization FOREIGN KEY
ALTER TABLE professional_schedule
  ADD CONSTRAINT fk_sch_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_schedule ADD CONSTRAINT fk_sch_professional FOREIGN KEY
ALTER TABLE professional_schedule
  ADD CONSTRAINT fk_sch_professional FOREIGN KEY (
    pro_id_professional
  ) REFERENCES professional (
    id_professional
  ) ON DELETE CASCADE
/


