PROMPT CREATE TABLE professional_image
CREATE TABLE professional_image (
  id_image            NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  pro_id_professional NUMBER        NOT NULL,
  file_name           VARCHAR2(255) NOT NULL,
  mime_type           VARCHAR2(100) NOT NULL,
  created_at          TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional_image ADD PRIMARY KEY
ALTER TABLE professional_image
  ADD PRIMARY KEY (
    id_image
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_image ADD CONSTRAINT fk_prof_image FOREIGN KEY
ALTER TABLE professional_image
  ADD CONSTRAINT fk_prof_image FOREIGN KEY (
    pro_id_professional
  ) REFERENCES professional (
    id_professional
  ) ON DELETE CASCADE
/


