PROMPT CREATE TABLE push_var_catalog
CREATE TABLE push_var_catalog (
  id_var_catalog NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  var_key        VARCHAR2(50)   NOT NULL,
  label_es       VARCHAR2(120)  NOT NULL,
  sample_value   VARCHAR2(200)  NULL,
  is_active      NUMBER(1,0)    DEFAULT 1 NOT NULL,
  sort_order     NUMBER(4,0)    DEFAULT 0 NOT NULL
)
/

PROMPT ALTER TABLE push_var_catalog ADD CONSTRAINT chk_push_var_cat_active CHECK
ALTER TABLE push_var_catalog
  ADD CONSTRAINT chk_push_var_cat_active CHECK (is_active IN (0, 1))
/

PROMPT ALTER TABLE push_var_catalog ADD CONSTRAINT pk_push_var_catalog PRIMARY KEY
ALTER TABLE push_var_catalog
  ADD CONSTRAINT pk_push_var_catalog PRIMARY KEY (id_var_catalog)
/

PROMPT ALTER TABLE push_var_catalog ADD CONSTRAINT uq_push_var_catalog_key UNIQUE
ALTER TABLE push_var_catalog
  ADD CONSTRAINT uq_push_var_catalog_key UNIQUE (var_key)
/

PROMPT INSERT push_var_catalog seed
MERGE INTO push_var_catalog t
USING (
  SELECT 'NOMBRE'   AS var_key, 'Nombre'   AS label_es, 'Ana'              AS sample_value, 10 AS sort_order FROM dual UNION ALL
  SELECT 'APELLIDO' AS var_key, 'Apellido' AS label_es, 'Giménez'          AS sample_value, 20 AS sort_order FROM dual UNION ALL
  SELECT 'EMAIL'    AS var_key, 'Email'    AS label_es, 'ana@ejemplo.com'  AS sample_value, 30 AS sort_order FROM dual
) s
ON (t.var_key = s.var_key)
WHEN MATCHED THEN UPDATE SET
  t.label_es     = s.label_es,
  t.sample_value = s.sample_value,
  t.sort_order   = s.sort_order,
  t.is_active    = 1
WHEN NOT MATCHED THEN INSERT (var_key, label_es, sample_value, is_active, sort_order)
VALUES (s.var_key, s.label_es, s.sample_value, 1, s.sort_order)
/

COMMENT ON TABLE push_var_catalog IS 'Variables de sistema permitidas en titulo (y opcionales en body) de campanas push.';
/