PROMPT CREATE TABLE push_campaign
CREATE TABLE push_campaign (
  id_campaign         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  name                VARCHAR2(200)               NOT NULL,
  title_template      VARCHAR2(500)               NOT NULL,
  body_template       VARCHAR2(4000)              NOT NULL,
  url_template        VARCHAR2(1000)              NULL,
  audience_type       VARCHAR2(20)                NOT NULL,
  role_id             NUMBER                      NULL,
  send_at             TIMESTAMP(6) WITH TIME ZONE NULL,
  status              VARCHAR2(20)                DEFAULT 'DRAFT' NOT NULL,
  scheduler_job_name  VARCHAR2(128)               NULL,
  is_enabled          NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  sent_at             TIMESTAMP(6) WITH TIME ZONE NULL,
  error_message       VARCHAR2(4000)              NULL,
  created_by          VARCHAR2(100)               NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT chk_push_camp_audience CHECK
ALTER TABLE push_campaign
  ADD CONSTRAINT chk_push_camp_audience CHECK (audience_type IN ('ALL_ACTIVE', 'ROLE'))
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT chk_push_camp_status CHECK
ALTER TABLE push_campaign
  ADD CONSTRAINT chk_push_camp_status CHECK (
    status IN ('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'CANCELLED', 'DISABLED', 'ERROR')
  )
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT chk_push_camp_enabled CHECK
ALTER TABLE push_campaign
  ADD CONSTRAINT chk_push_camp_enabled CHECK (is_enabled IN (0, 1))
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT chk_push_camp_role_req CHECK
ALTER TABLE push_campaign
  ADD CONSTRAINT chk_push_camp_role_req CHECK (
    (audience_type = 'ALL_ACTIVE' AND role_id IS NULL)
    OR (audience_type = 'ROLE' AND role_id IS NOT NULL)
  )
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT pk_push_campaign PRIMARY KEY
ALTER TABLE push_campaign
  ADD CONSTRAINT pk_push_campaign PRIMARY KEY (id_campaign)
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT uq_push_camp_job_name UNIQUE
ALTER TABLE push_campaign
  ADD CONSTRAINT uq_push_camp_job_name UNIQUE (scheduler_job_name)
/

PROMPT ALTER TABLE push_campaign ADD CONSTRAINT fk_push_camp_role FOREIGN KEY
ALTER TABLE push_campaign
  ADD CONSTRAINT fk_push_camp_role FOREIGN KEY (role_id)
  REFERENCES role (id_role)
/

PROMPT CREATE INDEX idx_push_camp_status ON push_campaign
CREATE INDEX idx_push_camp_status
  ON push_campaign (status, send_at)
/

COMMENT ON TABLE push_campaign IS 'Campanas push admin (Hasel_admn). Canal paralelo a notificaciones fijas de PKG_AOX_FCM_API.';
/