PROMPT CREATE TABLE push_campaign_var
CREATE TABLE push_campaign_var (
  id_campaign_var NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  id_campaign     NUMBER         NOT NULL,
  var_key         VARCHAR2(50)   NOT NULL,
  var_value       VARCHAR2(4000) NOT NULL
)
/

PROMPT ALTER TABLE push_campaign_var ADD CONSTRAINT pk_push_campaign_var PRIMARY KEY
ALTER TABLE push_campaign_var
  ADD CONSTRAINT pk_push_campaign_var PRIMARY KEY (id_campaign_var)
/

PROMPT ALTER TABLE push_campaign_var ADD CONSTRAINT uq_push_camp_var_key UNIQUE
ALTER TABLE push_campaign_var
  ADD CONSTRAINT uq_push_camp_var_key UNIQUE (id_campaign, var_key)
/

PROMPT ALTER TABLE push_campaign_var ADD CONSTRAINT fk_push_camp_var_camp FOREIGN KEY
ALTER TABLE push_campaign_var
  ADD CONSTRAINT fk_push_camp_var_camp FOREIGN KEY (id_campaign)
  REFERENCES push_campaign (id_campaign) ON DELETE CASCADE
/

PROMPT CREATE INDEX idx_push_camp_var_camp ON push_campaign_var
CREATE INDEX idx_push_camp_var_camp
  ON push_campaign_var (id_campaign)
/

COMMENT ON TABLE push_campaign_var IS 'Variables custom (clave/valor) de una campana push; mismo valor para todos los destinatarios.';
/