PROMPT CREATE TABLE push_campaign_delivery
CREATE TABLE push_campaign_delivery (
  id_delivery      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  id_campaign      NUMBER                      NOT NULL,
  platform_user_id NUMBER                      NOT NULL,
  fcm_token        VARCHAR2(1000)              NULL,
  resolved_title   VARCHAR2(500)               NULL,
  resolved_body    VARCHAR2(4000)              NULL,
  status           VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  error_message    VARCHAR2(4000)              NULL,
  sent_at          TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE push_campaign_delivery ADD CONSTRAINT chk_push_deliv_status CHECK
ALTER TABLE push_campaign_delivery
  ADD CONSTRAINT chk_push_deliv_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
/

PROMPT ALTER TABLE push_campaign_delivery ADD CONSTRAINT pk_push_campaign_delivery PRIMARY KEY
ALTER TABLE push_campaign_delivery
  ADD CONSTRAINT pk_push_campaign_delivery PRIMARY KEY (id_delivery)
/

PROMPT ALTER TABLE push_campaign_delivery ADD CONSTRAINT fk_push_deliv_camp FOREIGN KEY
ALTER TABLE push_campaign_delivery
  ADD CONSTRAINT fk_push_deliv_camp FOREIGN KEY (id_campaign)
  REFERENCES push_campaign (id_campaign) ON DELETE CASCADE
/

PROMPT ALTER TABLE push_campaign_delivery ADD CONSTRAINT fk_push_deliv_pu FOREIGN KEY
ALTER TABLE push_campaign_delivery
  ADD CONSTRAINT fk_push_deliv_pu FOREIGN KEY (platform_user_id)
  REFERENCES platform_user (id_platform_user)
/

PROMPT CREATE INDEX idx_push_deliv_camp ON push_campaign_delivery
CREATE INDEX idx_push_deliv_camp
  ON push_campaign_delivery (id_campaign, status)
/

PROMPT CREATE INDEX idx_push_deliv_pu ON push_campaign_delivery
CREATE INDEX idx_push_deliv_pu
  ON push_campaign_delivery (platform_user_id)
/

COMMENT ON TABLE push_campaign_delivery IS 'Resultado por destinatario/dispositivo de una ejecucion de campana push.';
/