PROMPT CREATE TABLE ref_addon_specialty
CREATE TABLE ref_addon_specialty (
  id_addon_specialty     NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  rad_id_addon           NUMBER                      NOT NULL,
  osp_id_org_specialty   NUMBER                      NOT NULL,
  created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT CREATE INDEX idx_refaddonspec_addon ON ref_addon_specialty (rad_id_addon)
CREATE INDEX idx_refaddonspec_addon
  ON ref_addon_specialty (
    rad_id_addon
  )
/

PROMPT CREATE INDEX idx_refaddonspec_spec ON ref_addon_specialty (osp_id_org_specialty)
CREATE INDEX idx_refaddonspec_spec
  ON ref_addon_specialty (
    osp_id_org_specialty
  )
/

PROMPT ALTER TABLE ref_addon_specialty ADD CONSTRAINT pk_ref_addon_specialty PRIMARY KEY
ALTER TABLE ref_addon_specialty
  ADD CONSTRAINT pk_ref_addon_specialty PRIMARY KEY (
    id_addon_specialty
  )
/

PROMPT ALTER TABLE ref_addon_specialty ADD CONSTRAINT uq_ref_addon_specialty UNIQUE
ALTER TABLE ref_addon_specialty
  ADD CONSTRAINT uq_ref_addon_specialty UNIQUE (
    rad_id_addon,
    osp_id_org_specialty
  )
/

PROMPT ALTER TABLE ref_addon_specialty ADD CONSTRAINT fk_refaddonspec_addon FOREIGN KEY
ALTER TABLE ref_addon_specialty
  ADD CONSTRAINT fk_refaddonspec_addon FOREIGN KEY (
    rad_id_addon
  ) REFERENCES ref_addon (
    id_addon
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE ref_addon_specialty ADD CONSTRAINT fk_refaddonspec_spec FOREIGN KEY
ALTER TABLE ref_addon_specialty
  ADD CONSTRAINT fk_refaddonspec_spec FOREIGN KEY (
    osp_id_org_specialty
  ) REFERENCES org_specialty (
    id_org_specialty
  ) ON DELETE CASCADE
/

COMMENT ON TABLE ref_addon_specialty IS 'Puente addon↔especialidad de org. 0 filas=global; N filas=nicho (ej. ODONTOGRAM_3D→DENTAL).';
COMMENT ON COLUMN ref_addon_specialty.rad_id_addon IS 'FK a ref_addon.id_addon.';
COMMENT ON COLUMN ref_addon_specialty.osp_id_org_specialty IS 'FK a org_specialty.id_org_specialty.';
