PROMPT CREATE TABLE ref_booking_slot_interval
CREATE TABLE ref_booking_slot_interval (
  id_slot_interval NUMBER       GENERATED BY DEFAULT AS IDENTITY,
  minutes_value    NUMBER(4,0)  NOT NULL,
  label            VARCHAR2(80) NOT NULL,
  sort_order       NUMBER(4,0)  DEFAULT 0 NOT NULL,
  is_active        NUMBER(1,0)  DEFAULT 1 NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ref_booking_slot_interval ADD CONSTRAINT chk_ref_slot_interval_active CHECK
ALTER TABLE ref_booking_slot_interval
  ADD CONSTRAINT chk_ref_slot_interval_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE ref_booking_slot_interval ADD CONSTRAINT chk_ref_slot_interval_minutes CHECK
ALTER TABLE ref_booking_slot_interval
  ADD CONSTRAINT chk_ref_slot_interval_minutes CHECK (
    minutes_value IN (15, 30, 45, 60)
  )
/

PROMPT ALTER TABLE ref_booking_slot_interval ADD CONSTRAINT pk_ref_slot_interval PRIMARY KEY
ALTER TABLE ref_booking_slot_interval
  ADD CONSTRAINT pk_ref_slot_interval PRIMARY KEY (
    id_slot_interval
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ref_booking_slot_interval ADD CONSTRAINT uq_ref_slot_interval_minutes UNIQUE
ALTER TABLE ref_booking_slot_interval
  ADD CONSTRAINT uq_ref_slot_interval_minutes UNIQUE (
    minutes_value
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT INSERT ref_booking_slot_interval seed
INSERT INTO ref_booking_slot_interval (minutes_value, label, sort_order, is_active) VALUES (15, '15 minutos', 10, 1);
INSERT INTO ref_booking_slot_interval (minutes_value, label, sort_order, is_active) VALUES (30, '30 minutos', 20, 1);
INSERT INTO ref_booking_slot_interval (minutes_value, label, sort_order, is_active) VALUES (45, '45 minutos', 30, 1);
INSERT INTO ref_booking_slot_interval (minutes_value, label, sort_order, is_active) VALUES (60, '60 minutos', 40, 1);
