PROMPT CREATE TABLE ref_cancel_wait_hours
CREATE TABLE ref_cancel_wait_hours (
  id_cancel_wait_hours NUMBER       GENERATED BY DEFAULT AS IDENTITY,
  hours_value          NUMBER(4,0)  NOT NULL,
  label                VARCHAR2(80) NOT NULL,
  sort_order           NUMBER(4,0)  DEFAULT 0 NOT NULL,
  is_active            NUMBER(1,0)  DEFAULT 1 NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ref_cancel_wait_hours ADD CONSTRAINT chk_ref_cancel_wait_active CHECK
ALTER TABLE ref_cancel_wait_hours
  ADD CONSTRAINT chk_ref_cancel_wait_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE ref_cancel_wait_hours ADD CONSTRAINT chk_ref_cancel_wait_value CHECK
ALTER TABLE ref_cancel_wait_hours
  ADD CONSTRAINT chk_ref_cancel_wait_value CHECK (
    hours_value IN (1, 2, 3, 4, 6, 12)
  )
/

PROMPT ALTER TABLE ref_cancel_wait_hours ADD CONSTRAINT pk_ref_cancel_wait_hours PRIMARY KEY
ALTER TABLE ref_cancel_wait_hours
  ADD CONSTRAINT pk_ref_cancel_wait_hours PRIMARY KEY (
    id_cancel_wait_hours
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ref_cancel_wait_hours ADD CONSTRAINT uq_ref_cancel_wait_value UNIQUE
ALTER TABLE ref_cancel_wait_hours
  ADD CONSTRAINT uq_ref_cancel_wait_value UNIQUE (
    hours_value
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT INSERT ref_cancel_wait_hours seed
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (1,  '1 hora de espera',  10, 1);
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (2,  '2 horas de espera', 20, 1);
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (3,  '3 horas de espera', 30, 1);
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (4,  '4 horas de espera', 40, 1);
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (6,  '6 horas de espera', 50, 1);
INSERT INTO ref_cancel_wait_hours (hours_value, label, sort_order, is_active) VALUES (12, '12 horas de espera', 60, 1);
