PROMPT CREATE TABLE ref_holiday
CREATE TABLE ref_holiday (
  id_holiday    NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  country_code  VARCHAR2(2)                 NOT NULL,
  holiday_date  DATE                        NOT NULL,
  name          VARCHAR2(120)               NOT NULL,
  is_active     NUMBER(1,0)                 DEFAULT 1 NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ref_holiday ADD CONSTRAINT pk_ref_holiday PRIMARY KEY
ALTER TABLE ref_holiday
  ADD CONSTRAINT pk_ref_holiday PRIMARY KEY (
    id_holiday
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ref_holiday ADD CONSTRAINT uq_ref_holiday_country_date UNIQUE
ALTER TABLE ref_holiday
  ADD CONSTRAINT uq_ref_holiday_country_date UNIQUE (
    country_code,
    holiday_date
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ref_holiday ADD CONSTRAINT chk_ref_holiday_active CHECK
ALTER TABLE ref_holiday
  ADD CONSTRAINT chk_ref_holiday_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE ref_holiday ADD CONSTRAINT chk_ref_holiday_country CHECK
ALTER TABLE ref_holiday
  ADD CONSTRAINT chk_ref_holiday_country CHECK (
    REGEXP_LIKE(country_code, '^[A-Z]{2}$')
  )
/

PROMPT CREATE INDEX idx_ref_holiday_lookup
CREATE INDEX idx_ref_holiday_lookup
  ON ref_holiday (
    country_code,
    holiday_date,
    is_active
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

COMMENT ON TABLE ref_holiday IS 'Calendario global de feriados nacionales por pais (ISO 3166-1 alpha-2).';
/
COMMENT ON COLUMN ref_holiday.country_code IS 'Codigo ISO de pais, p.ej. PY.';
/