PROMPT CREATE TABLE ref_plan_feature
CREATE TABLE ref_plan_feature (
  id_plan_feature NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  pln_id_plan     NUMBER        NOT NULL,
  feature_code    VARCHAR2(50)  NOT NULL,
  is_enabled      NUMBER(1,0)   DEFAULT 1 NOT NULL
)
/

PROMPT ALTER TABLE ref_plan_feature ADD CONSTRAINT pk_ref_plan_feature PRIMARY KEY
ALTER TABLE ref_plan_feature
  ADD CONSTRAINT pk_ref_plan_feature PRIMARY KEY (
    id_plan_feature
  )
/

PROMPT ALTER TABLE ref_plan_feature ADD CONSTRAINT uq_ref_plan_feature UNIQUE
ALTER TABLE ref_plan_feature
  ADD CONSTRAINT uq_ref_plan_feature UNIQUE (
    pln_id_plan,
    feature_code
  )
/

PROMPT ALTER TABLE ref_plan_feature ADD CONSTRAINT chk_ref_pf_enabled CHECK
ALTER TABLE ref_plan_feature
  ADD CONSTRAINT chk_ref_pf_enabled CHECK (
    is_enabled IN (0, 1)
  )
/

PROMPT ALTER TABLE ref_plan_feature ADD CONSTRAINT fk_ref_pf_plan FOREIGN KEY
ALTER TABLE ref_plan_feature
  ADD CONSTRAINT fk_ref_pf_plan FOREIGN KEY (
    pln_id_plan
  ) REFERENCES ref_plan (
    id_plan
  ) ON DELETE CASCADE
/

COMMENT ON TABLE ref_plan_feature IS 'Entitlements por plan. feature_code define la funcionalidad habilitada (ej. VOICE_RECEPTION, DEPOSIT_COLLECTION, APPOINTMENT_HISTORY, PROFITABILITY_ANALYTICS).';
