PROMPT CREATE TABLE ref_reminder_hours
CREATE TABLE ref_reminder_hours (
  id_reminder_hours NUMBER       GENERATED BY DEFAULT AS IDENTITY,
  hours_value       NUMBER(4,0)  NOT NULL,
  label             VARCHAR2(80) NOT NULL,
  sort_order        NUMBER(4,0)  DEFAULT 0 NOT NULL,
  is_active         NUMBER(1,0)  DEFAULT 1 NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE ref_reminder_hours ADD CONSTRAINT chk_ref_reminder_hours_active CHECK
ALTER TABLE ref_reminder_hours
  ADD CONSTRAINT chk_ref_reminder_hours_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE ref_reminder_hours ADD CONSTRAINT chk_ref_reminder_hours_value CHECK
ALTER TABLE ref_reminder_hours
  ADD CONSTRAINT chk_ref_reminder_hours_value CHECK (
    hours_value IN (2, 6, 12, 24, 48, 72)
  )
/

PROMPT ALTER TABLE ref_reminder_hours ADD CONSTRAINT pk_ref_reminder_hours PRIMARY KEY
ALTER TABLE ref_reminder_hours
  ADD CONSTRAINT pk_ref_reminder_hours PRIMARY KEY (
    id_reminder_hours
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE ref_reminder_hours ADD CONSTRAINT uq_ref_reminder_hours_value UNIQUE
ALTER TABLE ref_reminder_hours
  ADD CONSTRAINT uq_ref_reminder_hours_value UNIQUE (
    hours_value
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT INSERT ref_reminder_hours seed
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (2,  '2 horas antes',  10, 1);
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (6,  '6 horas antes',  20, 1);
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (12, '12 horas antes', 30, 1);
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (24, '24 horas antes', 40, 1);
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (48, '48 horas antes', 50, 1);
INSERT INTO ref_reminder_hours (hours_value, label, sort_order, is_active) VALUES (72, '72 horas antes', 60, 1);
