PROMPT CREATE TABLE role
CREATE TABLE role (
  id_role     NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR2(50)                NOT NULL,
  description VARCHAR2(200)               NULL,
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_active   NUMBER(1,0)                 DEFAULT 1 NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE role ADD CONSTRAINT chk_rol_active CHECK
ALTER TABLE role
  ADD CONSTRAINT chk_rol_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE role ADD CONSTRAINT pk_role PRIMARY KEY
ALTER TABLE role
  ADD CONSTRAINT pk_role PRIMARY KEY (
    id_role
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE role ADD UNIQUE
ALTER TABLE role
  ADD UNIQUE (
    name
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/


