PROMPT CREATE TABLE role_capability_default
CREATE TABLE role_capability_default (
  id_role_capability_default NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  rol_id_role                NUMBER                      NOT NULL,
  cap_id_capability          NUMBER                      NOT NULL,
  is_granted                 NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at                 TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE role_capability_default ADD CONSTRAINT pk_role_cap_default PRIMARY KEY
ALTER TABLE role_capability_default
  ADD CONSTRAINT pk_role_cap_default PRIMARY KEY (
    id_role_capability_default
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE role_capability_default ADD CONSTRAINT uq_role_cap_default UNIQUE
ALTER TABLE role_capability_default
  ADD CONSTRAINT uq_role_cap_default UNIQUE (
    rol_id_role,
    cap_id_capability
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE role_capability_default ADD CONSTRAINT fk_rcd_role FOREIGN KEY
ALTER TABLE role_capability_default
  ADD CONSTRAINT fk_rcd_role FOREIGN KEY (
    rol_id_role
  ) REFERENCES role (
    id_role
  )
/

PROMPT ALTER TABLE role_capability_default ADD CONSTRAINT fk_rcd_capability FOREIGN KEY
ALTER TABLE role_capability_default
  ADD CONSTRAINT fk_rcd_capability FOREIGN KEY (
    cap_id_capability
  ) REFERENCES capability (
    id_capability
  )
/

PROMPT ALTER TABLE role_capability_default ADD CONSTRAINT chk_rcd_granted CHECK
ALTER TABLE role_capability_default
  ADD CONSTRAINT chk_rcd_granted CHECK (
    is_granted IN (0, 1)
  )
/

COMMENT ON TABLE role_capability_default IS 'Defaults de sistema por rol base. Orgs sin override heredan esta matriz.';
/
