PROMPT CREATE TABLE professional_service
CREATE TABLE professional_service (
  id_pro_service      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  pro_id_professional NUMBER                      NOT NULL,
  ser_id_service      NUMBER                      NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_ps_org
CREATE INDEX idx_ps_org
  ON professional_service (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE professional_service ADD CONSTRAINT pk_pro_service PRIMARY KEY
ALTER TABLE professional_service
  ADD CONSTRAINT pk_pro_service PRIMARY KEY (
    id_pro_service
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_service ADD CONSTRAINT uq_pro_service UNIQUE
ALTER TABLE professional_service
  ADD CONSTRAINT uq_pro_service UNIQUE (
    pro_id_professional,
    ser_id_service
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE professional_service ADD CONSTRAINT fk_ps_organization FOREIGN KEY
ALTER TABLE professional_service
  ADD CONSTRAINT fk_ps_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_service ADD CONSTRAINT fk_ps_professional FOREIGN KEY
ALTER TABLE professional_service
  ADD CONSTRAINT fk_ps_professional FOREIGN KEY (
    pro_id_professional
  ) REFERENCES professional (
    id_professional
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE professional_service ADD CONSTRAINT fk_ps_service FOREIGN KEY
ALTER TABLE professional_service
  ADD CONSTRAINT fk_ps_service FOREIGN KEY (
    ser_id_service
  ) REFERENCES service (
    id_service
  ) ON DELETE CASCADE
/


