PROMPT CREATE TABLE service
CREATE TABLE service (
  id_service          NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER                      NOT NULL,
  name                VARCHAR2(100)               NOT NULL,
  duration_minutes    NUMBER                      NOT NULL,
  price               NUMBER                      NULL,
  is_active           NUMBER(1,0)                 DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_ser_org
CREATE INDEX idx_ser_org
  ON service (
    org_id_organization
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE service ADD CONSTRAINT chk_ser_active CHECK
ALTER TABLE service
  ADD CONSTRAINT chk_ser_active CHECK (
    is_active IN (0, 1)
  )
/

PROMPT ALTER TABLE service ADD CONSTRAINT chk_ser_duration CHECK
ALTER TABLE service
  ADD CONSTRAINT chk_ser_duration CHECK (
    duration_minutes > 0
  )
/

PROMPT ALTER TABLE service ADD CONSTRAINT chk_ser_price CHECK
ALTER TABLE service
  ADD CONSTRAINT chk_ser_price CHECK (
    price >= 0 OR price IS NULL
  )
/

PROMPT ALTER TABLE service ADD CONSTRAINT pk_service PRIMARY KEY
ALTER TABLE service
  ADD CONSTRAINT pk_service PRIMARY KEY (
    id_service
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE service ADD CONSTRAINT fk_ser_organization FOREIGN KEY
ALTER TABLE service
  ADD CONSTRAINT fk_ser_organization FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/


