PROMPT CREATE TABLE specialty
CREATE TABLE specialty (
  id_specialty        NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization NUMBER        NOT NULL,
  name                VARCHAR2(100) NOT NULL,
  description         VARCHAR2(255) NULL,
  is_active           NUMBER(1,0)   DEFAULT 1 NOT NULL,
  created_at          TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE specialty ADD PRIMARY KEY
ALTER TABLE specialty
  ADD PRIMARY KEY (
    id_specialty
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE specialty ADD CONSTRAINT fk_specialty_org FOREIGN KEY
ALTER TABLE specialty
  ADD CONSTRAINT fk_specialty_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/


