PROMPT CREATE TABLE subscription_einvoice_outbox
CREATE TABLE subscription_einvoice_outbox (
  id_outbox            NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  invoice_id           NUMBER                      NOT NULL,
  org_id_organization  NUMBER                      NOT NULL,
  status               VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  attempts             NUMBER                      DEFAULT 0 NOT NULL,
  last_error           VARCHAR2(500)               NULL,
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at         TIMESTAMP(6) WITH TIME ZONE NULL,
  emission_key         VARCHAR2(64)                NULL,
  lease_owner          VARCHAR2(64)                NULL,
  lease_until          TIMESTAMP(6) WITH TIME ZONE NULL,
  processing_started_at TIMESTAMP(6) WITH TIME ZONE NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT pk_sub_einvoice_outbox PRIMARY KEY
ALTER TABLE subscription_einvoice_outbox
  ADD CONSTRAINT pk_sub_einvoice_outbox PRIMARY KEY (id_outbox)
/

PROMPT ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT fk_sub_einv_outbox_inv FOREIGN KEY
ALTER TABLE subscription_einvoice_outbox
  ADD CONSTRAINT fk_sub_einv_outbox_inv FOREIGN KEY (invoice_id)
  REFERENCES org_subscription_invoice (id_invoice)
  ON DELETE CASCADE
/

PROMPT ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT fk_sub_einv_outbox_org FOREIGN KEY
ALTER TABLE subscription_einvoice_outbox
  ADD CONSTRAINT fk_sub_einv_outbox_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization)
  ON DELETE CASCADE
/

PROMPT ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT chk_sub_einv_outbox_status CHECK
ALTER TABLE subscription_einvoice_outbox
  ADD CONSTRAINT chk_sub_einv_outbox_status CHECK (
    status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
  )
/

-- Una sola fila outbox por invoice (ciclo de vida reutiliza la misma fila PENDING↔FAILED).
PROMPT ALTER TABLE subscription_einvoice_outbox ADD CONSTRAINT uq_sub_einv_outbox_invoice UNIQUE
ALTER TABLE subscription_einvoice_outbox
  ADD CONSTRAINT uq_sub_einv_outbox_invoice UNIQUE (invoice_id)
/

PROMPT CREATE INDEX idx_sub_einv_outbox_pending ON subscription_einvoice_outbox
CREATE INDEX idx_sub_einv_outbox_pending
  ON subscription_einvoice_outbox (status, created_at)
/

PROMPT CREATE INDEX idx_sub_einv_outbox_lease ON subscription_einvoice_outbox
CREATE INDEX idx_sub_einv_outbox_lease
  ON subscription_einvoice_outbox (status, lease_until)
/

COMMENT ON TABLE subscription_einvoice_outbox IS
  'Outbox de emision FE SIFEN: se encola al confirmar PAID; el despacho HTTP a Astro ocurre fuera de la transaccion de pago.';
/
COMMENT ON COLUMN subscription_einvoice_outbox.emission_key IS
  'Clave idempotente inmutable (INV-{invoice_id}) propagada a Astro/firmador.';
/
COMMENT ON COLUMN subscription_einvoice_outbox.lease_owner IS
  'Identificador del worker que reclamo la fila (lease).';
/
COMMENT ON COLUMN subscription_einvoice_outbox.lease_until IS
  'Vencimiento del lease; PROCESSING expirado se reclama de nuevo.';
/
COMMENT ON COLUMN subscription_einvoice_outbox.processing_started_at IS
  'Timestamp del ultimo reclamo atomico a PROCESSING.';
/
