PROMPT CREATE TABLE subscription_einvoice_webhook_log
CREATE TABLE subscription_einvoice_webhook_log (
  id_webhook_log   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  delivery_id      VARCHAR2(64) NOT NULL,
  invoice_id       NUMBER NULL,
  cdc              VARCHAR2(44) NULL,
  idempotency_key  VARCHAR2(128) NULL,
  status           VARCHAR2(20) NOT NULL,
  http_status      NUMBER NULL,
  reason           VARCHAR2(500) NULL,
  received_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
/

PROMPT ALTER TABLE subscription_einvoice_webhook_log ADD CONSTRAINT pk_sub_einv_webhook_log PRIMARY KEY
ALTER TABLE subscription_einvoice_webhook_log
  ADD CONSTRAINT pk_sub_einv_webhook_log PRIMARY KEY (id_webhook_log)
/

PROMPT ALTER TABLE subscription_einvoice_webhook_log ADD CONSTRAINT uq_sub_einv_webhook_delivery UNIQUE
ALTER TABLE subscription_einvoice_webhook_log
  ADD CONSTRAINT uq_sub_einv_webhook_delivery UNIQUE (delivery_id)
/

PROMPT ALTER TABLE subscription_einvoice_webhook_log ADD CONSTRAINT fk_sub_einv_webhook_invoice FOREIGN KEY
ALTER TABLE subscription_einvoice_webhook_log
  ADD CONSTRAINT fk_sub_einv_webhook_invoice FOREIGN KEY (invoice_id)
  REFERENCES org_subscription_invoice (id_invoice)
  ON DELETE SET NULL
/

PROMPT ALTER TABLE subscription_einvoice_webhook_log ADD CONSTRAINT chk_sub_einv_webhook_status CHECK
ALTER TABLE subscription_einvoice_webhook_log
  ADD CONSTRAINT chk_sub_einv_webhook_status CHECK (
    status IN ('ACCEPTED', 'REPLAYED', 'REJECTED')
  )
/

PROMPT CREATE INDEX idx_sub_einv_webhook_invoice ON subscription_einvoice_webhook_log
CREATE INDEX idx_sub_einv_webhook_invoice
  ON subscription_einvoice_webhook_log (invoice_id, received_at)
/

COMMENT ON TABLE subscription_einvoice_webhook_log IS
  'Trazabilidad durable y sin secretos de invoice.ready recibido desde ESIGN.';
COMMENT ON COLUMN subscription_einvoice_webhook_log.delivery_id IS
  'X-Esign-Delivery-Id estable; clave de deduplicación del webhook.';
COMMENT ON COLUMN subscription_einvoice_webhook_log.reason IS
  'Motivo resumido; nunca contiene HMAC, API key ni XML.';
