PROMPT CREATE TABLE subscription_credit_note
CREATE TABLE subscription_credit_note (
  id_credit_note         NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  source_invoice_id      NUMBER                      NOT NULL,
  org_id_organization    NUMBER                      NOT NULL,
  cdc_ref                VARCHAR2(44)                NOT NULL,
  amount                 NUMBER                      NOT NULL,
  motivo                 NUMBER                      DEFAULT 2 NOT NULL,
  description            VARCHAR2(255)               NULL,
  status                 VARCHAR2(20)                DEFAULT 'PENDING' NOT NULL,
  nce_cdc                VARCHAR2(44)                NULL,
  nce_estado_sifen       VARCHAR2(20)                NULL,
  nce_cod_res            VARCHAR2(10)                NULL,
  nce_prot_aut           VARCHAR2(30)                NULL,
  nce_error              VARCHAR2(500)               NULL,
  emission_key           VARCHAR2(64)                NULL,
  attempts               NUMBER                      DEFAULT 0 NOT NULL,
  last_error             VARCHAR2(500)               NULL,
  lease_owner            VARCHAR2(64)                NULL,
  lease_until            TIMESTAMP(6) WITH TIME ZONE   NULL,
  processing_started_at  TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at           TIMESTAMP(6) WITH TIME ZONE NULL,
  org_storage_addon_id   NUMBER                      NULL,
  org_addon_id           NUMBER                      NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT pk_sub_credit_note PRIMARY KEY
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT pk_sub_credit_note PRIMARY KEY (id_credit_note)
/

PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT fk_sub_credit_note_inv FOREIGN KEY
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT fk_sub_credit_note_inv FOREIGN KEY (source_invoice_id)
  REFERENCES org_subscription_invoice (id_invoice)
  ON DELETE CASCADE
/

PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT fk_sub_credit_note_org FOREIGN KEY
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT fk_sub_credit_note_org FOREIGN KEY (org_id_organization)
  REFERENCES organization (id_organization)
  ON DELETE CASCADE
/

PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT chk_sub_credit_note_status CHECK
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT chk_sub_credit_note_status CHECK (
    status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
  )
/

PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT chk_sub_credit_note_motivo CHECK
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT chk_sub_credit_note_motivo CHECK (
    motivo BETWEEN 1 AND 8
  )
/

-- Una NCE por FE origen (cancelación de addon mid-cycle).
PROMPT ALTER TABLE subscription_credit_note ADD CONSTRAINT uq_sub_credit_note_invoice UNIQUE
ALTER TABLE subscription_credit_note
  ADD CONSTRAINT uq_sub_credit_note_invoice UNIQUE (source_invoice_id)
/

PROMPT CREATE INDEX idx_sub_credit_note_pending ON subscription_credit_note
CREATE INDEX idx_sub_credit_note_pending
  ON subscription_credit_note (status, created_at)
/

PROMPT CREATE INDEX idx_sub_credit_note_lease ON subscription_credit_note
CREATE INDEX idx_sub_credit_note_lease
  ON subscription_credit_note (status, lease_until)
/

COMMENT ON TABLE subscription_credit_note IS
  'Notas de crédito SIFEN (NCE) por cancelación de addon con FE previa. Outbox integrado (status/lease).';
/
COMMENT ON COLUMN subscription_credit_note.source_invoice_id IS
  'FE STORAGE_ADDON aprobada que se referencia (cdc_ref).';
/
COMMENT ON COLUMN subscription_credit_note.emission_key IS
  'Clave idempotente inmutable (NCE-{source_invoice_id}) propagada a Astro/firmador.';
/
