PROMPT CREATE TABLE user_notification
CREATE TABLE user_notification (
  id_notification      NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization  NUMBER                      NOT NULL,
  org_member_id        NUMBER                      NOT NULL,
  ntype                VARCHAR2(20)                NOT NULL,
  title                VARCHAR2(500)               NOT NULL,
  body                 VARCHAR2(4000)              NULL,
  action_type          VARCHAR2(30)                DEFAULT 'OPEN_URL' NOT NULL,
  action_url           VARCHAR2(1000)              NULL,
  action_payload       CLOB                        NULL,
  appointment_id       NUMBER                      NULL,
  holiday_id           NUMBER                      NULL,
  campaign_id          NUMBER                      NULL,
  read_at              TIMESTAMP(6) WITH TIME ZONE NULL,
  deleted_at           TIMESTAMP(6) WITH TIME ZONE NULL,
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  dedupe_key           VARCHAR2(200)               NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT pk_user_notification PRIMARY KEY
ALTER TABLE user_notification
  ADD CONSTRAINT pk_user_notification PRIMARY KEY (
    id_notification
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT fk_unotif_org FOREIGN KEY
ALTER TABLE user_notification
  ADD CONSTRAINT fk_unotif_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT fk_unotif_member FOREIGN KEY
ALTER TABLE user_notification
  ADD CONSTRAINT fk_unotif_member FOREIGN KEY (
    org_member_id
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT fk_unotif_appointment FOREIGN KEY
ALTER TABLE user_notification
  ADD CONSTRAINT fk_unotif_appointment FOREIGN KEY (
    appointment_id
  ) REFERENCES appointment (
    id_appointment
  ) ON DELETE SET NULL
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT fk_unotif_holiday FOREIGN KEY
ALTER TABLE user_notification
  ADD CONSTRAINT fk_unotif_holiday FOREIGN KEY (
    holiday_id
  ) REFERENCES ref_holiday (
    id_holiday
  ) ON DELETE SET NULL
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT chk_unotif_ntype CHECK
ALTER TABLE user_notification
  ADD CONSTRAINT chk_unotif_ntype CHECK (
    ntype IN ('APPOINTMENT', 'PAYMENT', 'HOLIDAY', 'SYSTEM')
  )
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT chk_unotif_action CHECK
ALTER TABLE user_notification
  ADD CONSTRAINT chk_unotif_action CHECK (
    action_type IN ('OPEN_URL', 'OPEN_CLOSURE')
  )
/

PROMPT ALTER TABLE user_notification ADD CONSTRAINT uq_unotif_dedupe UNIQUE
ALTER TABLE user_notification
  ADD CONSTRAINT uq_unotif_dedupe UNIQUE (
    dedupe_key
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT CREATE INDEX idx_unotif_member_created
CREATE INDEX idx_unotif_member_created
  ON user_notification (
    org_member_id,
    created_at
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_unotif_member_unread
CREATE INDEX idx_unotif_member_unread
  ON user_notification (
    org_member_id,
    read_at
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_unotif_member_deleted
CREATE INDEX idx_unotif_member_deleted
  ON user_notification (
    org_member_id,
    deleted_at
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

COMMENT ON TABLE user_notification IS 'Inbox in-app (campanita). Independiente de FCM/push.';
/
COMMENT ON COLUMN user_notification.dedupe_key IS 'Clave opcional anti-duplicado, p.ej. HOLIDAY:org:holiday:member.';
/
COMMENT ON COLUMN user_notification.deleted_at IS 'Soft delete. NULL = visible. Conserva dedupe_key para que el feriado no reaparezca.';
/