PROMPT CREATE TABLE user_integration
CREATE TABLE user_integration (
  id_integration NUMBER                      GENERATED BY DEFAULT AS IDENTITY,
  usr_id_user    NUMBER                      NOT NULL,
  provider       VARCHAR2(50)                NOT NULL,
  access_token   VARCHAR2(4000)              NOT NULL,
  refresh_token  VARCHAR2(4000)              NULL,
  created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT CREATE INDEX idx_uint_user
CREATE INDEX idx_uint_user
  ON user_integration (
    usr_id_user
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE user_integration ADD CONSTRAINT pk_user_integration PRIMARY KEY
ALTER TABLE user_integration
  ADD CONSTRAINT pk_user_integration PRIMARY KEY (
    id_integration
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE user_integration ADD CONSTRAINT uq_uint_user_prov UNIQUE
ALTER TABLE user_integration
  ADD CONSTRAINT uq_uint_user_prov UNIQUE (
    usr_id_user,
    provider
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE user_integration ADD CONSTRAINT fk_uint_user FOREIGN KEY
ALTER TABLE user_integration
  ADD CONSTRAINT fk_uint_user FOREIGN KEY (
    usr_id_user
  ) REFERENCES org_member (
    id_org_member
  ) ON DELETE CASCADE
/


