PROMPT CREATE TABLE user_fcm_devices
CREATE TABLE user_fcm_devices (
  device_id          NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  platform_user_id   NUMBER         NOT NULL,
  fcm_token          VARCHAR2(1000) NOT NULL,
  platform           VARCHAR2(50)   NULL,
  created_at         TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP NULL,
  last_used_at       TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE user_fcm_devices ADD PRIMARY KEY
ALTER TABLE user_fcm_devices
  ADD PRIMARY KEY (
    device_id
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE user_fcm_devices ADD CONSTRAINT uk_fcm_token UNIQUE
ALTER TABLE user_fcm_devices
  ADD CONSTRAINT uk_fcm_token UNIQUE (
    fcm_token
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT CREATE INDEX idx_fcm_platform_user ON user_fcm_devices
CREATE INDEX idx_fcm_platform_user
  ON user_fcm_devices (
    platform_user_id
  )
  INITRANS  20
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE user_fcm_devices ADD CONSTRAINT fk_fcm_platform_user FOREIGN KEY
ALTER TABLE user_fcm_devices
  ADD CONSTRAINT fk_fcm_platform_user FOREIGN KEY (
    platform_user_id
  ) REFERENCES platform_user (
    id_platform_user
  ) ON DELETE CASCADE
/

