PROMPT CREATE TABLE workspace_setting
CREATE TABLE workspace_setting (
  id_setting              NUMBER         GENERATED BY DEFAULT AS IDENTITY,
  org_id_organization     NUMBER         NOT NULL,
  profile_slug            VARCHAR2(100)  NULL,
  description             VARCHAR2(1000) NULL,
  public_whatsapp         VARCHAR2(20)   NULL,
  logo_url                VARCHAR2(500)  NULL,
  logo_filename           VARCHAR2(255)  NULL,
  logo_mime_type          VARCHAR2(100)  NULL,
  time_format             VARCHAR2(10)   DEFAULT '24H' NULL,
  theme_pref              VARCHAR2(20)   DEFAULT 'light' NULL,
  hidden_public_price_label VARCHAR2(80) DEFAULT 'A evaluar' NULL,
  updated_at              TIMESTAMP(6)   DEFAULT CURRENT_TIMESTAMP NULL,
  unanswered_alert_action VARCHAR2(20)   DEFAULT 'KEEP' NULL,
  rsi_id_slot_interval    NUMBER         NULL,
  rh_id_reminder_hours    NUMBER         NULL,
  cwh_id_cancel_wait_hours NUMBER        NULL
)
  INITRANS  10
  STORAGE (
    NEXT       1024 K
  )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT unanswered_alert_action_ck CHECK
ALTER TABLE workspace_setting
  ADD CONSTRAINT unanswered_alert_action_ck CHECK (
    unanswered_alert_action IN ('KEEP','CANCEL')
  )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT pk_workspace_settings PRIMARY KEY
ALTER TABLE workspace_setting
  ADD CONSTRAINT pk_workspace_settings PRIMARY KEY (
    id_setting
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT uq_workspace_org UNIQUE
ALTER TABLE workspace_setting
  ADD CONSTRAINT uq_workspace_org UNIQUE (
    org_id_organization
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT uq_workspace_slug UNIQUE
ALTER TABLE workspace_setting
  ADD CONSTRAINT uq_workspace_slug UNIQUE (
    profile_slug
  )
  USING INDEX
    INITRANS  20
    STORAGE (
      NEXT       1024 K
    )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT fk_workspace_settings_org FOREIGN KEY
ALTER TABLE workspace_setting
  ADD CONSTRAINT fk_workspace_settings_org FOREIGN KEY (
    org_id_organization
  ) REFERENCES organization (
    id_organization
  ) ON DELETE CASCADE
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT fk_ws_slot_interval FOREIGN KEY
ALTER TABLE workspace_setting
  ADD CONSTRAINT fk_ws_slot_interval FOREIGN KEY (
    rsi_id_slot_interval
  ) REFERENCES ref_booking_slot_interval (
    id_slot_interval
  )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT fk_ws_reminder_hours FOREIGN KEY
ALTER TABLE workspace_setting
  ADD CONSTRAINT fk_ws_reminder_hours FOREIGN KEY (
    rh_id_reminder_hours
  ) REFERENCES ref_reminder_hours (
    id_reminder_hours
  )
/

PROMPT ALTER TABLE workspace_setting ADD CONSTRAINT fk_ws_cancel_wait_hours FOREIGN KEY
ALTER TABLE workspace_setting
  ADD CONSTRAINT fk_ws_cancel_wait_hours FOREIGN KEY (
    cwh_id_cancel_wait_hours
  ) REFERENCES ref_cancel_wait_hours (
    id_cancel_wait_hours
  )
/

